### ISSUE TITLE
Add a flag to allow console.log output to make it to the console.

### ISSUE THREAD

**Issue by javajosh** [substack/tape#100]
Often when I'm writing code I like to use my tests to get insight into the state of my code - often in preparation for writing the test itself, I will do something, inspect the state of the object, then codify the value I find as a test.

It's lo-tech, but it works, and I can't do it with tape, at the moment.

**Comment by geekytime** [comment]
For short messages, you could also call `tape.comment` to write messages out to the tap log, if you don't want to turn off your formatter. 

Just make sure to turn them off when you're done if they're debug-only.

**Comment by hom-bahrani** [comment]
as @anko mentioned this issue can arise by using faucet or another tap processor which tend to swallow console logs. I did managed to get logs to work with colortape though

`"babel-tape-runner -r src/tests/setupTests.js src/tests/**/*.js | colortape"`
