### ISSUE TITLE
Calling createStream() more than once causes weird behavior on the first test.

### ISSUE THREAD

**Issue by aghassemi** [substack/tape#105]
I have a use-case where I need to create two streams, one in objectMode and one for raw TAP output, however calling createStream() twice has a side-effect where for the very first test in the suite, the state of whether it has ended or not is ignored making t.plan(x) not work properly in the first test.

```
var test = require('tape');

test.createStream(); // all good
test.createStream(); // this extra call causes "starting test 2" to show up before "finishing test 1"

test('test one', function (t) {
  t.plan(1);
  console.log('starting test 1');
  setTimeout( function() {
    console.log('finishing test 1');
    t.pass();
  }, 100);
});

test('test two', function (t) {
   console.log('starting test 2');
   t.end();
});
```

**Comment by nfcampos** [comment]
I have the same problem (for the same reason, want both object mode and TAP output) and i'd created issue #230 because i didn't realise this issue existed.

Any update on this?

**Comment by geekytime** [comment]
Although this example is contrived, I discovered the same behavior when trying to run tests in the browser that also report results back to the CLI. 

I'd like to use the object stream to render HTML results in the browser, while sending the TAP results back to the CLI app that kicks off the tests, so they can be properly streamed into other reporters.

**Comment by keithkml** [comment]
I ran into this issue in an attempt to use `createStream` to capture the name of the currently running test, for screenshot / logging purposes.

**Comment by nhamer** [comment]
The issue is here: https://github.com/substack/tape/blob/b66f8f80928bb82f0817407880a139ad118daf01/lib/results.js#L68

The results stream is actually acting as the test-runner, so each stream picks off the common queue of pending tests - you could potentially have as many simultaneous tests as streams.
