### ISSUE TITLE
Suppress anonymous comments

### ISSUE THREAD

**Issue by andrewdeandrade** [substack/tape#108]
When calling `test()` without a name, tape prints `# (anonymous)` to the console. Anonymous comments like this should be suppressed so that you can use `test()` to group tests (async) without unnecessary line noise.

**Comment by Sequoia** [comment]
Is there a way to suppress this output completely? I'd like *just* the test reporting (ok or not ok with the error output).

**Comment by anko** [comment]
@Sequoia `node test.js | grep -v "^#"` should trim the comments and leave just

    TAP version 13
    ok 1 should throw
    ok 2 should throw
    ok 3 should throw
    ok 4 should be equal
    ok 5 should be equal

Did you mean that?

**Comment by ljharb** [comment]
If there are specific things that tape is doing that contradict TAP 13, please open new issues for them.
