### ISSUE TITLE
Unexpected behavior when running tape command

### ISSUE THREAD

**Issue by wavded** [substack/tape#109]
Using the provided test runner (`tape` command), I pass it a glob which gives me the following found files:

``` js
[ 'lib/config/test/env-test.js',
  'lib/config/test/string-test.js',
  'lib/models/test/club-test.js',
  'lib/models/test/member-test.js',
  'lib/models/test/notice-test.js',
  'lib/models/test/template-test.js',
  'lib/models/test/types/email-test.js',
  'lib/models/test/types/phone-test.js',
  'lib/models/test/types/zip-test.js',
  'lib/models/test/user-test.js' ]
```

However, as it processes the files I get the following invalid TAP output (note: TAP header appears multiple times, numbering starts over).

```
TAP version 13
# config?env
ok 1 valid json configs
# Date#toGolfHitsString
ok 2 converts < 10 month > 10 day
ok 3 converts > 10 month < 10 day
TAP version 13
# setup
# Club.schema
ok 1 chair person is required
# Club#setLogo
```

  It seems to "start over" when it switches from the `config` folder to the `models` folder but I don't know why.  Seems like it shouldn't matter.

**Comment by ljharb** [comment]
#97 was closed in favor of https://npmjs.com/cached-tape.
