### ISSUE TITLE
Can't call test.createStream().pipe(process.stdout) from inside browser

### ISSUE THREAD

**Issue by drernie** [substack/tape#113]
I am running tape in my browser with browserify, and it works great!  However, I can't find any way to add output filters.

When I do something as simple as: test.createStream().pipe(process.stdout)

I get:

[Error] TypeError: undefined is not an object (evaluating 'dest.writable')
	ondata (main.js, line 4317)
	emit (main.js, line 1776)
	drain (main.js, line 6460)
	push (main.js, line 6469)
	(anonymous function) (main.js, line 6438)
	write (main.js, line 6450)
	ondata (main.js, line 4318)
	emit (main.js, line 1776)
	drain (main.js, line 6460)
	resume (main.js, line 6523)
	resume (main.js, line 6412)
	(anonymous function) (main.js, line 6416)
	(anonymous function) (main.js, line 2286)
	forEach ([native code], line 0)
	(anonymous function) (main.js, line 2285)

[Error] TypeError: undefined is not an object (evaluating 'dest.on')
	(anonymous function) (main.js, line 4332)

**Comment by domenic** [comment]
Somebody did already do it; it's called browserify :)
