### ISSUE TITLE
Nothing in TAP output indicating skipped tests

### ISSUE THREAD

**Issue by aghassemi** [substack/tape#115]
When a whole test is skipped using `test.skip()`, there is nothing in the TAP output indicating that fact. (only skipped assertions show up as # SKIP in TAP out)

I am not sure if putting SKIP directive on the test line is valid TAP, I think it is not, so maybe we can output something like this for an skipped tests:

```
# MyTest
# ok 1 # SKIP MyTest has been skipped.
```

This can help skipped tests "not get lost" since CI reporters can report on number of skipped tests and set builds to failed or at least unstable when there are skipped tests.

**Comment by fraserc** [comment]
+1 for this as not having reporting of skipped tests seems a bit odd. I'm doing QA with a team where I'll skip tests I know fail, so that the devs can pick them up later and fix them up.

**Comment by r0mflip** [comment]
Fixed in https://github.com/substack/tape/pull/476 ...
