### ISSUE TITLE
How do I use gulp with tape?

### ISSUE THREAD

**Issue by josephfinlayson** [substack/tape#117]
http://stackoverflow.com/questions/26818795/how-do-i-use-gulp-with-tape

I'm trying to integrate gulp (the task runner) with tape. How can I do this? There doesn't seem to be an existing gulp plugin, nor does it seem I should use one. 

I've see this, but it looks really inelegant:

    var shell = require('gulp-shell')

    gulp.task('exec-tests', shell.task([
      'tape test/* | faucet',
    ]));

    gulp.task('autotest', ['exec-tests'], function() {
      gulp.watch(['app/**/*.js', 'test/**/*.js'], ['exec-tests']);
    });

I've tried this, which looks like it should work:

	var tape = require('tape');
	var spec = require('tap-spec');

	gulp.task('test', function() {
	    return gulp.src(paths.serverTests, {
	            read: false
	        })
	        .pipe(tape.createStream())
	        .pipe(spec())
	        .pipe(process.stdout);
	});

but I get a `TypeError: Invalid non-string/buffer chunk` error

**Comment by jokeyrhyme** [comment]
Gulp tasks do not always need to be streams, they can also be Promises. I have a test file like this:

```javascript
module.exports = function () {
  return new Promise(function(resolve) {
    test('blah blah', function (t) {
      /* add asserts, etc */
      t.end();
    });
    /* add more tests, etc */
    test('END: ' + __filename, function (t) {
      t.end();
      resolve();
    });
  });
};
```

Then my gulp task looks like:

```javascript
gulp.task('test', function () {
  return require('./test-file');
});
```

**Comment by tarruda** [comment]
Here's a simple way using the [xargs](https://www.npmjs.com/package/xargs) module:

```js
var xargs = require('xargs');

gulp.task('test', function() {
  return gulp.src('test/**/*.js', {read: false})
    .pipe(through.obj(function(file, enc, cb) { return cb(null, file.path); }))
    .pipe(xargs('./node_modules/.bin/tape', {stdio: ['ignore', process.stdout, process.stderr]})
});
```

If you wish to use a custom reporter:

```js
  return gulp.src(files, {read: false})
    .pipe(through.obj(function(file, enc, cb) { return cb(null, file.path); }))
    .pipe(xargs('./node_modules/.bin/tape'))
    .pipe(xargs.spawn('./node_modules/.bin/tap-dot', {stdio: ['pipe', process.stdout, process.stderr]}));
```

**Comment by sontek** [comment]
I'm finding a lot of people trying to do this and a lot of hacks on ways to do it... Is there a recommended way yet? I don't understand why this issue was closed.

**Comment by fobos** [comment]
@sontek You can use [gulp-tape](https://www.npmjs.com/package/gulp-tape) or see ho it built and write your own edition.
