### ISSUE TITLE
Explain differences with node-tap

### ISSUE THREAD

**Issue by MattiSG** [substack/tape#120]
Hi and thanks for this module  :)

You mention [`node-tap`](https://github.com/isaacs/node-tap) in the README as a source of inspiration. However, when checking out the description of that module, it reads as if they it essentially had the same goal as `tape`: to provide a basic test framework that outputs in TAP format.

A comparison with `node-tap` would be welcome to help the newcomer decide which module is the best fit for her use case.

**Comment by ljharb** [comment]
Closing, but a PR to add clarification to the readme is welcome.
