### ISSUE TITLE
Intend output of subtests

### ISSUE THREAD

**Issue by binarykitchen** [substack/tape#129]
I think that would be neat. At the moment this code

```js
test('middleware:', function(t) {
    ...

    t.test('with baiduspider', function(t) {
        ...
    })
})
```

outputs

```
...
TAP version 13
# middleware:
# with baiduspider
...
```

but indentation like that would be cool:

```
...
TAP version 13
# middleware:
    # with baiduspider
...
```

Can do a PR if you're too busy.

**Comment by koresar** [comment]
You probably should do it.

**Comment by Raynos** [comment]
Sounds good.

However lets do '# four spaces' instead of 'four spaces #'

**Comment by koresar** [comment]
I hope nobody would mind if I do it? Thanks. :)

**Comment by binarykitchen** [comment]
@koresar go ahead, i'm too busy with another crazy project of mine ...

**Comment by koresar** [comment]
Please, see https://github.com/substack/tape/pull/136

**Comment by substack** [comment]
Instead of inventing something we should wait to see what TAP14 decides: https://github.com/TestAnything/Specification/issues/2

**Comment by DeusProx** [comment]
So 3 years later still no official answer? I would like to use this implementation but having no indentation for my subtests looks really unstructured.
