### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by rektide** [substack/tape#135]
In https://github.com/substack/tape/issues/33#issuecomment-26271697 ,  @spion mentioned his experimental fork [blue tape](https://github.com/spion/blue-tape). It's been a joy to use, but now that promises are part of Node and definitely definitely a part of [io.js](https://github.com/iojs/io.js), I feel like it's appropriate to ask where I can ask: can we please get promise support in Tape?

Please support tests which return a promise. I'd love to see this usability enhancement upstreamed.

**Comment by wavded** [comment]
I'd be all for this personally (it's really nice to work with) but I know peeps like to keep things modular here.  IMO, tape isn't doing anything meaningful with what's returned anyway so... whaddayah say @substack @Raynos :)

**Comment by Raynos** [comment]
Promise support is out of scope.

tape is all about running a thunk and calling `assert.end()`. It does not have any flow control opinions.

It's also trivial to add promise support as a third party module.

**Comment by wavded** [comment]
I sorta figured :)  I'm happy with blue-tape for the time being and it has been trivial to keep up to date with tape.

**Comment by Raynos** [comment]
@wavded One tip is to use peer deps or equivelant so that users of blue-tape can control tape version

**Comment by rektide** [comment]
@Raynos out of scope? out of what scope? i thought scope was something akin to being a useful, out of the box experience for writing tests in Javascript? What do you have in mind for scope?
