### ISSUE TITLE
Wrapping text causes problems with `tap.TapConsumer`

### ISSUE THREAD

**Issue by nylen** [substack/tape#140]
The [code to wrap long `expected` and `actual` lines](https://github.com/substack/tape/blob/v3.4.0/lib/results.js#L148-L151) breaks `tap.TapConsumer` - it expects to see these keys and values on the same line.  Also see isaacs/node-tap#109.

**Comment by ljharb** [comment]
@nylen is this still an issue? If so, a PR with a failing test case (or even a fix!) would be most appreciated.

**Comment by ljharb** [comment]
Closing, pending a repro.
