### ISSUE TITLE
.contains('...') wanted

### ISSUE THREAD

**Issue by binarykitchen** [substack/tape#143]
Gotta love tape, but for the sake of DX, it would be good if parts of strings can be tested with something like `.contains()`

the api description does not mention it. wondering if i am missing something here or if it's not documented?

**Comment by Raynos** [comment]
We should stick to the assert interface. Which means

```js
assert.ok('str'.indexOf('substr') >= 0)
```

**Comment by binarykitchen** [comment]
Okay, fair enough. Just an idea to make it a bit easier for us to write tests. Close this ticket if you think it's obsolete.

**Comment by wilmoore** [comment]
> assert.ok('str'.indexOf('substr') >= 0)

:+1: - also, at some point, you'll be able to just use this:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes
