### ISSUE TITLE
expose/export `tape`?

### ISSUE THREAD

**Issue by tunnckoCore** [substack/tape#144]
Why every tap reporter not export directly tape? Then we can just add reporter to devDeps and

```js
var test = require('reporterName').tape;
```

**Comment by Raynos** [comment]
that causes dependency frustration.

If the reportor is using tape@2 then you have to upgrade the reporter before using tape@4.

Also the reporters do not depend on tape so they dont need it either.

You should become comfortable with many packages in your package.json
