### ISSUE TITLE
Coffeescript support?

### ISSUE THREAD

**Issue by hflw** [substack/tape#147]
Hi!

I was wondering if you guys would be interested in adding coffeescript support to the `bin/tape` runner. I've already gotten it to work, just wondering if you guys would be interested in me cleaning it up and making a PR, or if you have any strong opinions on how it should be implemented. Thanks!

**Comment by Raynos** [comment]
Coffeescript support is out of scope.

If you want coffeescript just run your tests with `coffeescript`. 

Feel free to publish `coffeetape` and add a link in the wiki.

**Comment by hflw** [comment]
Just wrote this: https://www.npmjs.com/package/coffeetape

I didn't see that the wiki was set up, just figured I'd post it here for others to find. Thanks!
