### ISSUE TITLE
Throws exactly

### ISSUE THREAD

**Issue by domenic** [substack/tape#150]
Any interest in something like this?

``` js

tape.Test.prototype.throwsExactly = function (fn, expected, message, extra) {
  // Based on https://github.com/substack/tape/blob/8835f51c6c4a8d45c5a415def9e25a08c144a478/lib/test.js#L424
  let caught = undefined;
  try {
    fn();
  } catch (error) {
    caught = { error };
  }

  const passed = caught && caught.error === expected;
  this._assert(passed, {
    message: message !== undefined ? message : 'should throw exactly',
    operator: 'throws exactly',
    actual: caught && caught.error,
    expected: expected,
    error: !passed && caught && caught.error,
    extra: extra
  });
};
```

Can PR if so.

**Comment by reggi** [comment]
+1

**Comment by Raynos** [comment]
I don't understand the use case for this.

When would you have access to the error object that a function throws; it should always throw a new one.

**Comment by domenic** [comment]
Any situation involving rethrowing, for example?

**Comment by Raynos** [comment]
Fair enough; I never rethrow in my code (without wrapping errors with more context).

**Comment by domenic** [comment]
Yeah. Also any situation where you e.g. "make an object errored" with a given `Error` instance, such that all its methods must from then-on throw that error. (Streams is doing that, instead of emitting `'error` events.)

**Comment by ljharb** [comment]
With v5, you'll be able to do `t.throws(thrower, (error) => error === expectedError, 'message')`, just like node's `assert.throws`, so I think this can be closed.
