### ISSUE TITLE
that new tap features

### ISSUE THREAD

**Issue by MylesBorins** [substack/tape#155]
So @isaacs has really done some fantastic work lately on tap. Is there any plan to port over some of the features?

I am quite aware that I might be volunteering myself here, but would definitely need to pair with someone in order to do this.

**Comment by vvo** [comment]
@TheAlphaNerd I am curious, was are the new great things in node-tape?

**Comment by TheAlphaNerd** [comment]
a couple features

a bunch of bug fixes

saner tap output (embedded tests showing nicely)

build in pretty reporters

I think some built in support for coverage (but I might be making that one up)

**Comment by vvo** [comment]
> I think some built in support for coverage (but I might be making that one up)

I saw a tweet from izs about this yes.

**Comment by vvo** [comment]
It seems that node-tap can almost replace tape now, what do you think?

**Comment by Raynos** [comment]
- `node-tap` does not work in the browser
 - `node-tap` spawns child proccesses
 - `node-tap` has way more loc 
 - `node-tap` wraps your test in a try catch and in a domain.

#morefeatures #moreproblems

**Comment by vvo** [comment]
in a domain? I tried to stay away from domains! Thanks for clarification raynos

**Comment by isaacs** [comment]
Tape and tap are different on purpose. 

Tape's design goal is to work in a browser. That's not taps goal. Taps goal is to be nice for testing node programs. Handling throws and using clean processes is an important part of that 

The tap runner can run tape tests and provide colored output and coverage reports.  If you put your coveralls repo token in your Travis env, you get coveralls automatically. Tape doesn't have a runner, but can hook into testing ci. 

It'd be good to borrow some of taps approach with respect to how child tests are represented, since that is a logically simpler approach. Beyond that maybe just recommend using tap as the runner, which many tape users already do.

**Comment by TheAlphaNerd** [comment]
This was exactly the advice I needed!

Had never expected to use tap as a runner.

I'll start experimenting with this and come back with notes if anything
doesn't work as expected

**Comment by isaacs** [comment]
I was wrong!  As of 2013, tape does have a runner.  It doesn't do much, though.

**Comment by TheAlphaNerd** [comment]
So I have been browserifying our tape tests and piping them into [smokestack](https://github.com/hughsk/smokestack) to run tests in the browser. How would you use the tap runner to do something similar?

**Comment by Raynos** [comment]
@isaacs 

> It'd be good to borrow some of tap's approach with respect to how child tests are represented, since that is a logically simpler approach. Beyond that maybe just recommend using tap as the runner, which many tape users already do.

I think this is a really good thing we do need; I noticed that some tap mocha reporters dont work with tape; so having the same "flavor" of TAP output from both programs makes all of the tooling work nicely (I couldnt get a deep equal diff because of how tape outputs expected and actual).

**Comment by bucaran** [comment]
It took me a while to figure this out, but [here is a simple](https://github.com/bucaran/generator-rise) workflow with ES6 tests using `tape`, Travis and coveralls.io integration.

**Comment by isaacs** [comment]
@Raynos @TheAlphaNerd I think the key shift here, if you want to take advantage of tap's `tap-mocha-reporter` outputs, would be to convert tape to use nesting for child tests (rather than juggling plan counts).  Probably there's some refactoring that could be done to leverage the code that's already in tap's `Test` class.  It could be a simple synchronous transform stream that takes the kind of objects that `tap-parser` emits, and spits out nicely nested TAP output.

**Comment by impinball** [comment]
@isaacs That's the only thing holding me back from using Tape in everything I can get away with. I don't get why it's not possible to nest messages like in Mocha and friends:

```coffee
class Foo
  foo: -> 1

t = require 'tape'

t.test 'Foo', ->
  t.test '::foo()', ->
    t.equal new Foo().foo(), 1, 'returns 1'
    t.equal new Foo().foo(), 2, 'returns 2'
```

What I expect based on most test runners:

```
ok 1 Foo ::foo() returns 1
not ok 2 Foo ::foo() returns 2
```

What I get from `tape`:

```
ok 1 returns 1
not ok 2 returns 2
```

That makes debugging a lot harder, especially without stack traces for the errors (grepping + my test convention makes it easy to spot what tests are failing).

**Comment by isaacs** [comment]
@impinball I think `tap` would do exactly what you're looking for.  If you don't need to run your tests in web browsers, node-tap is probably more what you're after.

**Comment by impinball** [comment]
Thanks! That should work for my current use case.

**Comment by impinball** [comment]
@isaacs Actually, node-tap doesn't do the expected behavior.

**Comment by isaacs** [comment]
@impinball If you can write your test in JavaScript over at https://github.com/isaacs/node-tap/issues with your expected output, I'd be happy to take a look.  This isn't really the place to discuss bugs in another project ;)

**Comment by nathanmarks** [comment]
@isiahmeadows 

One of the cool things about tape (IMO) is how simple it is to create your own test wrappers. 

Here's an example of the sort of thing I might add in to my test helpers to help organize tests with some consistency.

Helpers (using blue-tape for returning promises)
```js
import BlueTape from 'blue-tape';

export function Test (name, cb, testFn = BlueTape) {
  return testFn(name, t => cb(createTest(t, name)));
}

Test.only = function only (name, callback) {
  return Test(name, callback, BlueTape.only);
};

Test.skip = function skip (name, callback) {
  return Test(name, callback, BlueTape.skip);
};

function createTest (t, name) {
  return function test (desc, cb) {
    return t.test(`${name} - ${desc}`, cb);
  };
}
```

Test file:
```js
import { Test } from 'test/helpers';
import ContentProfile from 'lib/utils/contentProfile';

Test.only('ContentProfile', test => {

  test('object creation', ({ equal, end }) => {
    equal(
      typeof ContentProfile(),
      'object',
      'should create an object'
    );
    end();
  });

  test('async demo', ({ equal }) => {
    return ContentProfile()
      .scoreKeyword('test')
      .then(
        result =>
          equal(result, 20, 'should test returning promises')
      );
  });

  test('next tests in line', ({ ok, end }) => {
    ok(
      Array.isArray(ContentProfile().sentences),
      'should be an array'
    );
    end();
  });

});
```

Output:
```
TAP version 13
# ContentProfile
# ContentProfile - object creation
ok 1 should create an object
# ContentProfile - async demo
ok 2 should test returning promises
# ContentProfile - next tests in line
ok 3 should be an array

1..3
# tests 3
# pass  3

# ok
```

or piped through tap-spec:

```
  ContentProfile


  ContentProfile - object creation

    ✔ should create an object

  ContentProfile - async demo

    ✔ should test returning promises

  ContentProfile - next tests in line

    ✔ should be an array


  total:     3
  passing:   3
  duration:  9s

```

**Comment by bySabi** [comment]
I create a TAP helper that show nested test name beside parent test name separated by a custom `delimiter`

Any feedback is welcome.

[tap-lochness](https://github.com/bySabi/tap-lochnest)

**Comment by snuggs** [comment]
OHHH NICE @bySabi  !!! Will be adding it as a dependency to https://www.npmjs.com/package/buble-tape

**Comment by bySabi** [comment]
Hi @snuggs, I hope tap-lochness will be useful to you.

**Comment by gabrielcsapo** [comment]
@MylesBorins was the consensus to not move over features from tap into tape? ☹️
