### ISSUE TITLE
Comparison Assertions

### ISSUE THREAD

**Issue by danfinlay** [substack/tape#159]
I sometimes like to have comparison assertions, like "lessThan" or "greaterThan".

Is this the kind of feature you would accept in a PR, or that you would recommend using an external module for, to keep the `tape` core small?

**Comment by Raynos** [comment]
I'm personally in favor of restricting the `tape` API to be compatible with node `assert`. If the method is not in node core then it should probably not be in tape.

Other people may want to chime in with other opinions.

**Comment by blackbarn** [comment]
I would also agree to keep the tape core small. For additional functionality, modules are probably the best bet, e.g.,  promises [blue-tape](https://github.com/spion/blue-tape) or chai assertions [type-chai](https://github.com/jokeyrhyme/tape-chai.js).

**Comment by ljharb** [comment]
I think we've long since decided to match the API of `assert`.
