### ISSUE TITLE
Any recommended best practice to measure test execution time?

### ISSUE THREAD

**Issue by diasdavid** [substack/tape#161]
It is possible to set a timeout, but is there a simple way to print the time each test took? (Possibly with the name used for test)

**Comment by scottcorgan** [comment]
You can pipe it to tap-spec and it does rudimentary time tracking.

**Comment by diasdavid** [comment]
@scottcorgan only time tracking for the whole bundle of tests, right? I'm looking to make it test by test

**Comment by substack** [comment]
You could write a simple wrapper like this:

``` js
var tape = require('tape');

module.exports = function () {
    var t = tape.apply(this, arguments);
    var start = Date.now();
    t.on('end', function () {
        var now = Date.now();
        console.log('# time: ' + Math.round(now - start) + ' ms');
    });
    return t;
}
```

Then swap `require('tape')` with `require('yourmodule')`.

If you do end up using such a wrapper, please publish it to npm! You can look at [blue-tape](https://www.npmjs.com/package/blue-tape) for a good example of wrapping the tape API in custom behavior.

**Comment by Raynos** [comment]
Be wary of this pattern. Your better of doing 

```js
module.exports = function (tape) {
    return function () {
        var t = tape.apply(this, arguments);
        var start = Date.now();
        t.on('end', function () {
            var now = Date.now();
            console.log('# time: ' + Math.round(now - start) + ' ms');
        });
        return t;
    }
}
```

And doing `require('yourmodule')(require('tape'))`

I've run into many bugs caused by having multiple copies of tape in node_modules (tape is a secret singleton).

**Comment by substack** [comment]
That's a good point. I second @Raynos's recommendation.

**Comment by diasdavid** [comment]
Thank you @substack and @Raynos , this was really helpful. Managed to get the time I needed and published it as `timed-tape`.

**Comment by gabrielcsapo** [comment]
Any thoughts of bringing this into tape? I really would like to pass a flag to tape to get this output.

**Comment by gabrielcsapo** [comment]
@yoshuawuyts I was looking for a way to do this using tap-parser, seems like anything I try has the ability to be off by a factor of 10%, streams are unreliable

**Comment by yoshuawuyts** [comment]
Err, yeah I don't know what you're trying to do, but using tests for
benchmarks is probably not the right choice

**Comment by gabrielcsapo** [comment]
@yoshuawuyts not benchmarks, but showing how long tests take in relation to another. I agree benchmarks should not be thought of as tests, just wanted something similar to what Mocha has which allows you to see how long certain test scenarios and tests took.
