### ISSUE TITLE
Support for string exceptions

### ISSUE THREAD

**Issue by grit96** [substack/tape#162]
It would be great if there was a way of checking string exceptions. It may require a new method because `t.throws()` uses the second parameter as the message if it is string.

```javascript
function throwError() {
  throw 'Some Error';
}

test('throws error', function(t) {
  t.throws(throwError, 'Some Error', 'throws Some Error');
  t.throws(throwError, 'Some Other Error', 'does not throw Some Other Error');
  t.end();
});
```
```
TAP version 13
# throws error
ok 1 Some Error
ok 2 Some Other Error
```

**Comment by domenic** [comment]
No. This is extremely bad practice in JavaScript and tape will not support it.http://www.devthought.com/2011/12/22/a-string-is-not-an-error/

**Comment by grit96** [comment]
Is there a way of checking the exception message with `t.throws()`?
