### ISSUE TITLE
Tests never exit while timeouts or intervals are running in the background

### ISSUE THREAD

**Issue by mennovanslooten** [substack/tape#164]
## Steps to reproduce

Run this code in tape:

```javascript
var test = require('tape');

setInterval(function() {
    // I'm not really doing anything
}, 250);

test('Tape will not exit while a setInterval is running', function (t) {
    t.plan(1);
    t.equal(true, true);
    t.end();
});
```

## Expected result

The test exits successfully.

## Actual result

The test never exits.

**Comment by domenic** [comment]
You'll find this has nothing to do with tape. All node/io.js programs work this way. Here is a repro that also never exits:

```js
setInterval(function() {
    // I'm not really doing anything
}, 250);
```

**Comment by mennovanslooten** [comment]
Yes, I know that is the case. I didn't say this was caused by tape, just that I expect tape to exit when it's done testing.

Mocha exits just fine, with a similar testcase.

```javascript
setInterval(function() {
}, 250);

describe('intervals', function() {
    it('exits just fine', function() {
    });
});
```

**Comment by domenic** [comment]
That's... bizarre. I have no idea how Mocha does that. Maybe it force-exits the process (very bad practice).
