### ISSUE TITLE
Function.prototype.call

### ISSUE THREAD

**Issue by Mouvedia** [substack/tape#167]
In one of my tests I set `Function.prototype.call`. 
tape is affected by that change.

It's currently being used twice:
- [results.js](https://github.com/substack/tape/blob/74635e759f43f3976f0e469ae28be82a3f7fb111/lib/results.js#L189)
- [test.js](https://github.com/substack/tape/blob/ccfcf4f76581abc3842163dfe065198764247c85/lib/test.js#L486)

Storing a reference beforehand might help.

    var objProtoHasOwnPropCall = Object.prototype.hasOwnProperty.call.bind(Object.prototype.hasOwnProperty);

Is there a way to sandbox tape?

**Comment by ljharb** [comment]
I'm definitely in favor of making tape more robust - however, be aware that messing with `Function#call` or `Function#apply` will even break things in node core, so that's the one thing you should never do. Why are you mutating that in your tests?

**Comment by ljharb** [comment]
fwiw, this can be trivially fixed by using https://www.npmjs.com/package/has which uses `function-bind` internally and thus works on ES3, and is safe against `Function#call` being mutated after it's required.

**Comment by Raynos** [comment]
:-1: 

If you mutate globals then code breaks. This is not something tape has to be resilient against.

**Comment by ljharb** [comment]
I agree that it doesn't *have* to be - but that's not the same as saying it *shouldn't* be, for the benefit of users.

(Especially with a testing library, where users are likely to be testing that *their* code is robust against environment mutation)

**Comment by Mouvedia** [comment]
@ljharb I suspected that it wouldn't be enough. Indeed all the underlying dependencies would have to be changed as well.

Id understand if you closed the issue as won't fix.
