### ISSUE TITLE
Emit event when all tests are done

### ISSUE THREAD

**Issue by tsironis** [substack/tape#175]
I've been trying to run a mock API server that I wrote and use it with tape, but it seems that when the mock API server is running, ```tape``` cannot exit. Although I get the usual message,

```
1..39
# tests 39
# pass  39

# ok
```
the suite never really ends.

Is there a way to know when all tests are done? I've read the docs and couldn't find anything relevant.

**Comment by webthusiast** [comment]
I have the same problem. My use case: I have a web page which runs tape in the browser, and I have a phantomjs-script that loads that page. When the tests are done (and all results have been written), I want to exit the phantomjs process.

I had a look at the code, and it looks like this isn't supported. In node, the process exits when the result-stream ends. But this stream is a closure variable, so not accessible outside the `createExitHarness` function.

**Comment by Pajk** [comment]
:+1: 

This is my quick&dirty solution as the one @webthusiast mentioned did not work for me.

https://github.com/Pajk/tape/commit/a4355d8466a0894855c470164f9f7c2e5d227af5

It's called only when all tests pass but that's enough my case. I use it to disconnect node-postgres connection pool.

**Comment by akiva** [comment]
+1 I, too, encounter this, and find that the usual solution of implementing something akin to:

```javascript
tape('teardown', function (t) {
  server.close(...);
});
```
does not actual exit the test script process and the console will remain as @tsironis indicates (meaning, the server I am trying to close does, in fact, close).

**Comment by rhys-vdw** [comment]
Also interested in this feature. I tried @webthusiast's method, but the 'end' event never fires.

**Comment by rhys-vdw** [comment]
Or perhaps my problem is different - there is no summary printed at the end of the tests... It looks like the tests are simply not ending.

**Comment by Raynos** [comment]
+1

I've decided this is now a useful feature >_>;

**Comment by rhys-vdw** [comment]
@Raynos How does tape know when to emit the end event if there are async tests? Do all calls to `test` need to occur synchronously?

**Comment by Raynos** [comment]
At some point the program exits and prints the number of oks. Thats a good place to hook into.

Have to read more code.

I think it's simply reference counting.

**Comment by rhys-vdw** [comment]
My [asyc tests](https://github.com/rhys-vdw/data-mapper/blob/73308b81b4a6d1538d89d5335ae733710ee7850c/tests/integration/mapper/retrieval.js) just hangs indefinitely.

**Comment by akiva** [comment]
I was initially encountering this issue only to discover the real culprit was my MySQL connection not closing (remained hanging) after the tests. I have yet to encounter this problem with only static or local  files and processes. Figured that insight may or may not be of use to others.

**Comment by webthusiast** [comment]
I think different people might be looking at this issue from different angles. I think the OP describes a problem which could be investigated/solved if a new feature is added (@tsironis please correct me if I'm wrong). The name of the issue also suggests it's a feature request. I think related bugs might best be put in their own issues.

@Raynos: I'd like to start with writing a test, so it's probably a good start to agree on an interface. I'm thinking of making tape a promise, so that the following is possible:

    test = require('tape');
    test(...).then(onEnd);

Or:

    test = require('tape');
    Promise.all([
        test(...),
        test(...),
        ...
    ]).then(onEnd);

Maybe an additional event/callback-based implementation would be desired later, but I don't immediately see an obvious implementation for that.

**Comment by Raynos** [comment]
@webthusiast no promises.

The cleanest thing to do is:

```
var test = require('tape');

test.on('end', onEnd);
```

**Comment by yoshuawuyts** [comment]
+1 on
```js
test.on('end', onEnd)`
```
Having this hook available would probably be useful for [cuke-tap](https://github.com/yoshuawuyts/cuke-tap).

**Comment by webthusiast** [comment]
As a matter of fact, this feature is implemented in `node-tap` as [`test.tearDown(function)`](https://github.com/isaacs/node-tap#tteardownfunction), so we'd probably best stick with that?

**Comment by webthusiast** [comment]
The problem with that is that `tape` is a function. So it can't also inherit from `EventEmitter`. It could maybe use it as a mixin, but that seems a bit hacky. What about `tape.tearDown(cb)`?

**Comment by Raynos** [comment]
Tear down is reasonable.

**Comment by substack** [comment]
`tearDown()` sounds like a command that will tear apart the test, not registering a listener that fires when all the tests are finished

**Comment by Raynos** [comment]
Let's rename to

tape.onFinish(cb);

**Comment by ljharb** [comment]
no :bike: :house: here, `onFinish` SGTM

**Comment by webthusiast** [comment]
I hope this workflow is workable: both b09c92e and b01c08b should be pulled.

**Comment by Raynos** [comment]
@webthusiast do you want to open a pull request ? :)

**Comment by edravis** [comment]
+1

**Comment by webthusiast** [comment]
Hi @Raynos @substack, is this pull request still on your radar?

**Comment by rhys-vdw** [comment]
> I was initially encountering this issue only to discover the real culprit was my MySQL connection not closing (remained hanging) after the tests.

This is ended up being my problem also, I think. I wrapped certain test files in a promise handler and cleaned up my DB connections in the `finally` handler.

**Comment by jbcpollak** [comment]
+1: I'm writing a custom test runner that seems to be working perfectly, except it exits before any tests are run because the tests are asynchronous. I'm writing the custom running so I can configure and maintain output formatter and output stream (and other resources) inside JS code.

**Comment by blakeembrey** [comment]
@Raynos I'm not sure this feature entirely works. Since globbing happens asynchronously, you can't guarantee the `onFinish` hook is correct (E.g. it'll call `onFinish` before any tests even run). I think switching to synchronous globs would correct this.

**Comment by frantz** [comment]
I'm agree with @blakeembrey, I was trying to setup an `onFinish` hook in a preloaded module without any success because of asynchronous `glob` in `tape` cli.
