### ISSUE TITLE
RFC: Allow test.plan to take a callback argument called after test.end()

### ISSUE THREAD

**Issue by chrisirhc** [substack/tape#177]
This allows asynchronous tests to do clean up after the last assertion is called.

Ideally, a syntax like this would work:

```
test('async test', function (t) {
  t.plan(1, teardown);

  setTimeout(function () {
    t.ok(true, 'Yay');
  }, 1000)

  function teardown() {
    console.log('called at the end');
  }

});
```

Currently, I don't think there's any other way to do this besides creating a stream and listening for the end.

Would be happy to write a PR for this, just wanted to get a sense of whether this would be aligned with the project's goals.

**Comment by Raynos** [comment]
`t.once('end', teardown)`

**Comment by chrisirhc** [comment]
Excellent, didn't realize that was there.
