### ISSUE TITLE
Is there a way to execute an action when all tests are done?

### ISSUE THREAD

**Issue by remko** [substack/tape#185]
I'd like to call some cleanup action when all tests are finished. What is the recommended way to do this?
E.g. something like:

    setup();

    test("Some test", function (t) { ... t.end(); });
    test("Some other test", function (t) { ... t.end(); });

    test.on("end", function () { cleanup(); });
   
I tried `on('end')` and `on('done')` but that didn't work. It seems to work on the return value from `test()`, so I guess a workaround would be to wrap all tests in another `test`, but I'd like to avoid another level.

**Comment by substack** [comment]
If you put a `test()` at the end it can be used for cleanup:

``` js
test('setup', function (t) { t.end() })
test('test 1', function (t) { t.end() })
test('test 2', function (t) { t.end() })
test('teardown', function (t) { t.end() })
```
