### ISSUE TITLE
Callback an error

### ISSUE THREAD

**Issue by samuelmartineau** [substack/tape#190]
Is it a way to call a function in case of error?

I have a test like that:

```
t.true(ARRAY.every(function(item){
    return item.label
}), 'Every item should have label')
```

So I am looking for a callback to specify which item hasn't label in case of failing.

PS: I've also posted the issue on [stackoverflow](http://stackoverflow.com/questions/32626160/callback-when-test-fails-with-tape)

**Comment by ljharb** [comment]
Assuming `ARRAY` is an array in your example, why not:
```js
ARRAY.forEach(function (item) {
  t.ok(item.label, 'every item should have a label');
});
```

`every` is for when you want to reduce an array to a boolean, which isn't appropriate for testing (and getting a meaningful failure message) every item in an array.

**Comment by samuelmartineau** [comment]
Hi Jordan,

I thought about that and it was just to dicrease the number of assertion in this case (and log too)  but you're right, it's not the good testing way.

Thks

**Comment by eush77** [comment]
> it was just to dicrease the number of assertion in this case (and log too)

Here is [a nice trick from sql.js](https://github.com/kripken/sql.js/blob/be241c975342bb6edb4b6de669ce147b654205d5/test/test_blob.js#L16-L21):

```js
assert.equal(array.length, bigArray.length, "BLOB read from the database should be the same size as the one that was inserted");
for (var i=0; i<array.length; i++) {
	// Avoid doing 1e6 assert, to not pollute the console
	if (array[i]!==bigArray[i])
	assert.fail(array[i], bigArray[i] , "The blob stored in the database should be exactly the same as the one that was inserted");
}
```

This can be easily adapted to tape.
