### ISSUE TITLE
browserify tape exclude from source map

### ISSUE THREAD

**Issue by thisconnect** [substack/tape#192]
tape works nicely in the browser, when browserified. It would be helpful to have some option or advice in the docs how to exclude tape itself from being part of the sourcemap.

**Comment by ljharb** [comment]
Why would you want to exclude it from the sourcemap? Non-inlined source maps aren't downloaded unless you're in the dev tools, and they make stack traces work so well.

**Comment by thisconnect** [comment]
I wrote a small test to illustrate the issue that the sourcemap is pointing to "default_stream.js:26", but maybe I am missing something here.

```javascript
'use strict';
var tape = require('tape');

// this point to test.js:5, which is correct
console.log('this message points to test.js in sourcemap');

// the following all point to default_stream.js:26
// which is inside the tape module
// which is not very usefull
tape('sourcemap pointing to default_stream.js:26', function(t){
    t.plan(100);
    t.fail('fail');
    // stack trace points to the bundle-test.js
    // which is not so usefull
    t.error(new Error('big error here'), 'an error occured');
    t.end();
});

// this point to test.js:21, which is correct
tape('an error', function(t){
    throw new Error('a real error points to correct location in sourcemap');
});
```

See screenshot of the console with file and line number on the right

![screen shot 2015-09-19 at 11 31 47 am](https://cloud.githubusercontent.com/assets/546900/9975615/4f45e5a0-5ec2-11e5-86ac-89111c912264.png)

**Comment by thisconnect** [comment]
built with the debug flag ```browserify test/test.js --debug -o test/test-bundle.js```

**Comment by danielepolencic** [comment]
I was bitten by the same issue.

It looks like the stack trace in `tape` [doesn't account for source maps](https://github.com/substack/tape/blob/master/lib/test.js#L209-L244). Hence when an error is thrown, error lines refer to the compiled file and not the originals.

One should add some code to map the compiled file lines to the originals. In other words reimplement source maps in `Test.prototype._assert` method.

[node-source-map-support](https://github.com/evanw/node-source-map-support) seems to solve the problem at least on Chrome.

**Comment by thisconnect** [comment]
As you can see from my screenshot, a real Error somehow points to the correct location `Unchaught Error: a real error... test.js:22`. What bothers me is all the other logs that always point to `default_stream.js:26`

**Comment by thisconnect** [comment]
I am thinking of building tape in a separate file and enable blackbox script, has anyone done that?

**Comment by danielepolencic** [comment]
The real error is not process by `tape`, that's why you can see the right line number.

As for `default_stream`, [you can have a look at the code](https://github.com/substack/tape/blob/master/lib/default_stream.js#L26). All the output is redirected through that `console.log` (hence the line numbers in the console pointing to `default_stream.js:26`).

What do you mean with _black box script_?

**Comment by thisconnect** [comment]
https://developer.chrome.com/devtools/docs/blackboxing
