### ISSUE TITLE
Function to grab a screenshot

### ISSUE THREAD

**Issue by tobiastom** [substack/tape#193]
It would be nice if I could grab a screenshot of the current page and save it to some file. 

With this you could also visually validate the pages and compare them to previous versions.

**Comment by ljharb** [comment]
`tape` runs in the JS environment, typically on the command line. How do you suppose a command line tool, or a tool that doesn't know anything about the browser, would even be able to take a screenshot?

`tape` doesn't know about pages - that's a browser-only concept.

**Comment by tobiastom** [comment]
I was assuming you are using the WebDriver API internally (which is for example able to do screenshots), but obviously that is not the case.

Thanks.
