### ISSUE TITLE
util.format on msg

### ISSUE THREAD

**Issue by bahamas10** [substack/tape#194]
currently

``` js
test('foo', function (t) {
  t.comment('hello %s', 'world');
});
```

results in

```
# hello %s
```

It'd be nice if all "msg" arguments (since they all come as the last argument) can be `Array.prototype.slice.call`'d and passed through `util.format`

**Comment by ljharb** [comment]
That complexity in `tape` could be avoided by you requiring the `util.format` when you want it - is that overly burdensome?

**Comment by bahamas10** [comment]
@ljharb not at all, currently I have code like:

``` js
var f = require('util').format;
var test = require('tape');

test('foo', function (t) {
  t.comment(f('hello %s', 'world'));
});
```

It works... I could just imagine this being supported in the `tape` core.  If it is overly complex and not the place of `tape` to do the formatting of a string I understand that and am happy with what I'm currently doing.

**Comment by petemounce** [comment]
I was going to ask for this, and that's a decent workaround.

I actually want it more for the assertions than the comments - My tests all get a context to set up whether they're in production vs a number of other environments, and different tenants, and I'm so far checking that particular named cloud resources are present or not. It would be really nice to be able to just do `t.ok(resource.exists, '%s did not exist', name);` or similar.

**Comment by ljharb** [comment]
I'm thinking this isn't worth adding a `util` dependency to `tape` just to provide a bit of sugar that's trivial to add yourself in your assertions.
