### ISSUE TITLE
Tape site

### ISSUE THREAD

**Issue by kennetpostigo** [substack/tape#198]
Hey, 

I was interested in creating a website for Tape and sending a pull request. My only question is whether the entirety of the API Docs are in the README.md

**Comment by yoshuawuyts** [comment]
@kennetpostigo If you're creating a documentation site, it might be best to do that in a separate repo. That way pull-requests and commits for the two concerns stay nicely separated. Also: to my knowledge the README.md is where all documentation lives. Cheers!

**Comment by kennetpostigo** [comment]
@yoshuawuyts Thank you!
