### ISSUE TITLE
Tape no longer works in chrome apps

### ISSUE THREAD

**Issue by No9** [substack/tape#199]
Hi @ljharb 
This patch 
https://github.com/substack/tape/commit/88d567cdd9fcc0f7016029b8aa97e8439edb85c4 
Means that tape no longer works in chrome apps. 

The problem is that dynamic function binding is not allowed in the chrome app sandbox due to security restrictions. 
Does the patch fix a known issue or is it just housekeeping? 
If it's the latter then any chance it can be reverted? 

Hope you can help!

**Comment by yoshuawuyts** [comment]
wait, what? So this would be invalid:
```js
var regexpTest = bind.call(Function.call, RegExp.prototype.test)
```

?

Maybe it was added b/c of the following: From the [function-bind](https://github.com/Raynos/function-bind) readme:
> PhantomJS does not have Function.prototype.bind

**Comment by No9** [comment]
Yeah @yoshuawuyts and to be specific it is function-bind that is failing here
`https://github.com/Raynos/function-bind/blob/master/index.js#L38`
I can probably provide my own 'function-bind' that returns the RegExp.prototype.test if the revert isn't possible but thought I would ask here first.

**Comment by ljharb** [comment]
If by "dynamic function binding is not allowed", you mean that use of `Function` is not allowed in Chrome due to CSP restrictions, you're correct. Sadly there's no way to shim `bind` without it, and ES3 browsers don't have `Function#bind`.

One possibility (without any forking) would be to use a browserify shim that replaces `function-bind` with `Function.prototype.bind`, since you know it's available in a Chrome extension?

**Comment by ljharb** [comment]
Also - can you explain a bit about how you're using `tape` *inside a Chrome app*?

**Comment by No9** [comment]
Hi @ljharb 
Thanks for clarifying the reason for the change. 
When I said 
> I can probably provide my own function-bind 

I meant provide a shim.

That seems to be the most sensible option as there are probably more phantom folks than there are chrome app users.

FYI most of the libraries I write for chrome app uses tape.
There is an example here https://github.com/No9/chrome-fs 

It's the normal browserify approach.
https://github.com/No9/chrome-fs/blob/master/test/dat-test/write.js

But I write a little harness app to run it.
https://github.com/No9/chrome-fs/blob/master/test/chrome-app/

**Comment by No9** [comment]
Shimming and closing

**Comment by ljharb** [comment]
Thanks for pointing it out!
