### ISSUE TITLE
Request: `t.throws()` Support for error matching predicate.

### ISSUE THREAD

**Issue by rhys-vdw** [substack/tape#206]
Bluebird can [catch](http://bluebirdjs.com/docs/api/catch.html#catch) error types via a function predicate. This can be useful when you have the same error included in different places, causing an `instanceof` test to fail.

``` js
import something from 'something'; // Something also throws errors from 'some-errors'
import { SomeError } from 'some-errors';

something()
  .catch(SomeError, err => console.error('failure'));
```

The above instance can fail because the `SomeError` constructor is different to the `SomeError` constructor used by "something" module.

Anyway, I'd like to be able to support a predicate like this:

``` js
t.throws(
  () => somethingElse(),
  (error) => error.code === 'SOME_ERROR_ID',
  'failed with correct error!'
);
```

Happy to provide a PR for this.

**Comment by Raynos** [comment]
I tend to work around this in one of two ways.

Use the regular expression feature to assert something about `err.message`. 

Or do something like:

```js
var maybeErr = maybeSomethingElse();
assert.ok(maybeErr);
assert.equal(maybeErr && maybeErr.code, 'SOME_ERROR_ID');
```

**Comment by rhys-vdw** [comment]
Ends up looking like this:

```js
try {
  doSomething();
  t.fail('throws SomeError');
catch (e) {
  t.ok(isError(SomeError)(e), 'throws SomeError');
}
```

Lacks the readability. Of course I can write my own custom test, I just thought this might be worth adding into core.

**Comment by ljharb** [comment]
Closing in favor of #179; since node now supports a validation function
