### ISSUE TITLE
Connected redis client prevents tests from completing

### ISSUE THREAD

**Issue by jpiulac** [substack/tape#207]
Strange problem where the test doesn't finish when a redis client remains connected.

```javascript 
var test = require('tape');
var redis = require("redis").createClient();

test('this will not finish', function(t) {
  t.plan(1);
  t.equal(true, true);
});
```

```javascript 
//This will work as expected
var test = require('tape');
var redis = require("redis").createClient();

test('this will finish', function(t) {
  t.plan(1);
  redis.quit();
  t.equal(true, true);
});
```

Unfortunately I am using the redis client in a module and it's not so straight forward to quit the connection in my tests.

In case it helps, this is the declaration at the top of a module i'm having difficulties testing with tape.

```javascript 
var redisClient = require('redis').createClient(process.env.redis_url || null),
  throttle = require('tokenthrottle-redis')({
    rate: 5,
    window: 60 * 60 * 1000,
    expiry: 60 * 60 * 24,
  }, process.env.use_redis ? redisClient : null);
````

**Comment by wavded** [comment]
@jpiulac tape doesn't do any magic (which is a good thing IMO) so you'll have to close that Redis down yourself.  Thankfully its pretty easy by calling `redisClient.unref()` in your test suite to ensure it won't keep the event loop open when you are finished running your tests.

**Comment by Raynos** [comment]
This is a feature.

The tests did not succeed because you leaked a resource.

Resource leaks are bugs

**Comment by jpiulac** [comment]
Thank you.  That's cleared it up.
