### ISSUE TITLE
filename of failed test

### ISSUE THREAD

**Issue by tcurdt** [substack/tape#209]
Sometimes it's a bit hard to figure out where the failed test is originating from - am I missing something obvious here?

**Comment by thisconnect** [comment]
In the browser?

If you browserify and run the tests the console points to default_stream.js 26 which is not very useful
(see the screenshot https://github.com/substack/tape/issues/192#issuecomment-141640521)

**Comment by tcurdt** [comment]
Sorry for being unspecific - I was referring to node.

**Comment by tcurdt** [comment]
This is really getting frustrating:

    not ok 17 TypeError: Cannot read property 'path' of undefined
      ---
        operator: fail
      ...

How is one supposed to find the error? No file, no line number, no stacktrace.

**Comment by yoshuawuyts** [comment]
`tape` is pretty minimal; it just reports a pass / no pass - if you want something more fleshed out, try passing it through a test runner such as [tap](https://github.com/tapjs/node-tap)

Perhaps this could be improved, but using `tap` might help you narrow your error down right now. For the future I'd recommend naming your tests so any error that occurs can be tracked down without the help of tools (or potential patches onto `tape`). Cheers!

**Comment by tcurdt** [comment]
Thank God! :)
