### ISSUE TITLE
process.on('exit') is never called

### ISSUE THREAD

**Issue by jbach** [substack/tape#218]
This works:

``` JavaScript
'use strict';
let test = require('tape');
process.on('exit', () => console.log('This is called'));
test(t => {
    t.end();
    process.exit(0);
});
```

I can’t add exit handlers later on, however:

``` JavaScript
'use strict';
let test = require('tape');
test(t => {
    process.on('exit', () => console.log('Never called'));
    t.end();
    process.exit(0);
});
```

I guess this is due to [this line](https://github.com/substack/tape/blob/master/index.js#L86). Any exit listeners added after that won’t be executed before exiting.

Specifically, [`mongodb-prebuilt`](https://github.com/winfinit/mongodb-prebuilt)(which is used by [`Mockgoose`](https://github.com/mccormicka/Mockgoose)) leaves `mongod` processes running, due to the [handler](https://github.com/winfinit/mongodb-prebuilt/blob/master/index.js#L80) not being called.

Is this intended behavior?

**Comment by Raynos** [comment]
@jbach there is only so much we can do.

You can add a patch to tape where before calling `process.exit()` it runs all the other event listeners.

**Comment by nathanmarks** [comment]
@jbach can you use `Test.onFinish(cb)` to shut down other processes? This is what I do in my own tests to shut down redis connections and DB connections.

**Comment by ljharb** [comment]
I think you can use the onFinish and/or onFailure events for this.
