### ISSUE TITLE
No line number provided in Windows on failed tests (and proposed fix)

### ISSUE THREAD

**Issue by AlexDM0** [substack/tape#220]
Hi,

When I'm using windows with nodejs, tape does not provide an at: field with the line numbers if a test fails. 

It is fixed by placing:
```
var windowsPath = dir.substr(1,1) === ":"; // check for windows path if the second letter is a :
if (windowsPath)
  dir = dir.replace(/(\\)/g,"/").substr(2);  // swap \ for / and remove the D: or C: from C:\
```
at https://github.com/substack/tape/blob/master/lib/test.js#L212

and inserting:
```
if (windowsPath) 
  err[i] = err[i].replace(/(\\)/g,"/");  // swap \ for / 
```
before https://github.com/substack/tape/blob/master/lib/test.js#L214

This bug is caused by the drive letter before the path which you do not seem to expect in the rest of the logic and the inverted slashes.

I can do a pull if you'd like?

Regards

**Comment by ljharb** [comment]
@AlexDM0 Given #316, is this issue resolved?

**Comment by AlexDM0** [comment]
I think it can be closed, thanks!
