### ISSUE TITLE
Why test.error() ?

### ISSUE THREAD

**Issue by ibc** [substack/tape#225]
```
t.ok(value, msg)
Assert that value is truthy with an optional description message msg.

t.error(err, msg)
Assert that err is falsy. If err is non-falsy, use its err.message as the description message.
```

Is really `t.error()` a proper name? IMHO it should be `t.noError()` or whatever but `t.error()`.

**Comment by Raynos** [comment]
There are a lot of aliases in tape that are confusing.

It's actually `t.ifError(err, msg)`

**Comment by miduga** [comment]
Even the ifError alias is confusing. It seems that is waiting that to show the message if there's an error and is doing the opposite. t.checkNoError would be better or t.noError, like @ibc said, would be nice.

**Comment by ljharb** [comment]
The API matches that of `assert` and as such is chained to it, convenience not withstanding.

**Comment by pekeler** [comment]
`ok` is tied to `_assert(value, `
`notOK` is tied to `_assert(!value, `
`error` is tied to `_assert(!err, `

I agree with @ibc , `error` is the wrong name and it should be `noError`.

**Comment by pekeler** [comment]
The various forms of `ifError` make no sense to me either.
