### ISSUE TITLE
Why automatically end isn't an option?

### ISSUE THREAD

**Issue by kuraga** [substack/tape#227]
Good day!

Why automatically end isn't an option?

Thanks.

P.S. Without `t.plan`.

**Comment by kuraga** [comment]
P.S. Without `t.plan`.

**Comment by ljharb** [comment]
@kuraga tape can't know if you have asynchronous tests or not. `t.plan` and `t.end` are explicit ways of communicating that to tape. In the scenario where there's no `t.plan` or `t.end`, there's really two possibilities: either you want the test to automatically end, or, you made an error and forgot to include a `plan`/`end` call. The risk of the latter overrides the potential benefit of the former.

**Comment by kuraga** [comment]
@ljharb yes, but other test runners solve this problem (by an additional argument in async situation?) Or we may add an option: after call `tape.makeTestsSyncDefault()`... And `t.async`/`t.plan`...

**Comment by ljharb** [comment]
Other test runners only support sync by default - adding a "done" argument is an explicit opt-in to async testing behavior. tape, on the other hand, supports async by default, which in JS is a much more sensible default.

**Comment by kuraga** [comment]
Yes I said exact the same in first option and proposed to make a switcher of default behavior in the second. Thanks.

**Comment by danny-andrews** [comment]
This behavior should really be documented somewhere, because async-by-default is quite jarring coming from *any* other javascript testing framework.

**Comment by ljharb** [comment]
It should be jarring using a javascript testing framework that *isn't* async-by-default, since that's how JS works :-)

PRs are welcome to improve the documentation.

**Comment by danny-andrews** [comment]
I'm inclined to agree with you. :) I added a note to the README [here](https://github.com/substack/tape/compare/master...danny-andrews:patch-1).
