### ISSUE TITLE
Validate Error message & type with throws()

### ISSUE THREAD

**Issue by carolynnvu** [substack/tape#237]
Is there a way to validate an Error message with throws()? I am able to verify that the Error is caught, but there doesn't seem to be a way to compare the Error message to an expected message. Here's what I have so far:

```
var test = require('tape');

test('Pass invalid params to functon', function(assert){
    assert.throws(function() { 
        new ExampleObject(undefined, "validParam"); }, TypeError, "Should throw TypeError");
});
```

Thanks!

**Comment by carolynnvu** [comment]
I think I've found a partial solution, but I've run into another issue. 

If I pass in the expected message using regex, it validates the message. However, what if I want to validate the message AND error type? 

This works for checking the message:
```
test('Pass invalid params to functon', function(assert){
    assert.throws(function() { 
        new ExampleObject(undefined, "validParam"); }, /Fail - this is the expected error message/, "Should throw TypeError");
});
```

Now checking the error type seems to return true for *any* error message, rather than the actual expected one. 
Example:
```
test('Pass invalid params to functon', function(assert){
    assert.throws(function() { 
        new ExampleObject(undefined, "validParam"); },new TypeError( "Not what is expected but still passes"), "Should throw TypeError");
});
```

I've tried wrapping the TypeError as well, but that doesn't help:
```
String(new TypeError("Not what is expected but still passes"))
```

**Comment by ljharb** [comment]
I think I'd assume you should be able to pass in `new TypeError("Not what is expected but still passes")` and have it check both the type and the message (in place of just `TypeError`).

**Comment by carolynnvu** [comment]
@ljharb I've tried that, but the test passes. 

```
test('Pass invalid params to functon', function(assert){
    assert.throws(function() { 
        new ExampleObject(undefined, "validParam"); },new TypeError( "Not what is expected but still passes"), "Should throw TypeError");
});
```

**Comment by ljharb** [comment]
right, sorry - what i mean is, i think the optimal behavior is that your above test fails, but would pass with the correct message.

**Comment by carolynnvu** [comment]
@ljharb Yes, how would I go about achieving that? I'm having some trouble; the test is passing for any message I pass, not only the correct one.

**Comment by Raynos** [comment]
Just write a helper function

```js
test('thing', function t() {
  var err = tryCatch(function () { ... });
  assert.ok(err);
  assert.equal(err.message, 'wat');
  assert.equal(err.constructor.name, 'wat');
});
```

**Comment by ljharb** [comment]
imo, that particular behavior should be what `t.throws` *does* when given an error instance (as opposed to a constructor function)

**Comment by Raynos** [comment]
@ljharb that diverges from upstream `assert` in node core. 

Tape is not here to be convenient. It's here to output TAP.

**Comment by davidaurelio** [comment]
> Tape is not here to be convenient. It's here to output TAP.

Stumbled upon this. Just wow. I will look for something convenient, then.

**Comment by davidaurelio** [comment]
> Tape is not here to be convenient.

would you mind putting this into the readme? That would have saved me time.

**Comment by dasDaniel** [comment]
I was struggling with this too. would be _convenient_ to have `isError()`. I want to assert that I did get the correct error message without wrapping a function in `throws`. Here is what I got to work...

```js
  const res = await request(url)
    .set(jsonHeaders)
    .on('error', (err) => {
      const { message } = err.response.body;
      t.equal(message, 'My exact error message');
    }).catch(err => {
      t.pass('got an error response');
      t.end();
    })
```

_note; this uses `superagent` for the async call and `tape-async` library for async wrapping, but the same should be possible with some modifications _
