### ISSUE TITLE
No "at:" line reported on errors when running through babel-node or babel-tape-runner

### ISSUE THREAD

**Issue by carpie** [substack/tape#242]
Given a hypothetical test `foo.js`:

```
var test = require('tape');

test('foo', function myTest(t) {
    t.plan(1);
    t.equal(0, 1);
});

```

If I execute with node, everything is fine:

```
$ node foo.js
TAP version 13
# foo
not ok 1 should be equal
  ---
    operator: equal
    expected: 1
    actual:   0
    at: Test.myTest (/home/carpie/tmp/foo.js:5:7)
  ...

1..1
# tests 1
# pass  0
# fail  1

```

However, if I execute under babel-node or babel-tape-runner, the `at:` indicator is lost making the
test that failed difficult to find:

```
TAP version 13
# foo
not ok 1 should be equal
  ---
    operator: equal
    expected: 1
    actual:   0
  ...

1..1
# tests 1
# pass  0
# fail  1
```

I looked into to this and found it was because the babel stack traces did not have full paths in them, so the current _failure line_ detection did not find them.  I will send a pull request with a proposed alternate method of _failure line_ detection that makes this work.

**Comment by ljharb** [comment]
The babel issue seems to have been fixed in https://github.com/babel/babel/pull/3608 and released in v6.14.0.
