### ISSUE TITLE
Handling tearing down database connections

### ISSUE THREAD

**Issue by dyerw** [substack/tape#245]
As noted in #216 the tape process will not end if you have yet to disconnect from your database. When I had one test file I was able to make a cleanup test to tear down my connections and allow the process to end at the very end of the file. Now that I have two test files I'm running them with the tape glob command and I only want to tear it down after the last file executes. 

How do others handle this? Is there a way to guarantee code runs after all tests are completed?

**Comment by substack** [comment]
[test.onFinish](https://github.com/substack/tape#testonfinishfn)

executes a callback when all tests are finished
