### ISSUE TITLE
Standalone version (to load without browserfy)

### ISSUE THREAD

**Issue by whitecolor** [substack/tape#248]
Isn't it possible to load and use `tape` in the browser without broserfying it? For example to use with browser loaders (System.js) or standalone.

**Comment by ljharb** [comment]
There's no reason to use anything "standalone" these days, since everything is a module on `npm`. I'm not familiar with how System.js works but you do generally want a build process.

**Comment by whitecolor** [comment]
System just can just load ES6/CJS modules in the browser ect. How tape can be build?

**Comment by whitecolor** [comment]
Systemjs/jspm (or stealjs another option) they can load ES6/CJS in the browser, but it can load node modules of course, so for loading libs usually built versions are used. So, if you woudn't want to include  standalone or built version (ready for loading in browser) it in dist, can you explain how tape itself could be build for browser?

**Comment by whitecolor** [comment]
[Systemjs/jspm](https://github.com/systemjs/systemjs) (or [stealjs](https://github.com/stealjs/steal) as alternative that works with NPM well) they can load ES6/CJS in the browser, but it can load node modules of course, so for loading libs usually built versions are used. So, if you woudn't want to include standalone or built version (ready for loading in browser) it in dist, can you explain how tape itself could be build for browser?

**Comment by ljharb** [comment]
You'd just `browserify` your entry point, which would `require('tape')` somewhere in it.

**Comment by whitecolor** [comment]
Ok thanks. So I can just do
```javascirpt
browserify node_modules/tape --outfile tape.js -s test
```
and then load it with system.js it works ok, so Systemjs and compatible loaders can use it (just `import test from 'tape'` with proper mapping), and and it is possible to load it via script tag.

maybe include such version in dist be default?

**Comment by ljharb** [comment]
I don't see any benefit in that - everybody should have a build step these days, and it's trivial to run it through browserify when you want that.
