### ISSUE TITLE
Don't report skipped tests as passing

### ISSUE THREAD

**Issue by awlayton** [substack/tape#251]
The spec doesn't seem to make a requirement either way, but I think the idea was that skipped tests are not "passing" since they don't run.

This example reports 2 passing tests, but I expected it to report 1 passing and 1 skipped.

``` javascript
test = require('tape');

test('foo', function(t) {
    t.pass(1, 'yay');
    t.skip('stuff');
    t.end();
});
```

**Comment by tinvaan** [comment]
Can we close this now that https://github.com/substack/tape/pull/266 is merged ?

**Comment by ljharb** [comment]
Yep!
