### ISSUE TITLE
Pass through command line arguments

### ISSUE THREAD

**Issue by barkthins** [substack/tape#258]
Need to be able to pass through command line arguments to node.  In particular --stack-size.  The default of 984kbyte feels like I'm in the 20th century.

The obvious method of --stack-size to tape didn't work.

**Comment by ljharb** [comment]
`tape` isn't necessarily a runner - you'd `node test.js` where `test.js` requires `tape`, and pass whatever flags you want.

**Comment by barkthins** [comment]
but without tape I don't get the nice globbing to select which files to test... that's the point of tape.

**Comment by ljharb** [comment]
That is true, that is indeed the point of the runner (*not* the point of tape itself tho).

Just curious - what are you doing where you need to override the stack size? I've never run into that necessity.

**Comment by barkthins** [comment]
Running the npm package 'solc', where I have no control how they use the stack.   There's probably some scaling problem in the javascript-ifier package they are using.

Really 984kbytes isn't very much in the year 2016...  the nodejs community hasn't really addressed this yet AFAICT.

**Comment by barkthins** [comment]
btw I'm not sure if it's fixable.  bash doesn't allow arguments to pass through to child scripts.   we could just recommend the user wrap nodejs in a bash script, I have an example of how to do this.

**Comment by ljharb** [comment]
They could still be explicitly passed down, though, I'd assume.

**Comment by barkthins** [comment]
well I tried and failed.  You are welcome to try

**Comment by hollowdoor** [comment]
I have a similar problem.

It looks like the runner uses a require: https://github.com/substack/tape/blob/master/bin/tape#L28-L34

I wonder how much different it would be with child processes instead. There's speed issues, and stuff.

**Comment by hollowdoor** [comment]
Here is my attempt at a work around.

```javascript
//var test = require('tape');
var path = require('path');
var spawn = require('child_process').spawn;
var glob = require('glob');
var parseArgs = require('minimist');
var cwd = process.cwd();

var argv = parseArgs(process.argv.slice(2))

argv._.forEach(function(pattern){
    glob(pattern, function (err, files) {
        files.forEach(function (file) {
            var cmd = getCommand(file)
            console.log('running test: ',cmd)
            var run = spawn('node', cmd.split(' '))
            //To get argv from npm run command -- argv
            //a tap reporter can't be in the package.json scripts.
            //Maybe a special package.json field is in order.
            var tap = spawn('tap-spec', [], {stdio:
                ['pipe', 'inherit', 'inherit']
            });

            run.stdout.pipe(tap.stdin);
        });
    });

})

function getCommand(file){
    var cmd = path.resolve(cwd, file) + ' ' + process.argv.slice(3).join(' ');
    return cmd;
}
```

The tape module is commented out because it was ok to only use it in the children.

Every test script gets the same arguments though. A script field could be used instead.

There's no easy way to differentiate the original script arguments from the `--` arguments. So multiple globs will interfere with additional positional arguments after `--` from the command line.

**Comment by ljharb** [comment]
You can use the `NODE_OPTIONS` environment variable to pass any options to node you like; I don't think the `tape` runner needs special handling for this edge case.
