### ISSUE TITLE
t.end not honored

### ISSUE THREAD

**Issue by cdaringe** [substack/tape#264]
``` js
var test = require('tape');

test('something', t => {
    t.end();
    t.ok('bananas');
    t.pass('pass');
});
```

==>

```
cdieringer@Snapper-osx:~/node/test-tape-end$ node index.js
TAP version 13
# something
ok 1 (unnamed assert)
ok 2 pass

1..2
# tests 2
# pass  2

# ok
```

this is unexpected.  i would expect t.end not not permit subsequent tests, or otherwise error on them.

**Comment by ljharb** [comment]
There'd be no way in JS to not permit subsequent tests in a containing function from a function called within it - but I agree that it should error out on adding new tests after `end` is called. @substack, @Raynos, any concerns about tightening this up?

**Comment by yoshuawuyts** [comment]
I think disallowing subsequent requests is reasonable.

**Comment by jtlapp** [comment]
Looking into this now, I could only find two detrimental effects for assertions that follow `t.end`. They only apply to asynchronous assertions that follow `t.end` and to assertions in nested tests that follow `t.end`:

1. If the harness is created with `autoclose` false (which is the default), these assertions may appear out of order. Assertions within nested tests will properly appear under the nested test comment heading, but those not within nested tests may appear under other test headings.
2. If the harness is created with `autoclose` true and the output stream closes before the assertions run, the results of the assertions will not make it into the output. If the assertions run before the stream closes, (1) applies.
