### ISSUE TITLE
`t.throws(undefined)` passes, and should not

### ISSUE THREAD

**Issue by dmitrizagidulin** [substack/tape#267]
What am I doing wrong here? `t.throws()` doesn't seem to be working (not failing the test when a function is not throwing any exceptions).

Here's a sample test, that passes successfully (instead of failing as expected):

```javascript
'use strict'

var test = require('tape')

function emptyFunction () {
  // nothing happens here
}

test('This test should fail', function (t) {
  t.plan(1)
  t.throws(emptyFunction())
})
```

I'm on Node 5.0, `tape` version `4.4.0`.

**Comment by ljharb** [comment]
@dmitrizagidulin `throws` takes a single function - you're passing it `undefined` (the *return value* of a function)

**Comment by dmitrizagidulin** [comment]
Ohh I see. Is there a way to pass parameters to that function? (and why does it count undefined as a successful throws() test?)

**Comment by yoshuawuyts** [comment]
```js
t.throws(myFunction.bind(null, 'arg1', 'arg2'))
```

```js
t.throws(function () {
  myFunction('arg1', 'arg2')
})
```

**Comment by ljharb** [comment]
@dmitrizagidulin indeed that seems like a bug - `assert.throws(undefined)` throws with "block must be a function".

**Comment by dmitrizagidulin** [comment]
Thanks! :) Appreciate the guidance and the fix.

**Comment by ljharb** [comment]
np - I'll be releasing a patch version for v1, v2, v3, and v4 shortly that will include this fix.
