### ISSUE TITLE
test grouping, only/skip for nested

### ISSUE THREAD

**Issue by whitecolor** [substack/tape#273]
I organize my tests in folloing way:
```js
tape('setup', t => {
//.. test setup steps
})
// then test it sef co
tape('test1', t => {

})
tape.skip('test2', t => {
  t.test.skip(...) // not supported
  t.test.only(...) // not supported
})
tape('the end', t => {
  t.end()
})
```
Two problems i see here:
1) Nested test do not suport `skip/only`
2) Not sure is there a better way of test grouping, do recommend to use a big nested test?
3) Run `only` test if I whant to do this I would need to put .only on `setup` (maybe `the end`) as well wich seem a little bit inconvinient.

**Comment by ljharb** [comment]
1) `t.test(…, { skip: true }, …)`
2) nesting, or, separate files, are the best way to group
3) `t.test(…, { only: true }, …)` should work for you

**Comment by whitecolor** [comment]
Ok, thanks
