### ISSUE TITLE
Recipe on how to polyfill code intended for browser environment?

### ISSUE THREAD

**Issue by binarykitchen** [substack/tape#280]
For a npm library I use tape for unit tests. But that library includes some other packages intended for browser environment only. This causes my tape unit tests to crash with errors like `ReferenceError: navigator is not defined`

What's your recommendation here? Is there anything I can polyfill my tape tests before this happens?

**Comment by vphantom** [comment]
FYI if your code is already trying to distinguish browser vs node to be able to run in both, you can avoid the error with a `typeof` operator test instead of testing `navigator` directly:

```javascript
if (typeof navigator !== 'undefined') {
  ...browser stuff...
} else {
  ...node stuff...
}
```

**Comment by binarykitchen** [comment]
yup, thanks, already did that:
https://github.com/binarykitchen/videomail-client/blob/master/src/wrappers/visuals/replay.js#L10
