### ISSUE TITLE
Question/issue about t.throws

### ISSUE THREAD

**Issue by romu70** [substack/tape#281]
Hi,
First of all, I'm a Js newbie. I'm trying to develop something with Node and I use Tape as my test framework. Here is some piece of simple code:

```
'use strict';

var initialized = false;

module.exports = {
  // Initializes the new logger
  // 
  // Inputs:
  // - path: the log file full path
  init: function (path) {
    if(path === undefined || path === null)
      throw new TypeError("Logger: the path can't be null");
  },
  
  // getter of: initialized 
  get initialized() {
    return initialized;
  }
}
```

Here is a related Tape test:

```
var test = require('tape');
var logger = require("../src/logger.js");

test("Logger initialization", function (t) {
    t.plan(2);

    t.equal(false, logger.initialized, "logger is not initialized at first time");
    t.throws(logger.init()); //, null, "logger init doesn't accept null or empty");
 });
```

As you can see, I've tried the t.throws call with a single parameters and with 3, same output, Tape doesn't catch the error, so the execution crashes and my tests end.

t.equal works as expected.

Am I doing something wrong? Thanks.

**Comment by ljharb** [comment]
`t.throws(function () { logger.init(); });`

Nothing in JS can catch errors unless it's in a try/catch or in a function (that can be invoked in a try/catch).

**Comment by romu70** [comment]
Thanks. What stupid I'm, the more simple syntax is:

```
 t.throws(logger.init);
```

And @ljharb I keep your syntax when I need to test with parameters. Thanks a lot for the help.

**Comment by ljharb** [comment]
@romu70 the other difference is that if your function uses "this", you'd need `logger.init.bind(logger)`.

**Comment by romu70** [comment]
Ok thanks. Don't understand why I read everywhere on the web Js is a simple language. Quite the opposite imho. Thanks for the tip, I'll try to remember that. This gives me some experiments ideas, cool!
