### ISSUE TITLE
Document how to use in a browser environment

### ISSUE THREAD

**Issue by vphantom** [substack/tape#282]
The tag line for Tape is "tap-producing test harness for node **and browsers**", however the README includes no example whatsoever of how to use it client-side (or in something like PhantomJS to fully automate client-side testing, which I have no experience with at this time).

I wrote a module which was written to work directly in browsers and in Node, but I can't figure out an elegant testing solution client-side.  Obviously, re-using the bulk of my server-side tests would be best, so I'd like to use Tape somehow.

Since `index.js` contains a lot of `require()` calls I assume I'm supposed to transpile Tape in some way before I can source it from a browser?  What's the simplest and cleanest way of using Tape client-side?  I wouldn't want to depend on something like "Browserify" if there's actually a 3-line trick. :smiley:

Update: based on https://ci.testling.com/guide/tape it does seem like Browserify is involved.  I'm leaving this issue open nevertheless because it would be useful to point to that page or add the relevant examples from it in your README to avoid this confusion in the future.  Also, Browserify essentially provides a Node-like polyfill for the client.  This means that for example, code looking for `window` only if `module` is undefined would never be covered.  I'm hoping to find solutions to use Tape truly on the client side...

**Comment by ljharb** [comment]
There's no trick - use browserify or something like it, for 100% of your browser JS.

**Comment by vphantom** [comment]
Ah that's unfortunate.  From my limited testing, code in wrapped by Browserify doesn't have the same environment that the naked code would have.  It's good for gaining Tape itself, but bad for the module I'm trying to test.

**Comment by ljharb** [comment]
It's virtually identical, except you don't run in the global scope directly (a strict improvement) and some extra variables are available (like `global` and `module`). Your `window` checks will be unaffected.

**Comment by vphantom** [comment]
Good point, thanks.  Right now my "works-everywhere" module is structured as:

```javascript
(function(context) {

  ...the module itself...

  if (typeof context.exports === 'object') {
    // Node.JS
    context.exports = ...;
  } else {
    // Browser: supply handy globals
    context.foo = ...;
    context.bar = ...;
  }
})(typeof module !== 'undefined' ? module : this);
```

So I guess I'd just have to refactor this to test for `window` instead of `module` to get the same branching and add support for Browserify.

**Comment by ljharb** [comment]
@vphantom the idea is that your module shouldn't be "works everywhere" in the UMD sense - ie, it should *never* create globals, and only be consumed via browserify or similar.

**Comment by vphantom** [comment]
The module in question is stand-alone (like jQuery or any other).  I don't want to lock it into some framework (such as Browserify) to be usable.  (Of course, I don't mind depending on it for testing.)

**Comment by ljharb** [comment]
It's 2016 - everything should be "locked in" to that, including things like jQuery (the fact that it creates globals is a legacy behavior). Making it easier for somebody to use a library without a module system isn't doing them any favors.

**Comment by vphantom** [comment]
When JavaScript itself adds `require()` or equivalent, it'll be a relief and I'll happily adopt.  Until then, I have no intention of forcing users into my personal preference of one of many third-party frameworks.  I agree that it's cleaner to let the user set globals for themselves, of course, if it was possible natively.  But defining one, by the module's name, is close and keeps things simple.  In Node.JS:

```javascript
var foo = require('foo');
```

...then in the browser:

```html
<script type="text/javascript" src="foo.js"></script>
<script>
// Use global 'foo' here
</script>
```

This way, a quick test is easy to implement, and nothing's in the way of whatever bundling build tool they may want to use in production.

I like that Browserify can bundle up node-ish modules and dependencies neatly for running client-side, but it's self-contained so in the example above, anything executed after the bundle wouldn't have access to any of it.  (Unless I used `global` a.k.a. `window` but that brings me back to the same logic I'm using stand-alone right now.  And I **don't** want to impose globals server-side of course!)

(My earlier example exposed several globals because it was specifically a port of GNU gettext where they're expected; I usually export a single object.)

**Comment by ljharb** [comment]
commonJS is the only module system until ES6 modules arrive, and when they do, CJS will be the thing you want to have to migrate cleanly.

The reality is that what you want here doesn't impact the fact that virtually the entire ecosystem has moved in this direction: that everything is on npm, uses commonJS exclusively, and requires browserify/webpack to properly send to the browser.

If you'd like to swim against the current, feel free! Here's tape for the browser, using browserify: https://wzrd.in/standalone/tape

**Comment by vphantom** [comment]
Thanks for your patience here (and I'm keeping the discussion here in case it benefits others in my situation).  So you're saying that even modules destined to the browser are on NPM these days?  I had definitely _not_ noticed that.  I thought "Bower" was the repository for client-side stuff, and over there you do whatever you want with its downloads.

I'll read up on commonJS; if it's the emerging standard then I'll want to join in the fun. :smile:

**Comment by ljharb** [comment]
Yes, I'm saying exactly that. Bower isn't a package manager, it's a CLI wrapper around curl-to-github.

Everything worth using is on npm.

**Comment by vphantom** [comment]
Thank you for nudging me to give Browserify a second look.  I'm hooked, and I am refactoring my projects to CommonJS (thanks to `browserify --standalone` to build that variant for users who prefer it).  Also, it seems that running browserified tests with PhantomJS is easy with:

```js
test.onFinish(function() {
  if (typeof phantom !== 'undefined') {
    phantom.exit();
  }
});
```

I was afraid it would quit before outputting the results, but so far so good.

**Comment by ljharb** [comment]
Yay, glad to hear it! Welcome to the future :-)
