### ISSUE TITLE
Question with "throws" function

### ISSUE THREAD

**Issue by romu70** [substack/tape#284]
As an fan of the TDD philosophy, I'm writing my tests first. Here is a simple example:

```
t.throws(function() { logger.log(); }, null, "logger doesn't accept no input");
```

My ```logger.log``` function doesn't exist yet, it has not been written as time of test writing. The problem is the way this test is written, it passes, because calling an undefined function raises an exception. Is there a better way to write such a test which can lead to a failure?

**Comment by ljharb** [comment]
Surround if in `if (typeof logger.log === 'function') { … }`?

**Comment by romu70** [comment]
Thanks Jordan, I'm going to add specific tests regarding functions existence, that would be even better.

**Comment by ljharb** [comment]
@romu70 you can also do `test('someFunction', { skip: typeof obj.someFunction !== 'function' }, callback)`
