### ISSUE TITLE
Test exiting before stream event called?

### ISSUE THREAD

**Issue by jamen** [substack/tape#285]
I'm using tape to test my gulp plugin, however it is saying my tests are exiting without ending.

Here is a test:
```javascript
test('compiling', t => {
  gulp.src('compiling.pug')
  .pipe(pug())
  .on('data', function(file) {
    t.deepEqual(
      file.contents.toString(),
      '<!DOCTYPE html><html class="foo" lang="en"></html>'
    );
    t.is(extname(file.path), '.html');
    t.end();
  });
});
```
And I receive something like this:
```
    ✖ test exited without ending
    -----------------------------
      operator: fail
```
Does tape not play well with streams?

**Comment by ljharb** [comment]
If you're ending the test async, you need to synchronously call `plan`. In your case, make the first line of your test be `t.plan(2);` and the test will know to wait for the callback.

**Comment by ljharb** [comment]
The `end()` call is optional, but I'd recommend keeping it.

**Comment by jamen** [comment]
I tried using `t.plan(2)` as well, but I receive a different error:
```
✖ plan != count
----------------
  operator: fail
  expected: 2
  actual:   0
```
I know the event is being called, because my tests worked with AVA.

**Comment by jamen** [comment]
Maybe my events aren't being called now mysteriously.  This seems to be an issue on my end.  Sorry for the inconvenience.

**Comment by rochdev** [comment]
I am getting the same issue. If the event is not being called, shouldn't the test never end instead of ending early with a `plan != count` error?
