### ISSUE TITLE
tape with global strict mode

### ISSUE THREAD

**Issue by PatrickHeneise** [substack/tape#286]
I'm running all projects in strict mode and haven't found another solution yet than adding `--use_strict` directly to the tape script. Maybe a second bin `safe-tape`?

https://github.com/PatrickHeneise/tape/blob/master/bin/tape#L1

**Comment by ljharb** [comment]
You *do not* want to use the v8 "use_strict" flag - that is NOT the same as strict mode, and behaves differently.

If you want your projects in strict mode, include the "use strict" directive at the top of each file.

**Comment by PatrickHeneise** [comment]
I do want strict mode but I'm kind of tired to put "use strict"; on the top of every single js file. There must be another way?

**Comment by ljharb** [comment]
You could use babel, which assumes all your code is an ES6 module, and automatically puts "use strict" at the top?

Either way this is out of scope for tape :-)

**Comment by PatrickHeneise** [comment]
I created a fork with the flag until there's a better solution.

**Comment by ljharb** [comment]
Sure, but the flag is a much worse solution than putting "use strict" at the top of every single file - and babel is also a better solution.

**Comment by PatrickHeneise** [comment]
I've been running it for a week and haven't discovered any issues. What's so bad about the --use_strict flag?

**Comment by ljharb** [comment]
https://github.com/nodejs/node-v0.x-archive/issues/7479 talks about it in depth.

**Comment by PatrickHeneise** [comment]
awesome, thanks!
