### ISSUE TITLE
output 'command' to run single failure test 'run /home/.../.js'

### ISSUE THREAD

**Issue by lesterzone** [substack/tape#287]
Provide a way to run single failure test,

from failing test, expected output:

```
node example/timing.js
TAP version 13
# timing test
ok 1 should be equal
not ok 2 should be equal
  ---
    operator: equal
    expected: 100
    actual:   107
    at: ...
    run: tape /home/../example/timing.js
  ...

1..2
# tests 2
# pass  1
# fail  1
```

**run: tape /home/../example/timing.js**

Then we copy: `tape /home/../example/timing.js` and we can run single failure test

https://github.com/substack/tape/blob/master/lib/results.js#L157

``` js
output += inner + 'run: tape' + res.file + '\n'; //without line numbers
```

Based on:

a failing unit test should tell you at a glance:
- [x] Which component is under test? 
- [x] What is the expected behavior?
- [x] What was the actual result?
- [x] What is the expected result?
- [ ] How is the behavior reproduced?

[motivation](http://tenderlovemaking.com/2015/01/23/my-experience-with-minitest-and-rspec.html#things-i-like-about-rspec)

**Comment by ljharb** [comment]
This seems pretty impossible to generate; what if `tape` was passed `-r` arguments that are necessary for the tests to run? What if `tape` wasn't even used - tape tests can be run with `node`? What if the tests are running in the browser?

Closing for now; happy to reopen if a viable and robust means is suggested.
