### ISSUE TITLE
Needs to save references to nextTick and friends to avoid side-effects from stubbing

### ISSUE THREAD

**Issue by fatso83** [substack/tape#292]
We got a bug report our way in sinonjs/lolex#66, which basically boils down to that `tape` ends up using stubbed timing functions and gets stuck. Mocha solves this issue by saving references to all global timing related functions, such as `setTimeout`, `setInterval`, `nextTick`, ..., so that later modifications will not interfere with its internal use of them.

This would be the easiest fix.

Relevant lines that uses `nextTick`:
- [example 1](https://github.com/substack/tape/commit/978431c8a6db8cf3925a8b1b95a771aa872b9283#diff-dd2e881af3311f834199c7b515cff0c7R210)
- [example 2](https://github.com/dominictarr/through/commit/903501acf73d03f584dd572b885c78c1bc9cca8b#diff-168726dbe96b3ce427e7fedce31bb0bcR49)

**Comment by yoshuawuyts** [comment]
Yeah, seems like a reasonable way of resolving this - though one might also argue that clocks should never be messed with. But it probably has its uses, so hey

__See Also:__
- [sinon docs](http://sinonjs.org/docs/)

**Comment by ljharb** [comment]
Absolutely `tape` should be robust against modification of globals - thanks for the report!

Please file one on `through` for https://github.com/dominictarr/through/commit/903501acf73d03f584dd572b885c78c1bc9cca8b#diff-168726dbe96b3ce427e7fedce31bb0bcR49 - that's a separate repo.

Your given example though is indeed a cached version of `process.nextTick` - there's one example of `setTimeout` in `tape` code, which I'll fix shortly.
