### ISSUE TITLE
Docs don't actually say what messages are for

### ISSUE THREAD

**Issue by jtlapp** [substack/tape#297]
I like to be able to write code from the documentation without experimenting to figure out what something might mean first. These docs are pretty good, but the repeated statement "optional description message ``msg``" doesn't tell me anything about this message. Is the message only conditionally shown? What is that condition -- test passing or failing?

I realize that I will have my answer with a simple experiment, but it would be helpful to say something somewhere about these messages.

**Comment by jtlapp** [comment]
Okay, so I did the test. The message is always shown. So it's a description of the tested condition. More helpful language might be:

- optional description of tested condition ``msg``
- optional description of assertion ``msg``

Saying "optional description of test" might ambiguously refer to the containing call to ``test()`` and not just the particular assertion.

Also, a "message" seems like a report of news. This isn't really news so much as a description, so ``desc`` might be a more helpful parameter name. That may explain why I assumed the message would only show under one of the conditions.

Okay, now back to more significant things...

**Comment by ljharb** [comment]
Typically the "message" with every test framework is a human-readable description of the test being performed, and is often called "message" or "description" interchangeably.

The fact that that is a common pattern doesn't mean the docs can't be improved - PRs welcome!

**Comment by jtlapp** [comment]
I posted a pull request. I noticed that a number of methods are using the `msg` parameter as a message to report a condition, so I decided to leave the parameter name unchanged. The consistent name should help make it clear that there is a string description associated with each assertion. Besides, it's best to leave the names consistent with the code as well.

I also clarified the `throws()` assertion, which otherwise doesn't say how it's used. I noticed that when `expected` is neither a function nor a regex, the assertion always passes. Is that a bug? It would be nice to help protect the programmer from herself when possible.

I could not make sense of `doesNotThrow()`. The code doesn't seem right to me either. I didn't attempt to clarify this assertion.

**Comment by jtlapp** [comment]
The pull request failed for code failing to execute? The only thing that changed was a few lines in readme.

**Comment by jtlapp** [comment]
I have found a bug in the `.only` mechanism and would like to offer a fix, but my master branch now has this readme file that won't pass tests. git/github forever confuse me.

**Comment by ljharb** [comment]
@jtlapp typically PRs are best done from a branch, not from your local master - in that case you'll want to make a branch off of `master~1` - ie, off of the remote's master, not the local master.

**Comment by jtlapp** [comment]
Okay thanks. Does that mean my master branch should only ever mirror the source repository master branch? Would I only ever pull into my master from the source repository, never merging with local branches? (Thanks for this aside helping me with mechanics.)

**Comment by jtlapp** [comment]
And now magically my original pull request is passing. Someone reran it.

**Comment by ljharb** [comment]
Yes, that's basically how it would work. Also yes, I reran it - that particular test is flaky.

**Comment by jtlapp** [comment]
Okay, thank you. Is it safe for me to pull your merge into my master, or is that going to muck things up? (I have no confidence in this. We once mucked things up pretty bad thinking we were merely merging to get everyone on the same revision.)

**Comment by ljharb** [comment]
Generally you want to always hard reset your fork's master to match the source's master.

**Comment by jtlapp** [comment]
Okay, as shown on this SO? http://stackoverflow.com/questions/1628088/reset-local-repository-branch-to-be-just-like-remote-repository-head

**Comment by ljharb** [comment]
Sure.

**Comment by jtlapp** [comment]
Pull request https://github.com/substack/tape/pull/298 took care of this.
