### ISSUE TITLE
.only runs all tests with same name

### ISSUE THREAD

**Issue by jtlapp** [substack/tape#299]
I have a fix for this already, just wanted to give it an issue # before PRing.

`.only` identifies the test to run by the name of the test. If the developer (accidentally) writes multiple tests with the same name and one of those tests is declared `.only`, all tests having this duplicated name are run.

There are two main approaches to solving this. We can enforce test name uniqueness, or we can generate a unique ID for each test and use that ID. The former would be helpful to the developer, but the latter is simpler, faster, and makes a good setup for a desperately needed feature whereby we can run a single test without having to muck with the code. (I'll post this feature shortly.)

**Comment by jtlapp** [comment]
Can someone make sure my fix doesn't introduce a race condition? A race condition could potentially happen if multiple test modules are loaded asynchronously AND the increment operator is not atomic. We might then have multiple tests with the same ID. See line 48 of `lib/test.js`.

**Comment by jtlapp** [comment]
This SO answer says that ++ is not guaranteed to be atomic, so the next question is, does tape otherwise support asynchronous loading? http://stackoverflow.com/questions/680097/ive-heard-i-isnt-thread-safe-is-i-thread-safe/680114#680114

**Comment by ljharb** [comment]
That's in C++ - JS is single-threaded. You don't have to worry about it.

**Comment by jtlapp** [comment]
Ah yes! Thanks for the reminder. I actually program in Java for Android too, where I have to worry about these things.

I've written a way to pass a command line `-n` to indicate the number of a test to run, with `-n` adding test numbers to the test titles. However, I'm having trouble writing the test suite. I've emulated `test/require.js` for my tests, but I keep getting the following:

`Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit`

Any suggestions for me? Then I'll write the feature request and make its PR. Thanks!

**Comment by jtlapp** [comment]
(My `end` event is being called, but not the `data` event. Code is otherwise directly analogous to `test/require.js` and `test/require/*.js`, as far as I can tell.)

**Comment by jtlapp** [comment]
(Okay, nevermind. My `-n` broke streaming, so gotta look at that.)
