### ISSUE TITLE
Any way to run folder of tests as different processes?

### ISSUE THREAD

**Issue by davemackintosh** [substack/tape#309]
I'm having some major issues with the Waterline ORM in [Multicolour](https://github.com/Multicolour/multicolour) and my test suite.

Waterline appears to leak objects into memory and running tape `tape tests/*.js | tap-spec` seems like it loads one process for everything (Rightly so) but I wondered if there was a way to run each file as a separate process since PRs & issues in Waterline go largely unnoticed and I'd really like my tests to rightly pass before publishing the new version.

To clarify,

If I run tape on a single file, one at a time. It works as expected 👍 . Running with a glob its random failures due to a badly written piece of software in my dependency chain 👎 

Any hope? <3

(For those interested in the random nature of the failures: https://travis-ci.org/Multicolour/multicolour/builds/153272132)

**Comment by ljharb** [comment]
Could you use `find` and iterate over the list of files, calling `tape` on each one? You'd have to manually combine the exit statuses, and TAP output, of course.

That all seems like a useful alternative `tape` runner, but not something that belongs in `tape` itself.

My suspicion is that it's easier to replace the offending dependency.

**Comment by davemackintosh** [comment]
I wish it was possible to replace, it's really only actually an issue in testing but it's pretty much the entire proposition of the tool (multiple databases at the same time and codeless switches between tech)

I considered just running separate processes and combining but I'm also running istanbul over the test suite for coverage metrics so can't :/

**Comment by ljharb** [comment]
(small plug for https://www.npmjs.com/package/istanbul-merge if you want to combine coverage reports from multiple test runs into one master report)

**Comment by davemackintosh** [comment]
Okay, now that is cool! thanks. I'll have a look at that.

**Comment by davemackintosh** [comment]
I'll consider this invalid and close @ljharb.
