### ISSUE TITLE
Test stops in the middle

### ISSUE THREAD

**Issue by jpolack** [substack/tape#310]
Hello everyone,

when i test the results from my Database the Test simply stops in the middle.
I use a Promise. See following example:

````
var realModel = {
    message: "foo"
};
var test = require("tape");
test("findModels", function(t) {
      t.plan(1);
      Model.find()
          .then(function(dbmodels) {
              t.equal(dbmodels[0].message, realModel.message);
          });
});
````

output is:

[2016-08-19 20:14:36.757] [INFO] console - TAP version 13
[2016-08-19 20:14:36.757] [INFO] console - # findModels

if i start it looks like this it just executes the ".ok" statement

````
var realModel = {
     message: "foo"
};
var test = require("tape");
test("findModels", function(t) {
      t.plan(2);
      Model.find()
          .then(function(dbmodels) {
              t.ok(dbmodels[0].id);
              t.equal(dbmodels[0].message, realModel.message);
          });
});
````

output looks like:

[2016-08-19 20:02:52.190] [INFO] console - TAP version 13
[2016-08-19 20:02:52.219] [INFO] console - # findModels
[2016-08-19 20:02:52.230] [INFO] console - ok 1 should be truthy

Any Ideas how this can happen? Seems like there is a problem with executing t.equal. Is there anything wrong with my Code?

Thanks in advance

Jonah

**Comment by ljharb** [comment]
Just in case, try adding a `.catch(t.fail)` on the end of your promise.

**Comment by jpolack** [comment]
Oh yeah,

with the `.catch(t.fail)` a declaration error was catched, which was not catched before.

Not it works as expected.

Thank you very much, sometimes the solution is just in front of you
