### ISSUE TITLE
What does missing plan mean?

### ISSUE THREAD

**Issue by playground** [substack/tape#311]
This test is taking a while to run too, it times out after 30sec
```js
test('Healthcheck', function(assert) {
  assert.plan(2);

  request.get(`${mock.baseUrl}/user/healthcheck`, function(err, res) {
    assert.equal(res.statusCode, 200);
    assert.equal(res.body, 'healthy', 'should return Healthcheck');
    assert.end();
  });
});
```
```sh
✓ should be equal
  ✓ should return Healthcheck
  1) missing plan

  2 passing (5s)
  1 failing

  1) test/health-check.test.js missing plan:
     missing plan
```

**Comment by ljharb** [comment]
I'm not really sure - that phrase doesn't seem to appear anywhere in the codebase. Can you include the entire file, specifically the part that's requiring `test`?

**Comment by playground** [comment]
check.test.js
========================
var test = require('tape');
var request = require('request');
var nock = require('nock');

//var app = require('../bin/www');
var mock = require('./mocks/mock');

nock(mock.baseUrl)
  .get(`/user/${mock.sender}/profile`)
  .reply(200, mock.userProfile);

test('User Test', function(assert) {
  //assert.plan(2);

  request.get(`${mock.baseUrl}/user/${mock.sender}/profile`, function(err, res) {
    let json = JSON.parse(res.body);
    console.log('data99', json, mock.sender);
    assert.equal(json.data.id, mock.sender);
    assert.end();
  });
});

==================================
> tap --cov -R=spec test/*.test.js

Server listening on port 3001 !
GET /user/healthcheck 200 5.949 ms - 7
test/health-check.test.js
  ✓ should be equal
  ✓ should return Healthcheck
  1) missing plan

**Comment by ljharb** [comment]
and if you uncomment the "plan", the error goes away?

If so, that's expected. async tests need to either declare a planned number of assertions, or synchronously end.

**Comment by playground** [comment]
The missing plan error remains with or without comment out  //assert.plan(2);

I added another test suite, and am trying to understanding the reporting result

GET /user/healthcheck 200 5.372 ms - 7
test/health-check.test.js
  ✓ should be equal
  ✓ should return Healthcheck
  1) missing plan
Server listening on port 3001 !
test/user.test.js
  ✓ name should be Some Guy
  2) test/user.test.js  (what does this mean?)

  3 passing (4s)
  2 failing

  1) test/health-check.test.js missing plan:
     missing plan
  

  2) test/user.test.js:
     test/user.test.js

**Comment by ljharb** [comment]
I'm not really sure :-/ do you have a repo where I can reproduce this?

**Comment by playground** [comment]
Here is the sample repo
https://github.com/playground/sample

try comment and uncomment out different asserts, it will produce different errors.


test('First test!', function (assert) {
  request.get('http://localhost:3000/api/users', function(err, res) {
    let json = JSON.parse(res.body);
    assert.equal(json[0], 'John', 'name should be John');
    //assert.equal(json[1], 'Joe', 'name should be John');
    assert.end();
  });
});

test('Second test!', function (assert) {
  request.get('http://localhost:3000/api/users', function(err, res) {
    let json = JSON.parse(res.body);
    assert.equal(json[0], 'John', 'name should be John');
    //assert.equal(json[1], 'Joe', 'name should be Joe');
    assert.end();
  });
});

**Comment by playground** [comment]
if you comment out the second test, you will get

Server running on port 3000
test/user.test.js
  ✓ name should be John
  1) test/user.test.js

  1 passing (2s)
  1 failing

  1) test/user.test.js:
     test/user.test.js

**Comment by ljharb** [comment]
In both cases, you'd need to `assert.plan()` *outside* of the `request.get`, at the top level of the test.

**Comment by playground** [comment]
I tried that already with assert.plan(1), still gets
test('First test!', function (assert) {
  assert.plan(1);

  request.get('http://localhost:3000/api/users', function(err, res) {
    let json = JSON.parse(res.body);
    assert.equal(json[0], 'John', 'name should be John');
    //assert.equal(json[1], 'Joe', 'name should be John');
    assert.end();
  });
});

test('Second test!', function (assert) {
  assert.plan(1);

  request.get('http://localhost:3000/api/users', function(err, res) {
    let json = JSON.parse(res.body);
    assert.equal(json[0], 'John', 'name should be John');
    //assert.equal(json[1], 'Joe', 'name should be Joe');
    assert.end();
  });
});
Server running on port 3000
test/user.test.js
  ✓ name should be John
  ✓ name should be John
  1) missing plan

  2 passing (2s)
  1 failing

  1) test/user.test.js missing plan:
     missing plan
  
npm ERR! Test failed.  See above for more details.

**Comment by ljharb** [comment]
That's very strange. I'd love to see an example repo I could clone and reproduce locally.

**Comment by playground** [comment]
https://github.com/playground/sample

**Comment by ljharb** [comment]
You're using `tap` there, not `tape`. Run tape tests with `node` or `tape`. When I run `node test/user.test.js` everything works (altho it doesn't exit, because the server is still started, and not killed on test exiting)

**Comment by playground** [comment]
hmm, do you know why it is failing with tap?  Tap gives a very nice report.

**Comment by ljharb** [comment]
I'm not really sure - our tests use tap v0.7 so it's highly likely that we're not compatible with the latest version of tap. Typically you want to use `node` or `tape` as a runner, and then pipe the output to a formatter (like `faucet`, or perhaps `tap` itself).

**Comment by playground** [comment]
Can you share with me one of your test and your setup?

**Comment by ljharb** [comment]
https://github.com/ljharb/mocha-wrap/blob/master/package.json#L24
