### ISSUE TITLE
devDependencies out-of-date. intentional? 

### ISSUE THREAD

**Issue by nelsonic** [substack/tape#312]
Hi Fellow Tapers, 

we are just busy finishing writing a "_why you should use tape_" post and noticed that the `devDependecies` are out-of-date https://david-dm.org/substack/tape?type=dev  [![devDependencies Status](https://david-dm.org/substack/tape/dev-status.svg)](https://david-dm.org/substack/tape?type=dev)

![tape-out-dependencies-out-of-date](https://cloud.githubusercontent.com/assets/194400/18007163/ceb9d0cc-6b9a-11e6-9745-9b692708c399.png)

Is this intentional or, can we submit a PR updating them?

**Comment by yoshuawuyts** [comment]
oh yeah pretty sure it's not intentional - PR welcome

**Comment by nelsonic** [comment]
When we update to the latest versions of `tap` and `tap-parser` we get quite a few failing tests:
![tape-tests-fail-when-devdependencies-updated](https://cloud.githubusercontent.com/assets/194400/18007480/2a1b7cbc-6b9c-11e6-98d2-7e79b20d890e.png)

So there might be some re-work required for a PR.... worth it?

**Comment by yoshuawuyts** [comment]
While not crucial it'd be appreciated I reckon

**Comment by ljharb** [comment]
The failing tests are indeed the reason they aren't updated. It would be quite appreciated to get a minimal PR to update them.

**Comment by nelsonic** [comment]
Hi @yoshuawuyts & @ljharb (_and the rest of the Tape Team!_),
have made the necessary update to the _first_ test that needs to be updated to work with the _latest_ version of Tap. please see: https://github.com/nelsonic/tape/commit/7db3bdcc5ca5b1f7be6ccf112a4438ed47be65c3

followed the example found in this PR: https://github.com/substack/tape/pull/171/files which was merged by @Raynos 

When the test is run we get:

<img width="473" alt="tape-array-test-passes-after-update" src="https://cloud.githubusercontent.com/assets/194400/18030921/1caaf572-6cc2-11e6-9b76-201e0b9ed098.png">


Just to _confirm_: am I OK to continue updating the tests as necessary to bring them into line with the latest `tap` which matches the Tap Spec: https://testanything.org/tap-specification.html ? 

Let me know and I will finish off the update and submit a PR today. (_thanks!_)

**Comment by ljharb** [comment]
Those changes seem reasonable, thanks! Other than trying to keep diffs as minimal as possible, I'd love to review that PR.

**Comment by nelsonic** [comment]
@ljharb thanks for confirming. I will avoid updating the test arguments to keep diffs minimal. 

The tests I've updated so far have the following `.map` over the `stdout` stream:

```js
var rs = rows.map(function (r) {
    if (r && typeof r === 'object') {
        return { id : r.id, ok : r.ok, name : trim(r.name) };
    }
    else return r;
});
```
see: [`test/array.js#L15-L20`](https://github.com/substack/tape/blob/092344b906cd3774ba1812d2db431e77916c9f19/test/array.js#L15-L20)

Given that the `stdout` stream that we are reading is converted to a string before being compared
this `.map` is redundant. Can I _remove_ it?  (_or am I missing something?_)
e.g: https://github.com/nelsonic/tape/commit/0e04ba75d9d16a7ecf7fd39dedbc4b63401dd826

I've opened a PR so you can see what it _will_ look like: https://github.com/substack/tape/pull/314/files

**Comment by nelsonic** [comment]
@ljharb / @yoshuawuyts PR ready for review: https://github.com/substack/tape/pull/314/files (_thanks!_)

**Comment by nelsonic** [comment]
Yay! 
![tape-devdependencies-up-to-date](https://cloud.githubusercontent.com/assets/194400/18219421/65f6c780-7161-11e6-9f92-309b2550d54a.png)
