### ISSUE TITLE
Tape Drive Unavailable from Substack.net

### ISSUE THREAD

**Issue by snuggs** [substack/tape#315]
## Problem
The current link within README points to a bum resource. _Please see below_
![Tape Drive](http://substack.net/images/tape_drive.png)

Linked to Substack.net
http://substack.net/images/tape_drive.png

## Solution
Found a version on the "Way Back Machine" but don't think I would trust it.
![Tape Drive](https://cloud.githubusercontent.com/assets/38223/18106015/bc0426c0-6ecf-11e6-819c-3075b35bb7eb.png)

https://camo.githubusercontent.com/50dd49050de38c87a28ab6aa0b09bbe2d042cba1/687474703a2f2f737562737461636b2e6e65742f696d616765732f746170655f64726976652e706e67

**Comment by ljharb** [comment]
That is in fact the original image - I think we can stick it in the gh-pages branch and reference it that way.

**Comment by Download** [comment]
What I do with these images is I keep them right there in the repo. Then I link to them via [RawGit](https://rawgit.com/). The only downside is, I have to add the image, make a release and then point the link to that release. Only after that can I add it in the README, as RawGit frowns upon linking directly to master. But it works well apart from that.

**Comment by snuggs** [comment]
@Download @ljharb sooo what do we do? /cc @substack

**Comment by ljharb** [comment]
We wait patiently for @substack to respond.

**Comment by Download** [comment]
This is why projects need multiple contributors with commit rights. But of course if you care about this topic you can make a PR with the needed changes. It would be a pretty good way to get your feet wet in Open Source development. If you want to try:

* Fork this project
* Clone your fork to your local machine
* Create a new branch
* Make some changes
* Commit your changes
* Push your changes to GitHub
* On GitHub it will show a nice button: Create Pull Request. Hit it!
* Wait for @substack to show up and merge your PR
* ENJOY the new and improved logo and the fame and glory you get as a contributor to Open Source

**Comment by yoshuawuyts** [comment]
website is back up btw, this issue can be closed I think - tho might be an idea to host the image on github idk

**Comment by ljharb** [comment]
@Download the issue here is that github p lay allows owners to change repo gh-pages settings on individually owned repos. I have commit and publish rights, but that's not enough to fix this particular (insignificant) issue.

It can not be solved by a PR because I do not want the image assets to forever bloat the size of the repo.

**Comment by yoshuawuyts** [comment]
@ljharb a  workaround for that is to upload to github in a comment and link the address from that in a repo; they tend to keep their CDN stuff seriously hah
