### ISSUE TITLE
t.throws throws with "Cannot delete property"

### ISSUE THREAD

**Issue by dcousens** [substack/tape#320]
Reference: https://github.com/substack/tape/blob/master/lib/test.js#L448

``` javascript
        delete err.message;
               ^

TypeError: Cannot delete property 'message' of Error
    at Test.throws (../node_modules/tape/lib/test.js:448:16)
```

This seems like really odd behaviour and doesn't work with custom errors?

**Comment by ljharb** [comment]
https://github.com/substack/tape/commit/f66724fc98e6bede53afa54ca83521bdc50f8a2f implies that the purpose is ensuring that the property is enumerable (even in ES3).

It should work fine with custom errors, unless their "message" property is nonconfigurable for some reason. What test code is creating this error?

**Comment by dcousens** [comment]
The error is coming from https://github.com/dcousens/typeforce/blob/master/index.js#L34-L44,  as I'm putting that repository under `tape` at the moment.

Even ensuring the property is `enumerable: true` doesn't solve my issue?

**Comment by ljharb** [comment]
So, a few reactions:
 - you should probably use `Object.defineProperty` inside your getter to change it into a data property once it's cached instead of making it always be a (slow) getter
 - since the goal of that delete + reassign of "message" was enumerability, I think a) it should not do that if the property is already enumerable, and b) it should detect if the property is nonconfigurable, and avoid attempting to modify it if that's the case.

**Comment by dcousens** [comment]
> you should probably use Object.defineProperty inside your getter to change it into a data property once it's cached instead of making it always be a (slow) getter

That was my first reaction,  but node 6 doesn't allow that.

``` js
TypeError: Cannot redefine property: message
```

> since the goal of that delete + reassign of "message" was enumerability, I think a) it should not do that if the property is already enumerable, and b) it should detect if the property is nonconfigurable, and avoid attempting to modify it if that's the case.

Couldn't you just check that via:

``` javascript
assert(Object.keys(err).some(x => x === 'message'))
```

**Comment by ljharb** [comment]
Even easier, and ES3-compatible, with `Object.prototype.isEnumerable.call`. I'll make that change tomorrow, at least.

Because `configurable` defaults to false, you'll have to change the getter defineProperty to have `configurable: true` to be able to redefine it later.

**Comment by dcousens** [comment]
Thanks mate,  so for tomorrows change,  I'll be able to get away with changing: `enumerable: true` for my purposes?

**Comment by ljharb** [comment]
Yep, that's the idea.

**Comment by dcousens** [comment]
Thanks @ljharb :)
