### ISSUE TITLE
[Add] test.isIN(var, array, msg)

### ISSUE THREAD

**Issue by hustcc** [substack/tape#321]
Is there any API like below: 

```js
test.isIn(var, array, msg)
```

looking up the repo, maybe not~

**Comment by dcousens** [comment]
`test.true(array.indexOf(var), msg` ?

**Comment by hustcc** [comment]
I use tape like [this](https://github.com/hustcc/timeago.js/blob/master/tests/locales_test.js#L15).

but I think `isIn` appear frequently in test and testcase. Only for reference.

**Comment by ljharb** [comment]
This would be far too opinionated, let alone not part of the `assert` API. Use `indexOf`, `lastIndexOf`, `includes`, etc on your own, and use tape to test to the return value.
