### ISSUE TITLE
Tape test ends immediately

### ISSUE THREAD

**Issue by daposy** [substack/tape#322]
I have a module for executing tape tests. I would like for the tests to execute and log separately. This is the code I have for creating a harness and test. Console.log(t) shows me that it is indeed a test object. However, it seems that when I return the t object as part of the promise, the test is ended.

Its entirely possible that I should not be creating a harness. Should I be creating a subtest?

Additionally, createStream() to tapDiff will cause both tapDiff and tape to output to process.stdout. I'd like to stop Tape from piping to process.stdout.

``` js
function createHarness() {
  return new Promise((res) => {
    const test = tape.createHarness();
    const tapeStream = test.createStream();
    tapeStream.pipe(tapDiff()).pipe(process.stdout);
    tapeStream.pipe(fs.createWriteStream(`${testData.directory}/log.txt`));
    res(test);
  });
}

function createTape(test) {
  return new Promise((res) => {
    const tapeStream = test.createStream();
    tapeStream.pipe(tapDiff()).pipe(process.stdout);
    tapeStream.pipe(fs.createWriteStream(`${testData.directory}/log.txt`));
    test(`Test: ${testData.startTime}`, (t) => {
      console.log(t);
      res(t);
    });
  });
}
```

Async function

``` js
const test = await createHarness();
const t = await createTape(test);
```

Without the harness, passing t along async await works just fine.

``` js
function createTape() {
  return new Promise((res) => {
    // const test = tape.createHarness();
    testData.startMoment = moment().format('MMMM Do YYYY, h:mm:ss a');
    testData.startTime = Date.now();
    tape.only(`Test: ${testData.startTime}`, (t) => {
      res(t);
    });
  });
}
```

**Comment by ljharb** [comment]
@daposy have you figured this out?

**Comment by daposy** [comment]
I'm not the same user who created this ticket. Seems like when I switched GitHub usernames it merged someone else's tickets with mine.

**Comment by ljharb** [comment]
Wow, that seems like something that should be impossible! Thanks for responding.

**Comment by daposy** [comment]
Yeah, I was confused by the extra open issues I was seeing on projects I hadn't touched.
