### ISSUE TITLE
execution order with multiple node_modules/tape installations

### ISSUE THREAD

**Issue by timoxley** [substack/tape#325]
`tape`'s execution order gets confused when multiple `tape` installations exist.

For example, given multiple `tape` installations like this:

```
root
   node_modules/tape
   a/test.js
   a/node_modules/tape
   b/test.js
   b/node_modules/tape
```

The tests in `a` and `b` won't wait for each other to complete, even if they're running in the same node process i.e. the following will run tests in parallel:

```
tape a/test.js b/test.js
```

This is immediately evident by the printing of multiple `TAP version 13` strings when trying to run both tests:

```
> tape a/test.js b/test.js

TAP version 13
# a
TAP version 13
# b
...
```

Here's a an executable example that demonstrates the problem by having some shared global state between the tests:

https://github.com/timoxley/test-tape-multiple-instances

Not sure if it's possible to solve this cleanly, would need a globally accessible flag or interference/monkeypatching of require; both options are pretty gross.

**Comment by timoxley** [comment]
In my case, the nested `tape` installation was an accident, and due to some interaction between concurrently executing tests, things were passing when they shouldn't and I hadn't noticed for a long time.

**Comment by ljharb** [comment]
@timoxley is this a monorepo/multi-package scenario? typically i've seen test scripts that cd into each package and run `npm test` for that. if not, why the nested node_modules?

**Comment by timoxley** [comment]
@ljharb yep, monorepo. Problem with `cd` into each package is that it takes significantly longer because it needs to pay a heavy startup cost many times

**Comment by ljharb** [comment]
Given that each test file is requiring tape, and the node require algorithm is working properly here, I don't really think there's a good solution :-/

Perhaps you could `cd $root/node_modules/tape && npm link && cd $root/$eachProject && npm link tape` as part of your pre-test process?

**Comment by timoxley** [comment]
> I don't really think there's a good solution 

@ljharb agreed, though my concern here is that it's relatively easy to accidentally end up with inaccurate test reporting, in a way that's particularly hard to even notice. I think that's the worst-case scenario for any test runner. Not really tape's fault, unfortunately node's module system doesn't have any simple facility to detect or handle this scenario.

**Comment by ljharb** [comment]
I think it's worth noting though that this is in the unlikely scenario where you've got a monorepo, but you aren't running sub-package tests independently.

**Comment by ljharb** [comment]
This seems answered.
