### ISSUE TITLE
Provide a variable to test script files to determine root dir

### ISSUE THREAD

**Issue by jez9999** [substack/tape#326]
When I'm running a Node program, usually the first thing I do is run my startup code in the root application directory:

```
global.__base = __dirname;
```

That was it is easy for me to include library files from any other code file included because they will have access to __base to get a path to the root application dir.

When passing .tape.js files into tape, tape should expose a similar variable that gives the application access to the full root path of the application (ie. the path that package.json is in), so that the modules can easily require() library files and not have to worry about providing a relative path.

**Comment by ljharb** [comment]
This is a huge antipattern - dynamic requires are a horrible idea, and the `../` in your paths are *correct* and *proper* - if you don't like them, you should extract more things into small modules.

In short, relying on `__dirname` is an antipattern, and creating globals is exponentially more of an antipattern. I strongly encourage you not to do this.

**Comment by jez9999** [comment]
Absolute nonsense.  I will be developing a module to allow me to require stuff relative to my package.json.

**Comment by ljharb** [comment]
There are a number of such modules already available, but in no case is "creating a global" a good idea.

**Comment by ljharb** [comment]
fwiw, making a symlink inside node_modules to your project root called, say, "~", would let you `require('~/path/to/file/in/project')` without any globals "nonsense" or need to change tape or any other dependency.
