### ISSUE TITLE
AVG virus detection?

### ISSUE THREAD

**Issue by neo6238** [substack/tape#327]
Hi,

at the moment the AVG virus scanner seems to detect some JS/Downloader.Agent.54_Q in .\node_modules\tape\index.js.

Probably some false positive detection since nothing changed there recently... Not sure if you can do something about it.

Kind regards,
Philipp

**Comment by ljharb** [comment]
Thanks for letting us know. There's nothing we can do about it indeed.

**Comment by shawninder** [comment]
Is there anything I can do about it on my own machine to stop getting this warning?

**Comment by ljharb** [comment]
Disable or update AVG; add it as an explicit exclusion (i think that's somewhere in settings); contact AVG to let them know of the false positive.
