### ISSUE TITLE
How to use Preloading modules?

### ISSUE THREAD

**Issue by yandongCoder** [substack/tape#331]
I need add underscore in my tape test, I'm using --require arg like "tape -r underscore test/**/*.js", but in my test code, the line "console.log(_)" alrert "is not defined".
I didn't get it, it's seems to be a silly question, but how could I use --require to load underscore?

**Comment by ljharb** [comment]
@yandongCoder `--require` is for requiring things that cause side effects. Requiring underscore has none - if you want to use underscore if your tests, then just like everything else, you need an explicit require statement in each file that uses it.

**Comment by ljharb** [comment]
It is true that `--require` constitutes "preloading" - but it does not (thankfully) allow you to omit the explicit require statements in each file.

**Comment by yandongCoder** [comment]
ok, I kind of understand now, thank you :)
