### ISSUE TITLE
accurate but confusing testing error state messages

### ISSUE THREAD

**Issue by cdaringe** [substack/tape#332]
# problem statement

- errors messages are intuitively confusing

# discussion

```js
const errA = ...
const errB = ...
tape('a', t => { throw errA })
tape('b', t => { throw errB }) 
```

```txt
# a
not ok 1 test exited without ending
  ---
    operator: fail
  ...
not ok 2 test exited without ending
  ---
    operator: fail
  ...

1..2
# tests 2
# pass  0
# fail  2
```

OK, so what's wrong here? 

- test `b` was never started.  although`test exited without ending` may be correct from a machine perspective, from a user perspective, it would more correctly read `test exited without **starting**`.  i don't think this language is part of the [tap spec](https://testanything.org/tap-specification.html), so it may be worth consideration?

**Comment by cdaringe** [comment]
this was problematic because I was under the impression that the test had been started, when in fact, it never hard

**Comment by ljharb** [comment]
The test is started (ie, queued) when `tape` invokes, not when your callback invokes.

**Comment by cdaringe** [comment]
i agree. 

consider, which is the test?

- `t => t.equals(fruit(), 'bananas')`, or
- `tape('fruit', t => t.equals(fruit(), 'bananas'))`

most correctly (harness + assertions), the latter.  practically, the former.  it's this subtle ambiguity that leads to my periodic confusion.

all of this isn't really a big deal, per se.  however, the error message naturally makes me think, "oh, i forgot a t.end() or t.plan(...) or something."  well no, i didn't.  it's just that the error messages resemble a symptom of the failure, not the cause, which is detectable in our case.

here's what could have been cool:

```
# a
not ok 1 test errored unexpectedly
  ---
    operator: fail
  ...
not ok 2 test skipped due to upstream test errors
  ---
    operator: fail
  ...

1..2
# tests 2
# pass  0
# fail  2
```

re-open if you think any of my remarks are worthy of further investigation/discussion.  thx!
