### ISSUE TITLE
Question: Why does t.doesNotThrow have three arguments?

### ISSUE THREAD

**Issue by des-des** [substack/tape#334]
I do not understand why `t.doesNotThrow(fn, expected, msg)` has three arguments. It seems like the second argument, `expected`, is actually used as the message: https://github.com/substack/tape/blob/master/lib/test.js#L476.

Why doesn't the function just have the signature `t.doesNotThrow(fn, message)`?

**Comment by ljharb** [comment]
It's an `if` - if you pass an error instance, it checks the type of the error as well.

It's meant to mirror the `assert` API.

**Comment by ljharb** [comment]
@des-des that package is not the core module `assert`, it's something else that nobody can ever actually require in node. You're looking for https://nodejs.org/api/assert.html#assert_assert_doesnotthrow_block_error_message which also explains what the argument is used for. "does not throw a TypeError" is not the same as "does not throw anything at all" - something that throws a RangeError, for example, fails the latter but passes the former.
