### ISSUE TITLE
No line numbers reported when tests fails with Webpack

### ISSUE THREAD

**Issue by ssylvia** [substack/tape#335]
How do I get Tape to report the source of the failed test (`at: ...path/module/module.test.js [line #]`)

I have the following test:

```js
import test from 'tape';

test('Test', (t) => {
  t.test('testFirst', (assert) => {
    assert.equal(
      'testActual',
      'testExpected',
      'Should equal testExpected'
    );

    assert.end();
  });

  t.end();

});

```

and the output looks like:
```
TAP version 13
# Test
# testFirst
not ok 1 Should equal testExpected
---
operator: equal
expected: 'testExpected'
actual:   'testActual'
 ...

1..1
# tests 1
# pass  0
# fail  1
```

**Comment by danmakenoise** [comment]
@ssylvia I think more information is needed here. Where does `webpack` come in with this issue? Are you testing a bundled file, using webpack to transpile your tests, or something else?

**Comment by ssylvia** [comment]
@danmakenoise I'm running a Karma test suite that imports test files that are being served from a webpack dev server to compile the es6 code.

**Comment by ljharb** [comment]
What version of tape? What version of karma?

I'm going to close this, but will be happy to reopen if I can repro it.
