### ISSUE TITLE
Issue running tape in a node/express route

### ISSUE THREAD

**Issue by samueller** [substack/tape#339]
Users submit code in my web app. I want to then run tape tests against their code submission and render back the results:
```javascript
var test = require('tape')

app.get('/example', function(request, response) {
  var failures = []
  test.createStream({ objectMode: true }).on('data', row => {
    failures.push(row)
    console.log('pushed row onto failures')
  })
  test('my failing test', t => {
    t.ok(3 == 4)
    t.end()
  })
  console.log(JSON.stringify(failures))
  response.render(failures)
}
```
The problem is `failures` is still an empty array when logging to the console at the end. How do I get the list of failures to send back to the browser? Also, if I reload the browser a bunch of times I'll get these errors:
```
12:34:49 AM web.1 |  (node:11410) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 test listeners added. Use emitter.setMaxListeners() to increase limit
12:34:49 AM web.1 |  (node:11410) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 result listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by ljharb** [comment]
I believe you need to listen for the stream's "end" event before looking at `failures`

**Comment by ljharb** [comment]
As for the event emitter warnings, I think you need to remove the listeners after each request, if you're adding them on each request.
