### ISSUE TITLE
TypeScript support ? 

### ISSUE THREAD

**Issue by kevincaradant** [substack/tape#340]
Hi

I don't know if tape can support ts directly.  Before I used it with es6 files that I transpiled with babel in es5.  But if it's possible,   I don't want to have in the first step to transpile the ts in js.  I prefer to execute my tests on ts files written in es6.  Is it possible? 

Thank you

**Comment by ljharb** [comment]
No, because node only runs JavaScript. You may be able to use babel-node, but that's just transpiling on the fly.

**Comment by kevincaradant** [comment]
Alright, that makes sense in fact :).
Thank you.
I close this issue by consequency.

**Comment by prashaantt** [comment]
@kevincaradant Have you tried [ts-node](https://github.com/TypeStrong/ts-node)?

**Comment by kevincaradant** [comment]
@prashaantt , finallly I used tsc. Indeed, that should works with ts-node also

**Comment by prashaantt** [comment]
You can choose to either use `tsc` to first compile all your TS sources to plain JS and then run them with `tape`, or use `tape` with `ts-node` directly to compile TS sources on the fly, which is what I think you originally wanted to do.

```
ts-node node_modules/.bin/tape test/**/*.ts
```

**Comment by kevincaradant** [comment]
Ah yes thank you for this idea with ts-node on the fly, seems to be that I want but when I use it I get this error:

![image](https://cloud.githubusercontent.com/assets/6093175/22260109/34d82f72-e268-11e6-80ac-ef067c8a28d9.png)


I think it's a problem between mock-js and ts-node but I'm not sure :/
