### ISSUE TITLE
Stubbing out globals

### ISSUE THREAD

**Issue by bensleveritt** [substack/tape#343]
I hope this is a simple, stupid question, but I have a `fetch` call, and I want to stub it out when I'm running the tests in node. Is there anything I can do? I know I could run it in the browser, but I'm looking for a simple yey/ney on API logic, not 100% accuracy.

**Comment by ljharb** [comment]
You my want to look into https://npmjs.com/node-fetch

**Comment by bensleveritt** [comment]
Actually, I was hoping to avoid making any fetch calls at all. I've been trying to get proxyquire to do this, but I don't seem to be able to bend it to my will. I will try posting there though.

**Comment by ljharb** [comment]
`global.fetch = () => Promise.resolve()`?

**Comment by bensleveritt** [comment]
In the end, I got `proxyquire` working, but it was weird. I needed to define a global, but that's insufficient since the required module doesn't have access to the same global (or something...).

For prosperity's sake, my solution was to do something like this:
```
global.fetch = () => Promise.resolve();

const {
  getSites,
  getSitesURL
} = proxyquire('./api', {
  './fetch': () => Promise.resolve()
});
```
Not sure why I needed both for it to work, but it does, so I'm stopping.
