### ISSUE TITLE
Allow selective running of tests

### ISSUE THREAD

**Issue by willm** [substack/tape#344]
This is more of a feature suggestion rather than a bug. I use the `test.only()` method a lot, but you can only have one "only" test. It would be nice if I could run a subset of cases, maybe by allowing more than one test to be `only()` or adding a new function like `test.include()`?

**Comment by big-kahuna-burger** [comment]
maybe ```tape('some test', {skip: true})``` for selective skipping? It's possible to run with ```node test.js```, so narrow down to file and skip what bothers you.

**Comment by ORESoftware** [comment]
node-able tests, ftw

**Comment by ljharb** [comment]
I'm not sure what this would look like, or how you'd select a subset of cases.

Closing for now, but will reopen if a good suggestion appears.
