### ISSUE TITLE
Throws regexp error

### ISSUE THREAD

**Issue by pito-svk** [substack/tape#346]
I have the following test which throws ValidationError:

```javascript
t.throws(validatePropertyFunc, 
     /{ message: 'email is required', name: 'ValidationError', status: 400 }/, 
     'Error is ValidationError')
```

It should pass, however there are subtle differences, I don't know why it happens and how to solve it.

```
operator: throws
expected: |-
  '/{ message: \'email is required\', name: \'ValidationError\', status: 400 }/'
actual: |-
  { message: 'email is required', name: 'ValidationError', status: 400 }
```

**Comment by ljharb** [comment]
The regex applies to the string version of the error - you're passing a regex that tests against the apparent string value printed out under "actual". Try `/^ValidationError: email is required$/`?

**Comment by pito-svk** [comment]
Thanks, that works.
