### ISSUE TITLE
Request: Ability to pipe into tape.

### ISSUE THREAD

**Issue by chickendinosaur** [substack/tape#349]
Trying to do:

babel test.js | tape | tap-spec

This is so I don't have to do an extra build step to write out a bunch of files each time I run the tests to make development and build script for efficient.

Thank you!

**Comment by substack** [comment]
You can pipe the output of babel directly into node:

```
$ cat cool.js 
import test from 'tape'

test((t) => {
  t.ok('cool')
  t.end()
})
$ babel --presets es2015 cool.js | node
TAP version 13
# (anonymous)
ok 1 should be truthy

1..1
# tests 1
# pass  1

# ok
```

**Comment by chickendinosaur** [comment]
Thanks!
