### ISSUE TITLE
Can I get an lcov report from my test suite?

### ISSUE THREAD

**Issue by mbcooper** [substack/tape#350]
One of the things I like to monitor on a project is the line coverage, which I like to pass to SonarQube to get code coverage reports.

Is there to instrument tape or the stream runner to generate an lcov report?

--mike

**Comment by kgryte** [comment]
See, e.g., [Istanbul](https://github.com/gotwarlost/istanbul).

**Comment by substack** [comment]
```
npm install -g nyc
```

then you can run it like this:

```
$ nyc tape test/*.js
TAP version 13
# oakland
ok 1 sea level
ok 2 300km up in space
ok 3 space distance
ok 4 ground distance
ok 5 underground distance

1..5
# tests 5
# pass  5

# ok

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
 index.js |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|
$ nyc report --reporter=text-lcov
TN:
SF:/home/substack/projects/geodetic-to-ecef/index.js
FN:9,(anonymous_0)
FNF:1
FNH:1
FNDA:5,(anonymous_0)
DA:4,1
DA:5,1
DA:6,1
DA:7,1
DA:9,1
DA:10,5
DA:11,5
DA:12,5
DA:14,5
DA:15,5
DA:17,5
DA:19,5
DA:20,5
DA:21,5
DA:22,5
LF:15
LH:15
BRDA:10,0,0,2
BRDA:10,0,1,3
BRF:2
BRH:2
end_of_record
```

**Comment by cboden** [comment]
I'm not sure where my question belongs, so trying to tack it on here...I'm running `nyc tape 'tests/**/*.js'` as suggested above. Previously, this repository was running just tape on its own for quite a while, having just added nyc today. 

My question/issue is it's being reported `100` for `% Lines` on every file, which is not the case...any idea what I should do?

**Comment by ljharb** [comment]
the nyc repo would be a better place.
