### ISSUE TITLE
tape stops logging when using mock-fs

### ISSUE THREAD

**Issue by nemoxps** [substack/tape#354]
#### test.js
```js
let test = require('tape');
let mock = require('mock-fs');

test('test name', (t) => {
    t.pass('ok1');
    mock({ 'test-file.txt': 'test-file content' });
    t.pass('ok2');
    t.end();
    mock.restore();
});
```

#### `$ node ./test.js`
Prints:
```
TAP version 13
# test name
ok 1 ok1
```

So, anything breaks when using [mock-fs](https://github.com/tschaub/mock-fs).

It works, if `mock.restore()` is called before making any assertion.

Works:
#### test.js
```js
let test = require('tape');
let mock = require('mock-fs');

test('test name', (t) => {
    t.pass('ok1');
    mock({ 'test-file.txt': 'test-file content' });
    mock.restore();
    t.pass('ok2');
    t.end();
});
```
Prints:
```
TAP version 13
# test name
ok 1 ok1
ok 2 ok2

1..2
# tests 2
# pass  2

# ok
```

Works not:
#### test.js
```js
let test = require('tape');
let mock = require('mock-fs');

test('test name', (t) => {
    t.pass('ok1');
    mock({ 'test-file.txt': 'test-file content' });
    t.pass('ok2');
    mock.restore();
    t.pass('ok3');
    t.end();
});
```
Prints:
```
TAP version 13
# test name
ok 1 ok1
```

Any ideas what's going wrong?

**Comment by nemoxps** [comment]
I just tried something, but I've no idea why this is working.
Just added this line:
```js
test.createStream().pipe(process.stdout);
```

**Comment by ljharb** [comment]
My suspicion is that console logs (which is how tape's output shows up), since that's also a file, are getting swallowed up. I'm not familiar with mock-fs, since I usually just use the real filesystem for tests.

**Comment by nemoxps** [comment]
I think, I may have found the problem.
#### tape/index.js
```js
function createExitHarness (conf) {
// ...
var es = stream.pipe(conf.stream || createDefaultStream());
// ...
}
```
#### tape/lib/default_stream.js
```js
var fs = require('fs');
// ...
function flush () {
    if (fs.writeSync && /^win/.test(process.platform)) {
        try { fs.writeSync(1, line + '\n'); }
        catch (e) { stream.emit('error', e) }
    }
    else {
        try { console.log(line) }
        catch (e) { stream.emit('error', e) }
    }
    line = '';
}
```
`fs.writeSync(1, line + '\n');` there it is.

It seems that this is a windows-only issue (`/^win/.test(process.platform)`) - what's the reason for that (a comment in the file would be helpful)?

**Comment by ljharb** [comment]
`fs.writeSync` indeed writes to stdout.

Are you running on Windows?

I'm not sure what's going on, but if `mock-fs` can't handle `fs.writeSync(1, content)`, then it might be a bug in that library.

**Comment by nemoxps** [comment]
Yes, I'm running on Windows.

`mock-fs` overwrites the bindings from `process.binding('fs')`. It doesn't explicitly overwrites `writeSync`, but it does overwrite `write` (including some magic to support sync and non-sync). As far as I can see, `mock-fs`'s `write` doesn't write to stdout.

**Comment by ljharb** [comment]
Seems like it might be worth filing an issue on `mock-fs`?

**Comment by nemoxps** [comment]
I think so, just give me a minute.

**Comment by ljharb** [comment]
Closing in favor of https://github.com/tschaub/mock-fs/issues/201.

Will be happy to reopen if it turns out something needs to change in tape.
