### ISSUE TITLE
Adding comments to make code more understandable and self-explanatory

### ISSUE THREAD

**Issue by abhisheksoni27** [substack/tape#356]
Hey!

Can I work on adding comments to the code? That would make it more understandable, and would help a great deal for someone who's reading the source code from.

I thought I'd run this by you before spending a great deal of time on it.

What do you reckon?

**Comment by ljharb** [comment]
Comments should never explain "what", only "why", or history/motivation. If you think you can add comments like that, that'd be great!

If you find a place where you think a comment explaining "what" would be helpful, it'd be preferred to try to refactor the code instead to make it more readable :-)

**Comment by abhisheksoni27** [comment]
Hey! Thanks for the response. 

I think I can try. With that philosophy in mind, while I do so.
