### ISSUE TITLE
almost method, or asserting floats

### ISSUE THREAD

**Issue by dfcreative** [substack/tape#357]
Difficult to overstate how many times asserting floats is needed, but in some reason there is no `almostEqual` in `assert` nor `tape` modules. There is [almost-equal](https://www.npmjs.com/package/almost-equal) package for that.
Just thinking that it would be handy to have `almost` method in tape, comparing floats.
Thoughts?

I can come up with a PR.

**Comment by ljharb** [comment]
tape mirrors the assert API, and is intentionally not littered with custom matchers. You can already `t.ok(almostEqual(a, b), 'a is almost equal to b')`- I'm not sure what value a custom matcher would provide here.

**Comment by dfcreative** [comment]
@ljharb same value as `t.deepEqual(a, b)` provides over the `t.ok(deepEqual(a, b), 'a is deep equal to b')`.

**Comment by ljharb** [comment]
Except that deepEqual applies to every JS type, not just numbers; and most importantly, assert supports it.

Also, deepEqual is necessary to compare array and object contents and is not trivial to implement yourself.

**Comment by dfcreative** [comment]
Ok. But why is it important for tape to follow (exactly?) the API of assert?

**Comment by ljharb** [comment]
That's what the creator of the project decided.

**Comment by dfcreative** [comment]
@substack you mean?

From readme:

> The assertion methods in tape are heavily influenced or copied from the methods in node-tap.

Looking at node-tap:

> assertion methods are given several synonyms for compatibility with other test runners and the vagaries of human expectations and spelling

Seems that original idea was to let people use test runner with pleasure rather than strictly following `assert` API, it does not look like here backward-compatibility is pursued. Also `tape.deepLooseEqual` is already different from `assert`. Unless I don't know something.

**Comment by ljharb** [comment]
None the less, many other feature requests have been previously rejected due to their absence from assert.

In either case, checking that numbers are "almost equal" is not a common case; a matcher for that is not sufficiently generic (it only makes sense on number types); and there's already a package to check for it that has a pretty complex API around "how almost' (complexity that we wouldn't want in tape).

**Comment by dfcreative** [comment]
Well that can easily be extended to handle float/typed arrays, objects, objects with arrays, etc, I actually done that in [glsl-transpiler](https://github.com/stackgl/glsl-transpiler/blob/master/test/stdlib.js) Should say that it is far from "specific" case, that is actually regular case for any numeric calculations.

**Comment by kgryte** [comment]
@dfcreative the notion of "almost equal" is a matter of some debate. The package you provided as an example (`almost-equal`) uses a generic formula for comparing two floating-point numbers (which is neither conventional nor necessarily suitable for testing when comparing against known/expected values).

Having done a fair amount of testing of numeric algorithms, I would advocate that `almostEqual` is best left to userland, as any formulation needs to be tailored to the particular context being tested. Furthermore, any `almostEqual` would require parameterization which would be contrary to current conventions used by assertion APIs in this package.
