### ISSUE TITLE
Individual test pass, running tape tests/*.js fails

### ISSUE THREAD

**Issue by goliatone** [substack/tape#360]
I have a test directory with 4 different test files. If I run the files individually, each of them will pass, e.g.
```
...
# tests 5
# pass  5

# ok
```

When I run `node_modules/.bin/tape test/*.js` some tests will fail.
```
# tests 51
# pass  42
# fail  9
```

I have run them in two different macOS computers and both have a similar behavior with the exception of one computer is showing some 9 error messages:

>✖ test exited without ending
>   -----------------------------
>     operator: fail
>     at: process.emit (../application/node_modules/source-map-support/source-map->support.js:430:21)

If I run the tests using [bogota](https://www.npmjs.com/package/bogota) they all pass:
>total:     53
>  passing:   53
>  duration:  748ms

macOS Sierra 10.12.1
MacBook Pro Mid 2014
node v6.5.0

**Comment by tuananh** [comment]
i have the same issue.

**Comment by ljharb** [comment]
You have to quote your globbed path, or else the shell will expand it for you.

Try `tape 'test/*.js'`.

**Comment by tuananh** [comment]
@ljharb many thanks. it works

**Comment by ljharb** [comment]
@goliatone does this solve your issue? I don't expect it will; since it looks like you've injected source map support into node, which suggests that's what's causing the bug.

**Comment by ljharb** [comment]
Sure - but this is how all shells work. If you want to pass an argument to a tool without the shell interceding, you have to quote it.
