### ISSUE TITLE
How to test schema/nested object? 

### ISSUE THREAD

**Issue by mjasnikovs** [substack/tape#362]
For my requirements, I need to test JSON schema. I was using mocha and chai before, but it is too buggy.
Can somebody help to explain, how to attach "jsonschema" or any other proper validation library?

**Comment by ljharb** [comment]
```js
var test = require('tape');

test('an object', function (t) {
  var foo = { a: { b: 1 } };
  var bar = { a: { b: 1 } };
  t.deepEqual(foo, bar, 'foo is the same as bar');
  t.end();
});
```

**Comment by mjasnikovs** [comment]
I'm sorry, I did not explain my question correctly. 

```JavaScript
module.exports = {
	title: 'global User',
	type: 'object',
	required: [
		'id',
		'first_name',
		'voice_messages',
		'age',
		'gender',
		'driver_rating',
		'client_rating',
		'photo'
	],
	properties: {
		id: {type: 'number'},
		first_name: {type: ['string', 'null']},
		voice_messages: {type: ['boolean', 'null']},
		age: {type: ['number', 'null']},
		gender: {type: ['string', 'null']},
		driver_rating: {type: ['string', 'null']},
		client_rating: {type: ['string', 'null']},
		photo: imageSchema
	}
}
```
I need to test json schema value types, to test REST API.

**Comment by ljharb** [comment]
If you have your own function that validates the JSON against a jsonschema, then you can do `t.ok(validatesJSONSchema(object, schema))`, for example.

**Comment by yoshuawuyts** [comment]
I quite like using spok for this https://github.com/thlorenz/spok

**Comment by mjasnikovs** [comment]
I took a look at spok, and it too limited. It's is basically limited to a single object.
If anybody requires testing deeply nested objects and arrays. I have made https://github.com/mjasnikovs/tape-schema for such purpose.
