### ISSUE TITLE
Reporter recommendation with error stack support

### ISSUE THREAD

**Issue by thisconnect** [substack/tape#365]
Hi, which reporter would you recommend with tape?

I used to use the `tap-spec` reporter , but it swallows the TypeError stack trace. Unfortunately the newer version `@tap-format/spec` has the same issue. 

Randomly testing some other reporters it seems `faucet` by substack shows the correct error stack. 

Do you have any other pretty reporters recommendation?

#### test
```js
test('promisesomething', (t) => {
  SomePromise() // fails
  .then(result => {
    t.true(result, 'got result')
    t.end()
  })
  .catch(t.end) // catch error see plain tap output below
})
```

#### Plain tap output
```
not ok 9 TypeError: Cannot read property 'trim' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'trim' of undefined]
    stack: |-
      TypeError: Cannot read property 'trim' of undefined
          at minify (/users/user/path/project/minify.js:14:33)
          at module.exports.ast (/users/user/path/project/minify.js:32:10)
          at readFile.then.then.ast (/users/user/path/project/index.js:15:16)
  ...

```

#### with tap-spec 
`node test/index.js | tap-spec` missing information after stack: |-
![screen shot 2017-05-08 at 10 07 38 am](https://cloud.githubusercontent.com/assets/546900/25795567/3a104c9e-33d6-11e7-91cb-a94c2b0fa6f3.png)

**Comment by ljharb** [comment]
I usually pipe through faucet in a tty, and just use plain output everywhere else.
