### ISSUE TITLE
Can't run tape tests more than once

### ISSUE THREAD

**Issue by lastmjs** [substack/tape#366]
I have a method in a JavaScript class that I want to call multiple times to run my tests:

```
runTests() {
  const test = require('tape');

  test('check that the properties are all initialized correctly through plain attributes', (assert) => {
    assert.equal(true, true);
    assert.end();
  });
}
```

The test only runs the first time that I call `runTests`. It seems that on subsequent calls the callback passed into `test` is never called.

**Comment by ljharb** [comment]
I believe test descriptions need to be unique; try adding an autoincrementing integer in the description.

**Comment by lastmjs** [comment]
That isn't working either. Even if that were the case, I think subsequent calls to tests should run, especially if I am requiring the tape object anew each time. It seems like there is some carryover state that is causing issues.

**Comment by ljharb** [comment]
`require` is cached; you can require it a billion times and you'll get the same `===` value.

**Comment by lastmjs** [comment]
Can we allow tape to be reset somehow so that multiple tests can be called?

**Comment by ljharb** [comment]
Usually how I solve this is doing the `test` call in each place, and passing `assert` into my reusable function, where it calls `assert.test()`

**Comment by lastmjs** [comment]
This seems like a more fundamental issue to the library that should be addressed. I can only ever do one suite of tests, even if those tests are different. I'm trying to create a GUI for a test runner that is interactive, and so I need to run tests multiple times potentially, and turn some tests on and off, all with the same tape instance.

**Comment by ljharb** [comment]
it seems like you might want to run each tape run in a separate process.

**Comment by lastmjs** [comment]
I'm solving this by invalidating the require cache, I wish tape would allow resetting its state somehow so that we could programmatically run through tests more than once. I think this should be addressed.

**Comment by ljharb** [comment]
I'd be happy to review a PR that made it possible, but I can't promise it'd be a feature we'd add.

Many things are stateful via the require cache; invalidating that cache and/or using separate processes are the established means of solving this.

**Comment by lastmjs** [comment]
Looks like this might help me achieve what I'm looking for, I might look into it: https://github.com/substack/tape#var-htest--testcreateharness

**Comment by t3hmrman** [comment]
Hey all, 

I recently hacked a solution to this for my own needs (I'm actually writing E2E tests with `chromedriver`, `tape` and `webdriverio`) and though I should come here and ask just how bad this hack is (and if there's a way to get closer to a proper way to implement retries with `tape`), found this issue so I figured I might as well post here:


```js
const tapeWithRetry = retryCount => {
  var newHarness = tape.createHarness();

  return function() {

    var t = new newHarness(...arguments);
    var originalEnd = t._end;
    var currentRetry = retryCount;

    // Track the actual finish                                                                                                                                                                                                                                                
    var actualFinish;
    var actualResult = new Promise(resolve => actualFinish = resolve);

    tape(arguments[0], arguments[1], realTest => {
      newHarness.createStream().pipe(process.stdout);
      actualResult.then(function() { realTest.end(...arguments); });
    });

    t.end = err => {
      if (err && retryCount-- > 0) {
        // If there was a failure, retry.                                                                                                                                                                                                                                     
        console.log("Error encountered retrying...");
        t.run();
      } else {
        actualFinish(err);
      }
    };

    t.run(); // run the original test                                                                                                                                                                                                                                         
  };
};

const DEFAULT_RETRY_COUNT = 3;
exports.testWithRetry = tapeWithRetry(DEFAULT_RETRY_COUNT);
```

It's pretty messy, but as you can see it takes in the original `tape` function, and produces a `tapeWithRetry`, without harming the other tests. The use of a `Promise` is pretty hacky -- I tried to emit/capture the events that tape was using after taking a look at `test.js` but it didn't really work out so I regressed to just using a promise.

If this code is anywhere near Good Enough ™️ , I can make a little NPM package for this and release it.

**Comment by t3hmrman** [comment]
NVM I actually solved my problem just by doing more to make sure the tests are less flaky.

**Comment by ORESoftware** [comment]
nvm as in nevermind, not node version manager :)

**Comment by ljharb** [comment]
I don't think this makes sense to add to tape; if requiring a module has side effects (which 99% of the time, it shouldn't) then to test those, you'll have to manually clear the require cache before and/or after your test.
