### ISSUE TITLE
how to test if event listeners are fired

### ISSUE THREAD

**Issue by codeofsumit** [substack/tape#368]
I'm currently trying to test leaflet events.

```
map.on('pm:remove', (e) => {
    t.equal(e.layer, polygon, 'pm:remove event fired');
});
map.removeLayer(polygon);
```
the last line will fire an event on the `map` object.

However, it's never called and I get the `plan != count` error.

How to I properly test if event listeners are fired?

**Comment by ljharb** [comment]
From your example, your claim that`removeLayer` actually triggers a `pm:remove` event on `map` such that that callback is called, seems to be contradicted by "it's never called".

Can you share a bit of the code?

**Comment by codeofsumit** [comment]
Sorry for being misleading.
I meant, the `t.equal` is never called but yes, `pm:remove` is fired when `removeLayer` is called.

By your answer I'm assuming I did it correctly (in theory)?

I changed the event to [leaflets own `layerremove`](http://leafletjs.com/reference-1.0.3.html#map-layerremove) to make sure it's not a mistake in my code.

Here's the complete test file:

```
const test = require('tape');
const L = require('leaflet');

test('EVENTS', (t) => {
    t.plan(1);
    const mapContainer = document.createElement('DIV');
    document.body.appendChild(mapContainer);
    const map = L.map(mapContainer);

    const polyLatlngs = [[-111.03, 41], [-111.04, 45], [-104.05, 45], [-104.05, 41]];
    const polygon = L.polygon(polyLatlngs).addTo(map);

    map.on('layerremove', (e) => {
        t.equal(e.layer, polygon, 'layerremove event fired');
    });

    map.removeLayer(polygon);
});
```

The "error" here, as I removed `t.end()` now is constant waiting for the planned assertion.

**Comment by ljharb** [comment]
OK so, first of all, the `t.end()` call would have *had* to go after `t.equal`, inside the event handler callback - if you put it there, and you still get the test waiting, then objectively, the `layerremove` event callback is never getting fired.

That suggests it's either a bug in leaflet, or "layerremove" is the wrong event name, or `removeLayer` isn't supposed to emit the "layerremove" event.

**Comment by codeofsumit** [comment]
hmm ok - that means my code should work in theory. The events are definitely called but the problem is in my code then. Thanks! I know where to search for the mistake now :-)
