### ISSUE TITLE
tap-nyc a code coverage compatible TAP formatter

### ISSUE THREAD

**Issue by MegaArman** [substack/tape#371]
Hey everyone, so I made this output formatter today because I couldn't find one that played nicely with the nyc code coverage module. I used tap-spec as a basis and improved upon it in a couple of ways for example: removed unneeded dependencies and .gitignore'd tests to reduce module size, cleaned code overall (removed unneeded variables/require statements), only output on test failures, and removed excess new lines. It's my first npm module =D

Check it out! @substack , if you like it please include it on the readme <3. Tape rocks.

https://github.com/MegaArman/tap-nyc
https://www.npmjs.com/package/tap-nyc

**Comment by snuggs** [comment]
Nice work @MegaArman. Just started using tap-nyc today in a PR. https://github.com/devpunks/snuggsi/pull/72
![capture d ecran 2017-06-27 a 18 06 17](https://user-images.githubusercontent.com/38223/27612186-5c21491e-5b63-11e7-94d5-d82ae9b50272.png)

**Comment by ljharb** [comment]
a PR to add this to the readme would be welcome.
