### ISSUE TITLE
Getting a list of failing/passing tests after test suite execution

### ISSUE THREAD

**Issue by jwasinger** [substack/tape#378]
I have thousands of test cases.  It would be useful to be able to get a list of passing/failing tests after the suite is run in order to build a concise diff of test output between software versions.

Is there a way to do this?

**Comment by ljharb** [comment]
The test output is TAP, which is machine-readable. Is that not sufficient to get a list of every failing test case?

For example, try piping the output through npmjs.com/faucet for an example reporter you could build.

**Comment by jwasinger** [comment]
okay that seems reasonable.  Thanks!
