### ISSUE TITLE
Using t.comment(null) throws an error (why?)

### ISSUE THREAD

**Issue by markkemper1** [substack/tape#380]
Just spend way too long debugging a test to find out that `t.comment(thingThatIsNull)` will throw an error if `thingThatIsNull` is null

I assumed that this would behave in a similar way to console.log(thingThatIsNull) got burnt :fire:

Could we just treat `null` & `undefined` like empty string?

**Comment by ljharb** [comment]
I'm confused why you'd expect `t.comment` to take anything other than a string.

I'd expect it to throw for *any* non-string value, and I consider it a bug that it doesn't.

**Comment by markkemper1** [comment]
I am expecting it to behave like console.log() 

Maybe I've got the wrong idea about what this method is for?

**Comment by ljharb** [comment]
Yes, I think so - `console.log` is for runtime inspection, `t.comment` is for a text annotation of your test.

**Comment by markkemper1** [comment]
Hi @ljharb 

I was confused by this documentation (see below) and also having issues with seeing the console.log messages in the output of my tests (when using a tap-spec reporting tool).  

```
t.comment(message)

Print a message without breaking the tap output. (Useful when using e.g. tap-colorize where output is buffered & console.log will print in incorrect order vis-a-vis tap output.)
```

**Comment by ljharb** [comment]
gotcha. `console.log` passes its arguments through `util.format` before printing them; tape doesn't.
