### ISSUE TITLE
Plugin, extension to write tests without a need for end()

### ISSUE THREAD

**Issue by hendrics** [substack/tape#382]
Does anyone know if there is a tape extension, plugin to write tests without requiring end() or plan()? Most of my tests will synchronous so adding extra t.end() just to mark the test end seems overkill and just another excuse for people who are not so keen on testing... I understand it seems to be a key feature of tape/node tap, so I don't expect the library to provide such ability...

**Comment by ljharb** [comment]
The explicit `end` or `plan` makes sure that your test isn't ending early; if i stick a `return;` in the first line of your test, and `end` is implicit, then your test would wrongly pass. Currently, it'll fail, because only explicit dev action can end a test - which is a superior approach.

**Comment by hendrics** [comment]
@ljharb thank you for your answer.

I understand why you need plan when dealing with async tests and it is a nice way to deal with it. But I am little surprise if `t.end()` is a fail safe against a developer sticking return in the test. I am been writing and reviewing tests for quiet a few year now in different languages (c++, Python, java and now js) and that was never a problem and end of block was seemed to be a simple way to indicate the end of test. I have to admit I've never implemented a testing framework myself, so this perceived simplicity might be a price at writing a framework which has to introduce some magic... I am also hazy on the history: node tap did it first, right? And tape just followed the API? Also for a new comer to the framework it is a bit unclear that you need to do it if I am honest.

I am just wondering if there is a downstream extension which makes the t.end() optional? Unless I am really missing some vital piece which makes the whole paradigm to collapse without it...

**Comment by ljharb** [comment]
It's a fail-safe against all sorts of unknown things; explicit > implicit.

You could certainly make a function like:
```js
function autoEnd(testFn) {
  return (t) => {
    testFn(t);
    t.end();
  };
}

t.test(autoEnd((t) => {
  // blah
}));
```

**Comment by hendrics** [comment]
I see. Thank you for the idea.

**Comment by markanderstam** [comment]
[purple-tape](https://github.com/mattiash/purple-tape) does exactly this.
