### ISSUE TITLE
Failed assertions inside anonymous functions get incorrect line numbers

### ISSUE THREAD

**Issue by fongandrew** [substack/tape#386]
Consider the following two tests:

```js
test('test 1', t => {
  (function namedFn() {
    t.fail('1'); // Error reported here
  })();
  t.end();
});
```

```js
test('test 2', t => {
  (() => {
    t.fail('2');
  })(); // Error reported here
  t.end();
});
```

On Node v6.11.2, Tape correctly reports that the first test failed at the line with `t.fail('1')`. It incorrect reports that the second test failed at the point where the anonymous function was executed.

The problem appears Issue appears to stem from this code here: https://github.com/substack/tape/blob/5565ef5c965dbd113408b79b30cb0329368e3127/lib/test.js#L221-L253

Basically, what's happening is that Tape is iterating through each line in an error stack trace, using regexes to find and parse the first line that doesn't originate from within Tape's own directory for use as the origin of the error. The problem is that the regex doesn't account for how a stack trace might look for anonymous functions (or more accurately, functions with undefined names).

That is, with the first example above, the relevant stack trace looks like this:

```
Error: exception
    ...
    at namedFn (/Users/username/project/src/test-file.js:5:7)
    at Test.<anonymous> (/Users/username/project/src/test-file.js:6:5)
    ...
```

The stack trace for the second example though looks like this:

```
Error: exception
    ...
    at /Users/username/project/src/test-file.js:12:7
    at Test.<anonymous> (/Users/username/project/src/test-file.js:13:5)
    ...
```

In the first case, the regex picks on the `namedFn` line. In the second case, the regex can't make sense of the line with no function name and so drops down to the `Test.<anonymous>` line to use instead. Note that although the `Test.<anonymous>` function is indeed anonymous, it still has a name by virtue of being set as a property of a `Test` object -- not so for the anonymous function defined in my second example though, so it shows up without any name in the stack trace.

Context: This happened to me because I was trying to wrap the `test` function to automatically do  some setup and teardown for each test called with the wrapper function.  In case this bites anyone else, workaround for my issue was pretty simple -- just use `Object.definePropery(callback, 'name', { value: 'some-name' })` to give a name to the test callback function inside the wrapper.

**Comment by ljharb** [comment]
Thanks, this definitely needs to be fixed in the regex.

That said, in a world with modules, an IIFE should never be necessary, and I'm confident there's a better way to do what you're hoping to achieve - but thanks for reporting this bug!

**Comment by fongandrew** [comment]
Thanks. Just to be clear, it's not just IIFEs. Here's a more representative error case.

```js
const setup = () => {
  // Do some setup
};

const teardown = () => {
  // Do some teardown
};

const test = (name, tc) => tape(name, t => {
  setup();
  tc(t); // Fails here
  teardown();
});

test('test 1', (t: any) => {
  t.fail('1'); // Instead of here
  t.end();
});
```
