### ISSUE TITLE
Argument list too long - tape errors if there are 10,000 test files

### ISSUE THREAD

**Issue by eddyerburgh** [substack/tape#389]
Running tape when there are 10,000 test files causes it to exit with the following error:

```
/../node_modules/.bin/tape: Argument list too long
```
I've made a reproducible example in this repo - https://github.com/eddyerburgh/tape-test-error-repo

Steps to reproduce: clone repo, `yarn install`, `yarn test`

I originally ran into this problem when I was [stress testing different frameworks for testing Vue components](https://github.com/eddyerburgh/vue-unit-test-perf-comparison)

**Comment by willvincent** [comment]
This is actually _not_ a tape issue, but rather a shell limitation.

Try it yourself, after observing it fail with the argument list too long error, try again running the tests directly:
`node_modules/.bin/tape -r babel-register *.spec.js`

You should (eventually) see successful output:
```
1..10001
# tests 10001
# pass  10001

# ok
```

I sent a PR to your [linked repo](https://github.com/eddyerburgh/tape-test-error-repo) to avoid that issue.
