### ISSUE TITLE
use mocha run tape test cant work

### ISSUE THREAD

**Issue by muzidx** [substack/tape#393]
hi, I have a problem running the test, I use mocha to run spec.tape.js, but it cant work

node 7.7.2
npm 4.1.2

tape test code:  use npm example
```
var test = require('tape');
 
test('timing test', function (t) {
    t.plan(2);
    
    t.equal(typeof Date.now, 'function');
    var start = Date.now();
    
    setTimeout(function () {
        t.equal(Date.now() - start, 100);
    }, 100);
});
```

project catalog:

```
├── __tests__
     ├── spec.jest.js
     ├── spec.mocha.js
     └── spec.tape.js
├── mocha.opts
├── node_modules
├── package.json
```

package.json
```
...

"devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-jest": "^21.0.2",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-regenerator": "^6.26.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-es2015": "^6.24.1",
    "jest": "^21.1.0",
    "mocha": "^2.5.3",
    "regenerator-runtime": "^0.11.0",
    "tap-spec": "^4.1.1",
    "tape": "^4.8.0",
    "webpack": "^3.6.0"
  },
  "dependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "chai": "^4.1.2"
  },
  "scripts": {
    "jest": "NODE_PATH=./ jest",
    "tape": "NODE_PATH=./ mocha --opts ./mocha.opts __tests__/**.tape.js",
    "mocha": "NODE_ENV=test NODE_PATH=./ mocha --opts ./mocha.opts __tests__/**.mocha.js"
  }
...
```

mocha.opts

```
--debug
--compilers js:babel-core/register
--recursive
--colors
--timeout 60000

```

`npm run jest / mocha` no problem, can run the test, but `npm run tape` cant work ?
```
➜  project-name    npm run tape

> compare-the-test-frameworks@1.0.0 tape /Users/muzidx/Desktop/compare-the-test-frameworks
> NODE_ENV=test NODE_PATH=./ mocha --opts ./__tests__/mocha.opts __tests__/**.tape.js --compilers js:babel-core/register

(node:68080) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
Debugger listening on 127.0.0.1:5858


  0 passing (1ms)
```

and have npm error 
```
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

The same problem arises through cli execution, test not work;

But, use node to execute no problem, work it. So, run tape cant use mocha？or my project config is bad? 

node to run is my expect, it's:
```
➜  project name   node __tests__/spec.tape.js
TAP version 13
# timing test
ok 1 should be equal
not ok 2 should be equal
  ---
    operator: equal
    expected: 100
    actual:   105
    ...... 

1..3
# tests 3
# pass  1
# fail  2
```

**Comment by ljharb** [comment]
Mocha is a test runner that requires you author your tests in mocha's style; tape tests must be run with `node` or `tape` only.

Why are you trying to run non-mocha tests with `mocha`?

**Comment by muzidx** [comment]
@ljharb hi, thanks. I use mocha to run tape test, because a project about react+redux, before using mocha chai to test action and reducer func, with the development of the project, I gradually want to use redux-saga replace redux-thunk processing async operation, I find redux-saga official example of the use tape to test. So, I selected tape to test saga func compared to chai I prefer like tape. A module included two tests, mocha and tape, but use mocha to run , like this 
```
package.json
{
"scripts": {
     "test": "NODE_ENV=test NODE_PATH=./ mocha --opts ./mocha.opts 
                 ./__tests__/**/**.spec.js | tap-spec"
}

...
}
```
test can be run, no problem. 

Recently, I want to compared to mocha, jest, tape similarities and differences, so create a new project, as above describe code, but I have trouble when use mocha run tape test.

Want to know whether the problem is? tape does not match mocha‘style?

**Comment by ljharb** [comment]
If you want to use tape, you can't use mocha - I'm not sure how else to specify it.

mocha and jest can *sometimes* run the same tests, but often they can't - it depends how they're written. Neither can ever run tape tests.

When you change test style, you usually have to change runners too.
