### ISSUE TITLE
Provide API to get name of currently running test

### ISSUE THREAD

**Issue by keithkml** [substack/tape#401]
I'm using Tape for web browser UI automation tests. I'd like each test to store a screen shot whose filename matches the name of the test, like `clicking submit should work.png` – but Tape does not provide an API for getting the test name at all.

I worked around this by abusing `createStream`, but it broke TAP output:

```js
let currentTestName;
test.createStream({objectMode: true}).on('data', function(row) {
  if (row.type === 'test') {
    currentTestName = row.name;
  }
});
```

**Comment by nhamer** [comment]
It's not an exposed API, but it's in t.name

**Comment by keithkml** [comment]
Oh neat. Unfortunately that doesn't help me because I don't have access to `t` from the helper function.

**Comment by isnifer** [comment]
@keithkml 
```js
// your-tape-wrapper.js

import test from 'tape-async'

export default function tape(name, callback) {
  return test(name, async (t) => {
    await callback(t)
  })
}
```

**Comment by ljharb** [comment]
This seems answered.
