### ISSUE TITLE
Allow Setting opts.objectPrintDepth Globally

### ISSUE THREAD

**Issue by inadarei** [substack/tape#418]
Currently `opts.objectPrintDepth` can be set by passing an `opts` object to a t() function. However, if we need to change the setting across many (or all) tests - things can get messy.

### Solution:

Let Tape pay attention to an environmental variable `NODE_TAPE_OBJECT_PRINT_DEPTH`, which if set will override any local settings.

**Comment by inadarei** [comment]
Corresponding PR: #420

**Comment by andrewharvey** [comment]
@inadarei I believe you can close this issue now that your PR was merged :pray:
