### ISSUE TITLE
Test error type and properties

### ISSUE THREAD

**Issue by tjconcept** [substack/tape#426]
I often throw errors of a specific type and with additional properties, however, it is slightly inconvenient to test:

```js
let caught
try { fn() } catch (e) { caught = e }
t.ok(caught instanceof SpecificError)
t.deepEqual(caught, {message: '..', username: '..'})
```

Ideally I want something like:

```js
t.throws(fn, SpecificError, {message: '..', username: '..'})
```

Is there an existing, better, solution to this?
Is this a unique use case?
Would a PR for this functionality be considered?
Should it have its own operator such as `throwsDeepEqual`?

**Comment by tjconcept** [comment]
An annoyance I run into once in a while with the current API is that `t.throws(fn, SomeError)` will `OK` if `SomeError` is `undefined`. I fear that it is impossible to fix with the current API design, but just wanted to put it here as well.

**Comment by ljharb** [comment]
`t.throws` can accept a regex, so in your case, you could do something like ``` t.throws(fn, new RegExp(`^SpecificError: ${message}$`); ``` etc?

**Comment by tjconcept** [comment]
If I put the error name in the message then, yes, and the same "solution" would work for other properties (putting them in the message somehow).
I'd really much like to test the actual properties though so I can document them.
The instance can't be checked with a regex.

**Comment by ljharb** [comment]
Turns out this is something node itself supports now; see also #179.

**Comment by ljharb** [comment]
#179 is now resolved; tape v5 will support passing in an object of properties/regexes, as well as a validation function where you can run your own custom validations.
