### ISSUE TITLE
Issue ignoring node_modules using tape binary

### ISSUE THREAD

**Issue by danielgormly** [substack/tape#427]
**Node version:** 6.10.3 (I am writing an AWS Lambda function)
**OS:** Mac OS X 10.13.3 

The behaviour I desire is for tape to run through my project directory recursively and find all files with the suffix `.spec.js` and process these files.

`tape *.spec.js`: Selects files in the project root only.
`tape **/*.spec.js`: Selects files in subfolders only (not in the project root).
`tape {**/*,*}.spec.js` is the command I am using. (Is there a better glob pattern to use?)

Unfortunately the latter 2 of these commands also searches through node_modules too. In the case of the project I am working on, there is a module using this same convention `*.spec.js` and it attempts to run this too, only to find an undefined `describe` keyword (because this module obvs uses a diff test framework).

I'd like to submit a PR to tape to use glob's "ignore" option to optionally ignore the `node_modules` directory. Alternatively, is there another way around this I am not seeing?

Thanks!

**Comment by ljharb** [comment]
Instead, put the path in quotes - that way your shell won't preemptively interpret the `**`.

**Comment by danielgormly** [comment]
Thanks! I ended up solving this issue with a combination of quotes as you suggested and my original solution but negating the node_modules dir:

`tape '{,!(node_modules)/**/}*.spec.js' | tap-spec`

**Comment by ljharb** [comment]
Are your node_modules gitignored?

**Comment by danielgormly** [comment]
Yep!

**Comment by ljharb** [comment]
Hm, I’d expect `tape` to respect gitignore; you shouldn’t need to explicitly exclude node_modules. Are you sure that with the path in quotes, that’s needed?

**Comment by danielgormly** [comment]
Yeah this is the case on Node 8.9.4 and 6.10.3, both on OS X.

Output of `"test": "tape '**/*.spec.js'"`:
```
/path/to/project/node_modules/fast-deep-equal/spec/index.spec.js:8
describe('equal', function() {
^
ReferenceError: describe is not defined
    at Object.<anonymous> (/path/to/project/node_modules/fast-deep-equal/spec/index.spec.js:8:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /path/to/project/node_modules/tape/bin/tape:38:9
    at Array.forEach (native)
```

**Comment by ljharb** [comment]
ah, i see, you're colocating tests - that's an uncommon and recent enough practice that we probably haven't gotten issues about it before.

If you want to file a new issue for it, I think it'd be a good change to make it respect gitignore by default.

**Comment by danielgormly** [comment]
Ok thanks, I'll do that now
