### ISSUE TITLE
Ability to ignore node_modules or files in .gitignore by default

### ISSUE THREAD

**Issue by danielgormly** [substack/tape#428]
Referencing issue #427, I am working on a project where I'm co-locating tests with their module.

i.e.
```
--/path/to/module.js
--/path/to/module.spec.js
```

I'm currently targeting these spec files with the function `tape '{,!(node_modules)/**/}*.spec.js' | tap-spec`. The glob I've written is somewhat convoluted and slightly difficult to read and it does seem like perhaps the default behaviour for the tape-cli is that it should exclude the `node_modules` directory or respect your `.gitignore` file.

Within the glob module that tape uses, there is an `ignore` option to exclude certain directories and files. If there are legitimate reasons for not excluding node_modules and/or gitignore by default, perhaps this could be achieved behind a flag.

Thoughts?

**Comment by ljharb** [comment]
I think that a good semver-minor change would be to add an option to the `tape` binary that uses gitignore (node_modules should be gitignored anyways), and then in a later semver-major, flip the default.

**Comment by danielgormly** [comment]
Cool I'll go ahead with dotignore

**Comment by ljharb** [comment]
@danielgormly it'd be great if you wanted to submit a PR for this :-)
