### ISSUE TITLE
Do not use node-specific APIs

### ISSUE THREAD

**Issue by lastmjs** [substack/tape#431]
I understand that browserify and webpack exist, but I would like to use Tape in the browser without having to depend on a specific bundler. My own build process automatically compiles CommonJS to ES Modules, and so I can run those libraries directly in the browser without any bundling. The only issue with this library is that there are a few node-specific APIs at play here. I'm wondering if they could be replaced with browser-compatible versions so that everything works seamlessly across all platforms. Stream, path, and events all seem easy to replace. fs would probably be the most difficult, but it looks like it's only used in default_stream.js, could be replaced with an in-memory version potentially. I would be happy to do a PR with the changes.

**Comment by ljharb** [comment]
The nature of modern web dev is that everything comes from npm, and everything requires a build process (a bundler).

The defacto standard for bundlers is that they do what browserify does, which includes reading the "browser" field and also stubbing out node core modules with either polyfills or empty implementations.

I'm not sure what your own build process is using, but if it doesn't have the feature set that the entire ecosystem has come to expect - nay, demand - then I'm not sure what tape could or should do to accomodate it.

**Comment by lastmjs** [comment]
I suppose we disagree here, which is okay. I'll just state it as my opinion that everything can come from npm without requiring node-specific APIs, and not everything requires a build process nor a bundler process, nor should everything require a build process or bundler process.

Thanks for making an awesome library nonetheless

**Comment by ljharb** [comment]
There's virtually nothing that can be consumed from npm that does not require a build process or bundler process; and if something uses node-specific APIs, then it's incompatible with browsers, and it's not reasonable to expect a bundler will allow you to use it there (altho it's possible, as shown by browserify/webpack/etc)

**Comment by lastmjs** [comment]
> There's virtually nothing that can be consumed from npm that does not require a build process or bundler process

I really do not believe that statement is correct. There are many modules that are just plain JavaScript that can be used right away. As I've been looking through the issues, I'm not the only one confused by this library's lack of compatibility with the browser. There is no reason in my opinion that this library should be written using any node-specific APIs. It is supposed to be simple and just run your tests and provide output. Why does `fs` need to be included? Why rely on node-specific streams?

Not everyone uses Browserify or Webpack, that may be what many people use and what you use, but if this library is only usable in the browser with those build systems, perhaps the library documentation should reflect that and not lead the user to believe this library is browser-ready without those extra steps.

Also, Webpack and Browserify are stop-gap solutions in my opinion. What we should be working toward is a world without complicated build-processes. All of this tooling should be built to melt away when the platform can support it, so that the barrier to entry is as low as possible, without sacrificing performance as far as is possible.
