### ISSUE TITLE
How to use createHarness

### ISSUE THREAD

**Issue by lastmjs** [substack/tape#432]
Is the following supposed to work?

```javascript
const tape = require('tape');

const harness = tape.createHarness();

harness('This is a test', (assert) => {
    assert.equal(true, true);
    assert.end();
});
```

I'm running it in node, and creating a new harness and running the test with it produces no output. I've tried some variations of the parameters, and I get nothing. Using tape v4.9.0.

**Comment by lastmjs** [comment]
So if I call `tape()` after the harness is setup, it runs. But how can I get the harness to run more than once within the same execution thread and process? I want to be able to run tests over and over again in response to user input.

**Comment by lastmjs** [comment]
This is related to https://github.com/substack/tape/issues/366, but hopefully I'm just using createHarness incorrectly.

**Comment by anaptfox** [comment]
Hey @lastmjs, I'm trying to attempt something very similar to your use case. Did you ever figure this one out?

**Comment by lastmjs** [comment]
I'm trying to remember...looking at the repo that I was working on, I believe right around the time of my last comment, I decided to get rid of tape in my project. I think I ran into too many unresolved isues with tape, and realized my project just didn't need it. But, here's a hint at how I believe I got around the issue back then: https://github.com/lastmjs/guesswork/blob/v0.5.9/test-runner.ts#L211

**Comment by lastmjs** [comment]
If you're using node, you can essentially re-require the module each time you need to run tests fresh.

**Comment by ljharb** [comment]
The `require` cache is shared across the entire process; the solution to your problem is to clear the require cache if you want to test requiring a file multiple times.

This seems answered.

**Comment by chrisdevereux** [comment]
For anyone else who ended up here, you need to open a stream on the harness for it to start.

this did it for me:

```
tape.createStream().pipe(require('tape/lib/default_stream')())
```
