### ISSUE TITLE
Changing stream output

### ISSUE THREAD

**Issue by shaunmcarmody** [substack/tape#436]
Every example of Tape test failures seems to output to the terminal like this..

        TAP version 13
        # timing test
        ok 1 should be equal
        not ok 2 should be equal
        ---
        operator: equal
        expected: 100
        actual:   107
        ...

        1..2
        # tests 2
        # pass  1
        # fail  1

Whereas my output to the terminal contain the stack & at properties, and excludes the test, pass, fail summary at the end of the output, see below..

        TAP version 13
        # timing test
        ok 1 should be equal
        not ok 2 should be equal
        ---
        operator: equal
        expected: 100
        actual:   107
        at: request.get.expect.expect (server.test.js:12:14)
        stack: |-
           Error: should be equal
             at Test.assert
             at Test.bound
             // etc

How can I change the stream so that my outputs to the terminal exclude the stack & at properties, and include the test, pass, fail summary?

**Comment by ljharb** [comment]
Can I ask why you'd want to omit this information? If the test fails, the stack info helps to debug - and tests sometimes fail spuriously, so it seems like a big loss to discard that information just to hope that it will be there when you're debugging.

**Comment by ivanjonas** [comment]
That makes sense for when you run tests before comitting. But if you're already in the debugging process, you don't need to see the huge stack track over and over. I'm changing code and I want to see which tests are failing. I already know _where_.

**Comment by ljharb** [comment]
Isn't that the concern of a reporter? A custom reporter could format the results however it likes, including suppressing any extra information.

**Comment by planttheidea** [comment]
@ivanjonas 	@ljharb 	I think your discussion on whether the stack trace should or should not exist has distracted from a large problem (which admittedly was listed as an afterthought) ... the fact that the summary output is lost. I'm seeing this behavior with a number of reporters as well.

**Comment by ljharb** [comment]
@planttheidea aha, thanks.

The summary shouldn't be lost with a stream when there's a failure. A PR with a failing test case, and better, also with a fix, would be very appreciated.

**Comment by ivanjonas** [comment]
> 
> 
> Isn't that the concern of a reporter? A custom reporter could format the results however it likes, including suppressing any extra information.

You're absolutely right. This is one of those times when you come back to an issue and can't believe you have so easily come around to disagree with your opinion from only two months ago.
