### ISSUE TITLE
Do we really need `string.prototype.trim`?

### ISSUE THREAD

**Issue by shelacek** [substack/tape#444]
Package `string.prototype.trim` adds some not negligible cost into `node_modules`. According to http://npm.anvaka.com/#/view/2d/tape it is 8 packages:

- `define-properties`
- `es-abstract`
- `es-to-primitive`
- `is-date-object`
- `is-regex`
- `is-symbol`
- `object-keys`
- `string.prototype.trim`

which made up ~30% of the total size of `node_modules`:

```sh
$ du -bh --max-depth=1 node_modules/
27K     node_modules/is-symbol
7.7K    node_modules/inflight
21K     node_modules/through
19K     node_modules/is-date-object
37K     node_modules/minimatch
7.6K    node_modules/path-is-absolute
15K     node_modules/brace-expansion
36K     node_modules/object-keys
42K     node_modules/minimist
179K    node_modules/tape
18K     node_modules/resumer
45K     node_modules/es-to-primitive
8.0K    node_modules/once
59K     node_modules/glob
18K     node_modules/fs.realpath
25K     node_modules/is-regex
21K     node_modules/for-each
15K     node_modules/has
6.9K    node_modules/wrappy
17K     node_modules/concat-map
13K     node_modules/path-parse
28K     node_modules/string.prototype.trim
11K     node_modules/balanced-match
243K    node_modules/resolve
31K     node_modules/define-properties
7.8K    node_modules/inherits
34K     node_modules/is-callable
48K     node_modules/object-inspect
26K     node_modules/deep-equal
33K     node_modules/function-bind
17K     node_modules/defined
4.1K    node_modules/.bin
183K    node_modules/es-abstract
1.3M    node_modules/
```

It is not so important, but it is pretty much for a quite simple one liner, which is used only in one place.

Maybe something like this would be enough:

```js
if (msg == null) throw new TypeError();
forEach(String(msg).split('\n'), function (aMsg) {
    that.emit('result', aMsg.replace(/^\s*#?\s*|\s+$/g, ''));
});
```

**Comment by ljharb** [comment]
The size of node_modules is irrelevant; more deps is better; this is a test framework so bundle size is irrelevant; I’m not sure what benefit there would be from inlining it.

**Comment by shelacek** [comment]
Of course you are right. I don't have a problem with it. But I tend keep a look to my `node_modules`, because every dependency multiplies disproportionately. One of the reason I love about the **tape** is that it is relatively small compared to others.

http://www.youtube.com/watch?v=M3BM9TB-8yA&t=12m37s

**Comment by ljharb** [comment]
That talk is ridiculous - every complaint are part of the very reasons node is successful and widely used.

Thanks for filing the issue - it’s always a reasonable question to ask - but having deps is a good thing, and disk space is infinite and free, while cognitive overhead and complexity is expensive.

I’m going to close this, but we can keep discussing if you like!

**Comment by shelacek** [comment]
I'm not sure, that have deps on everything is good thing, but that's my opinion. Thank's @ljharb for your great work on this project, I appreciate it.

**Comment by ORESoftware** [comment]
mmmm disk space is not infinite, and the fewer deps the better, but OK :)

**Comment by Raynos** [comment]
I really enjoy tape and contribute to it.

I recently published `@pre-bundled/tape` for version `5.0.0`

It contains just under 1500 javascript files.

```sh
$ npm pack @pre-bundled/tape@5.0.0
npm http fetch GET 200 https://registry.npmjs.org/@pre-bundled%2ftape 1056ms
npm http fetch GET 200 https://registry.npmjs.org/@pre-bundled%2ftape 11ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/@pre-bundled/tape/-/tape-5.0.0.tgz 7ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/@pre-bundled/tape/-/tape-5.0.0.tgz 65ms (from cache)
npm notice 
npm notice 📦  @pre-bundled/tape@5.0.0
npm notice === Tarball Contents === 
 .... [ 1500 files snip]
 .... [ 1500 files snip]
 .... [ 1500 files snip]
npm notice XB  .... [ 1500 files snip ] ...
 .... [ 1500 files snip]
 .... [ 1500 files snip]
 .... [ 1500 files snip]
npm notice === Tarball Details === 
npm notice name:          @pre-bundled/tape                       
npm notice version:       5.0.0                                   
npm notice filename:      pre-bundled-tape-5.0.0.tgz              
npm notice package size:  382.7 kB                                
npm notice unpacked size: 2.2 MB                                  
npm notice shasum:        9d49252b2852ddc0ef56ed510877d8e90c63a129
npm notice integrity:     sha512-3bYif0qUXO0OL[...]RYxAh7JOMHhuA==
npm notice total files:   1494                                    
npm notice 
pre-bundled-tape-5.0.0.tgz
```

https://gist.github.com/Raynos/73420a585a481eedadd9aafe69597940

Modules are great ; dependencies are great.

But at the moment that means downloading ~1500 files to use the `tape` library.

The tape library itself is only 4 files.

The version of tape from 2018 ( v4.9.1) had ~1250 files
The version of tape from 2016 ( v3.6.1 ) had ~170 files

**Comment by ljharb** [comment]
File count is as meaningless as line count; it’s under an abstraction layer. node_modules is a black box.

**Comment by dev-dmtrllv** [comment]
Give me one good reason why more dependencies is a good thing...
I understand that deps are needed sometimes but don't use deps that fix thing you can do yourself

**Comment by ljharb** [comment]
@dev-dmtrllv because a separate, thoroughly tested package will almost always be better than code you write yourself - and in the rare cases where it's not, you should either publish or improve one.

**Comment by dev-dmtrllv** [comment]
@ljharb So you think it's a good idea to include a dependecy (string.prototype.trim) for one of the most basic tasks that needs to include a lot of other dependencies? I agree that some dependencies are better tested than something you write yourself but it's all about knowing your limits. If you think the task is too complicated or if you think you would have bugs then go with a dependency. But for something simple as this I think its useless.

> "and disk space is infinite and free"

Btw my disk is not infinite and free?? This sounds to me like a big joke.

I'm not attacking anyone. Just currious about the ideology behind this quote.

**Comment by NowDev** [comment]
> but having deps is a good thing, and disk space is infinite and free
lmao, good luck with that
