### ISSUE TITLE
Reduce the size of the npm package by limiting the included files

### ISSUE THREAD

**Issue by paazmaya** [substack/tape#447]
Looks like the `files` property (https://docs.npmjs.com/files/package.json#files) is not used in `package.json` to specify the included files, nor is the `.npmignore` file (https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) is being used for blacklisting unwanted files, for the package published to npm.

Would you consider adding either the `files` property or the `.npmignore` file, so that the resulting package file would have smaller size?

The current size can be seen when executing the command `npm pack` (https://docs.npmjs.com/cli/pack).

> This issue was create via [tawata](https://github.com/paazmaya/tawata/)

**Comment by ljharb** [comment]
No. The files property is incredibly dangerous and should never be used; and the size of the installed package is irrelevant.

Please do not spam issues in this fashion.

**Comment by paazmaya** [comment]
How about the utilisation of the network bandwidth?

**Comment by ljharb** [comment]
That’s npm’s problem to solve, not package authors’.

**Comment by paazmaya** [comment]
Sad to hear that.

**Comment by ljharb** [comment]
Regardless, automating the filing of issues does not help things not does it prime maintainers to welcome your suggestions.
