### ISSUE TITLE
“test exited without ending” error with asynchronous forEach loops

### ISSUE THREAD

**Issue by Mindcraft1** [substack/tape#448]
Tape version: 4.9.1
Node version: 8.11.3

The code below is a simplified version of the code please see the real world issue [here](https://stackoverflow.com/questions/53222787/tape-test-exited-without-ending-error-with-asynchronous-foreach-loops/53237773?noredirect=1#comment93403077_53237773).

I also created a small simplified repo reproducing the issue [here](https://github.com/Mindcraft1/SO-Tape-test-exited-without-ending-error-with-asynchronous-forEach-loops).

## What I'm doing

I'm trying to set up automated frontend testings with [browserstack][1], [selenium-webdriver][2] and tape.

The idea is to define multiple browsers and devices which have to be tested one after another with X amount of given tests. In the example below I define only one test and two browsers on OSX.

In order to define the browsers only once and handle tests I created a repo `test-runner` which should be added as `dev-dependency` to the repos which need to be tested on the given devices and browsers.
The `test-runner` gets all needed tests passed, starts the first browser, runs the tests on that browser and once all tests are done the browser is closed `quit()` and the next browser gets started and tests again.

**test-runner**

*/index.js*

```
// ---
// default browser configs
// ---
const defaults = {
  "os" : "OS X",
  "os_version" : "Mojave",
  "resolution" : "1024x768",
  "browserstack.user" : "username",
  "browserstack.key" : "key",
  "browserstack.console": "errors",
  "browserstack.local" : "true",
  "build": "test",
  "project": "test"
}

// ---
// browsers to test
// ---
const browsers = [
  {
    "browserName" : "Chrome",
    "browser_version" : "41.0"
  },
  {
    "browserName" : "Safari",
    "browser_version" : "10.0",
    "os_version" : "Sierra"
  }
]

module.exports = ( tests ) => {

  // ---
  // Asynchronous forEach loop
  // helper function
  // ---
  async function asyncForEach(array, callback) {
    for (let index = 0; index < array.length; index++) {
      await callback(array[index], index, array)
    }
  }

  // ---
  // runner
  // ---
  const run = async () => {

    // ---
    // Iterate through all browsers and run the tests on them
    // ---
    await asyncForEach( browsers, async ( b ) => {

      // ---
      // Merge default configs with current browser
      // ---
      const capabilities = Object.assign( {}, defaults, b )

      // ---
      // Start and connect to remote browser
      // ---
      console.log( '-- Simulate browser start -- ', capabilities.browserName )
      const browser = await new Promise( resolve => setTimeout( resolve, 3000 ) )

      // navigate to url in real world now

      // ---
      // Run the tests asynchronously
      // ---
      console.log( '-- Run tests --- ' )
      await asyncForEach( tests, async ( test ) => {
        await test( capabilities )
      } )

      // Stop browser in real world now and go to next one
      // This should only be logged when the all tests for this browser are finished
      console.log('quit: ', capabilities.browserName)


    } )

  }

  // ---
  // Start the tests
  // ---
  run()

}
```

If you're wondering how this `asyncForEach` function works I got it from [here][5].

**my-repo**

*/tests/index.js*

```
// testRunner is a dev-dependency in real world
const testRunner = require( '../../test-runner' )

// tests to run
// Could be more than one
const tests = [
  require('./test.js')
]

testRunner( tests )
```

*/tests/test.js*

```
const tape = require( 'tape' )

module.exports = async ( capabilities ) => {

  return new Promise( resolve => {

    tape( `Frontend test ${capabilities.browserName} ${capabilities.browser_version}`, async ( t ) => {

      // simulate body handling
      const body = await new Promise( resolve => setTimeout( resolve, 3000 ) )

      // Dummy ok
      t.ok(true, 'Button marked')

      //---
      // Test should end now
      //---
      t.end()

      resolve()

    } )

  })

}
```

*/package.json*

```
{
   ...
   "scripts": {
      "test": "node my-repo/tests/ | tap-spec"
   }
   ...
}
```

When I want to run the tests I execute `npm run test`.

Remember, that we have only one test (but could also be multiple tests) and two browsers defined so the behaviour should be:

1. Start browser 1 and navigate(Chrome)
2. One test on browser 1 (Chrome)
3. Close browser 1 (Chrome)
4. Start browser 2 and navigate (Safari)
5. One test on browser 2 (Safari)
6. Close browser 2 (Safari)
7. done

## The Problem
The asynchronous stuff seems to be working just fine, the browsers are started one after another as intended. **The problem is, that the first test does not finish even when i call `t.end()` and I don't get to the second test (fails right after 4.)**.

[![enter image description here][6]][6]

I tried using `t.pass()` and also running the CLI with `NODE_ENV=development tape test/front/ | tap-spec` but it didn't help.
I also noticed, that when I don't `resolve()` in `test.js` the test ends just fine but of course I don't get to the next test then.

I also tried to apply the solution from #160 but did not manage to adapt it to my setup.

Any thoughts how I could get this to work? is it even possible?

[1]: https://www.browserstack.com/automate
  [2]: https://www.npmjs.com/package/selenium-webdriver
  [4]: https://ci.testling.com/guide/tape
  [5]: https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404
  [6]: https://i.stack.imgur.com/q4Y3z.jpg

**Comment by Mindcraft1** [comment]
I think I figured out now, that tape can not end as long any process in a test is still running, so my problem is probably not solvable in this way. I t would be cool, if we could just force a test to end but I don't know if this would make any sense or is even possible with tapes design.

**Comment by camsjams** [comment]
You need to use t.plan in this example.
