### ISSUE TITLE
Old Browser Support With Browserify

### ISSUE THREAD

**Issue by dwighthouse** [substack/tape#456]
When testing in IE10 (and probably lower) with Tape, an error will occur:

```
This browser lacks typed array (Uint8Array) support which is required by ' + '`buffer` v5.x. Use `buffer` v4.x if you require old browser support.
```

Browserify switched its dependency on Buffer from v4 to v5 on [January 24th, 2017](https://github.com/browserify/browserify/pull/1678). Buffer v5 officially drops support for IE8 through IE10.

I was able to determine that it is Tape (or one of its dependencies), and not my code, that is making use of Buffer, and therefore triggering Browserify to attempt to include its polyfill(?), which then triggers the error in older versions of IE.

Like Tape, I'm attempting to build my library to support (and be testable) in as many browsers as possible, including older versions of IE. This means that while I can certainly use an older version of Browserify, or build my tests with two different versions of Browserify at the same time, there are some major potential side-effects of doing so:

1. I may be harming performance or compatibility with more recent or future browsers.
2. Simply by including old versions of libraries (like Browserify), I am indirectly including dependencies that represent a greater attack surface for security vulnerabilities. Even if there is no real danger, due to the potential vulnerabilities only occurring in test code, it could negatively effect the perceived security of my codebase in the eyes of NPM security audits and the like.
3. If building two different versions of my test code for the two different Browserify versions, I would have to deal with duplication of test code and pages (a minor problem).

Since Browserify is the ["recommended" method](https://github.com/substack/tape/issues/333#issuecomment-262855170) of bundling Tape tests for the Browser, and since Tape [claims to support IE6 through IE10](https://github.com/substack/tape#tape), yet current versions of Browserify don't fully support Tape, how does one square this circle?

**Comment by ljharb** [comment]
That's an interesting dilemma.

I'd be happy to accept a PR into `tape` that uses v4 of `buffer`, if that would address the issue.

In general, though, I think `browserify` should either use v4, or should provide a config option that allows it to be used (and I think filing an issue on browserify is a good idea).

**Comment by dwighthouse** [comment]
@ljharb I don't suppose there's a way to simply remove the reliance on Buffer at all in Tape, therefore preventing Browserify from trying to add its polyfill?

I just tested on IE9. The tests don't even start because something (probably again related to Buffer) triggers an uncaught error about Uint8Array not being supported by the browser (which is correct, but unhelpful).

**Comment by ljharb** [comment]
It looks like the usage of `Buffer` is in `tap-parser` as well as `lib/assert`. I don't think it's practical to remove it.

**Comment by dwighthouse** [comment]
Checking in. Any progress on this front?

**Comment by ljharb** [comment]
There’s no progress because there’s nothing actionable yet.

I’d suggest filing an issue on browserify itself to use v4 of Buffer.

**Comment by ljharb** [comment]
Closing in favor of discussion: https://github.com/browserify/browserify/pull/1678#issuecomment-458761629
