### ISSUE TITLE
Tests failing with no information: "npm ERR! Test failed.  See above for more details."

### ISSUE THREAD

**Issue by Divy123** [substack/tape#464]
The tests are failing with no errors and just with above message.
My test script is:
    "test": "TEST=true tape test/core/*.js test/core/ui/user-interface.js test/core/modules/QR.js | tap-spec; browserify test/core/modules/image-sequencer.js test/core/modules/chain.js test/core/modules/meta-modules.js test/core/modules/replace.js test/core/modules/import-export.js test/core/modules/run.js test/core/modules/dynamic-imports.js test/core/util/parse-input.js test/core/modules/benchmark.js| tape-run --render=\"tap-spec\"",
OS:Ubuntu 18.04.1
node:10.15.3
npm:6.4.1
Urgent help needed .
Thanks!!

**Comment by ljharb** [comment]
What happens if you just run:
```sh
TEST=true npx tape test/core/*.js test/core/ui/user-interface.js test/core/modules/QR.js | tap-spec; browserify test/core/modules/image-sequencer.js test/core/modules/chain.js test/core/modules/meta-modules.js test/core/modules/replace.js test/core/modules/import-export.js test/core/modules/run.js test/core/modules/dynamic-imports.js test/core/util/parse-input.js test/core/modules/benchmark.js
```
directly? (without the pipe)

**Comment by Divy123** [comment]
The tests do pass.

**Comment by ljharb** [comment]
Then it sounds like the issue is with `tape-run`, which isn't part of this package - you'll need to file it there: https://www.npmjs.com/package/tape-run
