### ISSUE TITLE
Pipe into multiple reporters?

### ISSUE THREAD

**Issue by screendriver** [substack/tape#477]
Do you know if / how it is possible to pipe the TAP output into multiple reporters at once?

For example locally I want to pipe into [tap-spec](https://github.com/scottcorgan/tap-spec) via

```js
"test:unit": "tape 'test/unit/**/*.js' | tap-spec"
```

but in a CI system I want to use [tap-xunit](https://github.com/aghassemi/tap-xunit)

```js
"test:unit:ci": "tape 'test/unit/**/*.js' | tap-xunit > dist/test-results.xml"
```

I know I could do following

```js
"test:unit:base": "tape 'test/unit/**/*.js'",
"test:unit": "yarn test:unit:base | tap-spec",
"test:unit:ci": "yarn test:unit:base | tap-xunit > dist/test-results.xml"
```

But then I have to run `test:unit` and `test:unit:ci` separately and that means the tests runs twice. Is there a way to define both reporters at once?

**Comment by ljharb** [comment]
That seems more like a unix question, and I don't think it's really possible. You might be able to direct the output to both stdout and stderr, and find something that can handle both streams, but that's beyond my unix expertise.

**Comment by screendriver** [comment]
Ok. I thought maybe one of you already has some experience with that and did that already :wink:

**Comment by ljharb** [comment]
Probably the simplest is to pipe the initial results into a file, and then you can cat the file twice.
