### ISSUE TITLE
Display line numbers 

### ISSUE THREAD

**Issue by johnsonsamuel** [substack/tape#485]
Hi Team,

Is there a way to extract the line numbers when the test fails?

Reason why I need it ?

I am currently looking into github checks api where we display annotations..

Example of annotations:

{
    "path": "README.md",
    "start_line": 2,
    "end_line": 2,
    "start_column": 5,
    "end_column": 10,
    "annotation_level": "warning",
    "title": "Spell Checker",
    "message": "Check your spelling for 'banaas'.",
    "raw_details": "Do you mean 'bananas' or 'banana'?"
  }

**Comment by ljharb** [comment]
I don't believe there is; you'd have to parse it out of a (nonstandard) stack trace.

**Comment by johnsonsamuel** [comment]
> I don't believe there is; you'd have to parse it out of a (nonstandard) stack trace.

oh ok. thanks for your reply.
