### ISSUE TITLE
Deep comparing array to object returns true

### ISSUE THREAD

**Issue by rolandas-valantinas** [substack/tape#493]
tested on `4.12.1`

```js
  actual = [
    'asd',
    'qwe',
  ];

  expected = {
    0: 'asd',
    1: 'qwe',
  };

  assert.deepEquals(actual, expected, 'test');
```
Asset returns `true`, but comparison should be strict and return `false`

**Comment by ljharb** [comment]
Try on tape@next; tape v4 and below use deep-equal v1.x which matches an older version of node.

**Comment by rolandas-valantinas** [comment]
confirmed working in `"tape": "^5.0.0-next.1"`
Any ETA on proper release?

**Comment by ljharb** [comment]
Not just yet; but hopefully not long.
