### ISSUE TITLE
`t.match` with two params logs failure message even on successful match

### ISSUE THREAD

**Issue by dchambers** [substack/tape#494]
If you omit the optional third argument when using the new the `t.match` assertion, a default message is written to the console as per all other assertions, but currently it incorrectly comes to the conclusion that the _match_ was a failure even when it passes.

For example:

```
ok 1 The input did not match the regular expression /abc/. Input: 'abc123'
```

**Comment by ljharb** [comment]
Whoops :-) good catch!
