### ISSUE TITLE
left/right instead of expected/actual in test output

### ISSUE THREAD

**Issue by substack** [substack/tape#526]
For equality comparisons, rust's test runner uses "left" and "right". I like this better than "expected" and "actual" because it takes me a moment to remember which argument is which. I'm not sure what `t.ok()` and `t.notOk()` should report.

**Comment by ljharb** [comment]
Would you think that this would be a breaking change, or that nobody would be depending on the wording in the output?

**Comment by substack** [comment]
I didn't find anything right away but I think some of the pretty output parser modules expect to find "expected" and "actual" in the yaml block so this would be a breaking change.

**Comment by ljharb** [comment]
Is that particularly worth it? It seems like a pretty minimal improvement.

**Comment by substack** [comment]
ok closing then
