### ISSUE TITLE
deepEqual may be broken?

### ISSUE THREAD

**Issue by mixmix** [substack/tape#528]
The following fails in tape@5, and passes in tape@4 ?! 

```js
const test = require('tape')

test('deepEqual', t => {
  const actual = [
    { id: '%x7tx05ZDJlZyhbFQKEMIah3i9puOE43PwuNvX4d/3rE=.sha256' },
    { id: '%/KZzVNBS97oqDtMNqaqu0mDYJT1LlXIfRn7cMcEjPLk=.sha256' }
  ]

  const expecte = [
    { id: '%x7tx05ZDJlZyhbFQKEMIah3i9puOE43PwuNvX4d/3rE=.sha256' }, 
    { id: '%/KZzVNBS97oqDtMNqaqu0mDYJT1LlXIfRn7cMcEjPLk=.sha256' }
  ]

  t.deepEqual(actual, expected)
  t.end()
})
```

**Comment by ORESoftware** [comment]
always include the error

**Comment by ljharb** [comment]
Seems to pass in tape 5 for me (with the proper variable spelling).

Happy to reopen if I can reproduce the issue (note that "works in v4, not in v5" isn't necessarily a bug, breaking changes across major versions are the reason for a major version)

**Comment by mixmix** [comment]
Thanks for comparing. Strangely when I ran the code I posted in the tape repo (@`5.0.1`) it passes for me.
In my project though I see: 

```bash
      operator: deepEqual
      expected: |-
        [ { id: '%BFLDq7Upme0Q4Jgqz+hM4eP/TQ0/S4UOTnTKwsB+tDU=.cloaked' } ]
      actual: |-
        [ { id: '%BFLDq7Upme0Q4Jgqz+hM4eP/TQ0/S4UOTnTKwsB+tDU=.cloaked' } ]
      at: Test.test (/home/mix/projects/SSBC/ssb-graphql/tribes/test/groups.test.js:51:5)
      stack: |-
  Error: should be deeply equivalent
  at Test.assert [as _assert] (/home/mix/projects/SSBC/ssb-graphql/tribes/node_modules/tape/lib/test.js:260:54)
  at Test.bound [as _assert] (/home/mix/projects/SSBC/ssb-graphql/tribes/node_modules/tape/lib/test.js:84:32)
  at Test.tapeDeepEqual (/home/mix/projects/SSBC/ssb-graphql/tribes/node_modules/tape/lib/test.js:501:10)
  at Test.bound [as deepEqual] (/home/mix/projects/SSBC/ssb-graphql/tribes/node_modules/tape/lib/test.js:84:32)
  at Test.test (/home/mix/projects/SSBC/ssb-graphql/tribes/test/groups.test.js:51:5)

```

and

```bash
      operator: deepEqual
      expected: |-
        [ { id: '%1ORk8YoGTK0A0iJ+9Vk48gAWah/fk8S8lCCmEYm5JgU=.sha256', feedId: '@geT0tPv9enmqM2mXVvcmG9FkM+pWyS56VTZmdKAHYIU=.ed25519', preferredName: 'alice' }, { id: '%hXCPRjk5TUe60OXrBUVL4EjdIvOOpJ9snQ+4UzFq52M=.sha256', feedId: '@YIY1NbjRPBl9vHrc6rNIgOnDvONto0ivjooCiIAlpw4=.ed25519', preferredName: 'bob' } ]
      actual: |-
        [ { id: '%1ORk8YoGTK0A0iJ+9Vk48gAWah/fk8S8lCCmEYm5JgU=.sha256', feedId: '@geT0tPv9enmqM2mXVvcmG9FkM+pWyS56VTZmdKAHYIU=.ed25519', preferredName: 'alice' }, { id: '%hXCPRjk5TUe60OXrBUVL4EjdIvOOpJ9snQ+4UzFq52M=.sha256', feedId: '@YIY1NbjRPBl9vHrc6rNIgOnDvONto0ivjooCiIAlpw4=.ed25519', preferredName: 'bob' } ]
      at: Test.test (/home/mix/projects/SSBC/ssb-graphql/tribes/test/authors.test.js:49:5)
      stack: |-
  Error: gets group authors
  at Test.assert [as _assert] (/home/mix/projects/SSBC/ssb-graphql/tribes/node_modules/tape/lib/test.js:260:54)
  at Test.bound [as _assert] (/home/mix/projects/SSBC/ssb-graphql/tribes/node_modules/tape/lib/test.js:84:32)
  at Test.tapeDeepEqual (/home/mix/projects/SSBC/ssb-graphql/tribes/node_modules/tape/lib/test.js:501:10)
  at Test.bound [as deepEqual] (/home/mix/projects/SSBC/ssb-graphql/tribes/node_modules/tape/lib/test.js:84:32)
  at Test.test (/home/mix/projects/SSBC/ssb-graphql/tribes/test/authors.test.js:49:5)

```

I'm running node `v10.15.3`

**Comment by mixmix** [comment]
also fails for me in node `v12.18.2`

**Comment by ljharb** [comment]
If you can create a repo that reproduces the problem, I will be able to address it very quickly.

Note that there might be things that aren't shown in the output that differentiate those objects - for example, one of them might have a `null` [[Prototype]] while the other does not.

**Comment by mixmix** [comment]
https://gitlab.com/ahau/ssb-graphql-tribes/-/merge_requests/5

**Comment by ljharb** [comment]
Thanks! I cloned it, and added a console log of the results of running `is-equal/why`, which reported "arguments have a different [[Prototype]]", as I suspected. When I then log out `Object.getPrototypeOf()` on both objects, the first gives `null` and `expected` gives `Object.prototype`.

After adding `__proto__: null` to the `expected` object (note: in every nested object literal too, not just the top) fixes the assertion. Alternatively, you can use `t.deepLooseEqual` instead of `t.deepEqual` - the default strictness of `t.deepEqual` changed in v5.

Your tests have one additional error, which is that you're using an `async function`, which returns a promise to Tape, but you're calling `t.end` asynchronously which causes a conflict. Change `ssb.close(t.end)` to `return new Promise((resolve) => ssb.close(resolve))` and that'll be resolved too (this is a fix in v5; mixing promises and callbacks in this way was always incorrect, but tape v4 ignored the returned Promise)

**Comment by mixmix** [comment]
Thank you for the detailed breakdown @ljharb  , really appreciate you taking the time to describe what was happening.
I'm confused about how the prototype thing happened ... will have to read up on that.

One strange thing about the async end problem is I see different behaviour based on how I run the tests :
- :heavy_check_mark: pass when I run `node test/authors.test.js`
- :x: fail when I run `tape test/*.test.js`  (npm run)

**Comment by ljharb** [comment]
That is very strange; but I suspect that might be some kind of test pollution due to the "sodium" stuff that pops up? I would definitely expect both of those to behave the same.
