### ISSUE TITLE
How to create a line break in my test message?

### ISSUE THREAD

**Issue by cagross** [substack/tape#535]
Hello.  How would I approach adding a line break in one of my Tape test messages?  I've tried adding a `\n`, as typically works for console.log() output, but that doesn't seem to do the trick.

**Comment by ljharb** [comment]
You can't - line breaks would violate the TAP spec, and break every TAP formatter and consumer.

You can do multiple `t.comment()`s, but each line has to start with a `#`.

**Comment by cagross** [comment]
OK thanks for that info.  I'll look into `t.comment()`--sounds like it could what I need.
