### ISSUE TITLE
How to have greaterthan() or lessthan() assertions in Tap

### ISSUE THREAD

**Issue by vipulgupta2048** [substack/tape#549]
I am bit new to this process as I am migrating some tests back to Tap. I couldn't help but notice there aren't specific assertions for the following to compare numbers. How can I write a similar test for them in Tap. I thought of using `t.ok` where I can formulate the expression into truthy value for my test but that didn't work out well. I feel I can add some more examples regarding comparisons other than just equal values. 

```
.toBeGreaterThan(number | bigint)
.toBeGreaterThanOrEqual(number | bigint)
.toBeLessThan(number | bigint)
.toBeLessThanOrEqual(number | bigint)
```

[Reference](https://jestjs.io/docs/en/expect)

**Comment by vipulgupta2048** [comment]
This could be an ideal solution -  t.ok(inputValue >= outputValue, `Values are correct.. Test passed`)

**Comment by Raynos** [comment]
I use 

```
t.ok(counter >= 5, `expected ${counter} >= 5`)
```

I put the value in the message because `t.ok()` just shows truthy / falsey.

**Comment by ljharb** [comment]
Back to tap? This is the repo for tape.

**Comment by vipulgupta2048** [comment]
My bad,
