### ISSUE TITLE
t.comment adds multiple new lines for multi-line strings

### ISSUE THREAD

**Issue by EarthyOrange** [substack/tape#570]
Given below code:
<pre>
test('test #1', (t) => {
  t.comment(
    dedent(`
      When:
       - Condition 1
       - Condition 2
    `),
  );
  // Setup Code

  t.comment('Then:');
  // Assertions
  t.end();
});
</pre>

Current Output
<pre>
test #1

When:

  - Condition 1

  - Condition 2

Then:
  ✓ Assertion
</pre>

Expected Output
<pre>
test #1

When:
  - Condition 1
  - Condition 2

Then:
  ✓ Assertion
</pre>

Why is an extra new line inserted between every line of a multi-line comment?
Can the excessive new line insertion be reduced?

https://github.com/substack/tape/blob/master/lib/test.js#L165

**Comment by ljharb** [comment]
TAP comments are meant to only be one line. It seems like a bug that it keeps the newlines at all, tbh.

**Comment by EarthyOrange** [comment]
The multi-line comment is useful. Can just the excess new-lines be removed?

**Comment by ljharb** [comment]
It would break TAP formatters - the whole point of tape is that it produces TAP-compliant output.

**Comment by EarthyOrange** [comment]
The current implementation is still compliant with the TAP protocol's requirement of a comment being a single line. If a multi-line comment is being detected then each line is being emitted separately as a comment.

**Comment by ljharb** [comment]
ah yes, you're right, we do have tests covering multiline comments. Your "current output" confused me because it omits the leading `#` :-)

What happens if you try:
```js
t.comment(
    dedent(`
      When:
       - Condition 1
       - Condition 2`),
  );
```

in other words, remove the extra trailing newline from your string input.

**Comment by EarthyOrange** [comment]
I still get the `Current Output` mentioned in the issue description.

**Comment by ljharb** [comment]
That's not what I see - with this file:
```js
var test = require('tape');
var dedent = require('dedent');

test('test #1', (t) => {
  t.comment(
    dedent(`
      When:
       - Condition 1
       - Condition 2
    `),
  );
  // Setup Code

  t.comment('Then:');
  // Assertions
  t.end();
});
```
whether run through `node` or `tape`, I get this output:
```bash
TAP version 13
# test #1
# When:
# - Condition 1
# - Condition 2
# Then:

1..0
# tests 0
# pass  0

# ok
```

Are you sure there's not something about your shell environment affecting the output? Are you perhaps using zsh and `setopt` has a bunch of options in it?

**Comment by EarthyOrange** [comment]
I am using the tap-difflet module to pretty print the results. Maybe it is printing the comments with extra new lines. I will look in to that.
