### ISSUE TITLE
More user friendly defaults

### ISSUE THREAD

**Issue by Raynos** [substack/tape#67]
There is a module called [tap-spec](https://github.com/scottcorgan/tap-spec) that prints nicely.

There is also [faucet](https://github.com/substack/faucet) that has more terse defaults.

Currently when you run `node test.js` tape just spits out `TAP` to stdout. 

What if tape checked whether stdout was a TTY and used faucet or tap-spec instead?

That way if you ever redirect stdout anywhere that's not a TTY like `| some thing` or `> some file` or `| tee some file` you will get the machine readable TAP just like you want.

However if you run `node test.js` plainly from the terminal you will get a more user friendly default output

**Comment by ljharb** [comment]
It seems like the discussion here ended up being "tape should output TAP, and a piped TAP reporter should be used for anything else", so I think this can be closed. Happy to reopen if not.
