### ISSUE TITLE
Better error stack traces reporting

### ISSUE THREAD

**Issue by Raynos** [substack/tape#68]
@chrisdickinson mentioned that tape doesn't print stack traces properly.

Reporting error cases for failing tests in a clean fashion is important for debugging & testing.

@chrisdickinson should provide more feedback and I can write a PR for some (failing) tests around a more descriptive error output and update the renderer

**Comment by scottcorgan** [comment]
@domenic just published `3.0.0` for tap-spec. Includes some prova-like error reporting.

**Comment by tschaub** [comment]
What are people doing when debugging test failures in a headed browser?  The output below is just from a single failing test.  I can't imagine where I'd start with a failure buried in 100s of passing tests.

![image](https://cloud.githubusercontent.com/assets/41094/7484289/0180eff2-f344-11e4-9629-2639abc6345d.png)

(The failing assertion is in test.js line 6, and there is an inline sourcemap in the test.js bundle.)

**Comment by Raynos** [comment]
@tschaub I try to reproduce it in node and then use that workflow.

if its a browser specific bug then i use `test.only` after I find it.

**Comment by gritzko** [comment]
My findings so far: row.file points to a random location inside tape, which is not helpful.
I send failed test stack traces to the console, so I can click on them.
![tape-dom](https://cloud.githubusercontent.com/assets/81581/8984306/65769f4c-36d9-11e5-9033-f563b5c82c0b.png)

**Comment by tcurdt** [comment]
tape-spec is nice - but (at least for me) does not provide stacktrace or file and line number either.

**Comment by ljharb** [comment]
This seems closed in #265 / #330.
