### ISSUE TITLE
Error Stack in Safari

### ISSUE THREAD

**Issue by azer** [substack/tape#80]
Looks like Safari produce error objects with no stack information at this line: https://github.com/substack/tape/blob/master/lib/test.js#L189

**Comment by ljharb** [comment]
@azer altho this is now on [this line](https://github.com/substack/tape/blob/master/lib/test.js#L215) - if you make that change locally - wrapping it in a try/catch and throwing it - does the stack information show up in Safari? (also, which version of Safari?)
