### ISSUE TITLE
Getting mojibake on windows

### ISSUE THREAD

**Issue by justan** [substack/tape#85]
When i run some chinese test on windows,  i'm getting mojibake. 

My test is:
```javascript
test('构造函数', function(t) {
  t.ok(typeof Ant === 'function', 'Ant 是个构造函数');
  t.end();
});
```

Output getting mojibake:
```
TAP version 13
# 鏋勯€犲嚱鏁?ok 1 Ant 鏄釜鏋勯€犲嚱鏁?
1..1
# tests 1
# pass  1

# ok
```

V2.13.0 (using `console.log` instead of `fs.writeSync`)  getting the right output:
```
TAP version 13
# 构造函数
ok 1 Ant 是个构造函数

1..1
# tests 1
# pass  1

# ok
```

This should be cause by #84.

**Comment by ljharb** [comment]
@justan is this still an issue? Please reopen if so.
