### ISSUE TITLE
t.comment() = fail exit code

### ISSUE THREAD

**Issue by timoxley** [substack/tape#92]
Is this correct behaviour?

Including any test comments seems to fail a suite.

```js
// test.js
var test = require('tape')

test('comment test', function(t) {
  t.comment('this is a comment')
  t.ok(true)
  t.end()
})
```

```
> tape test.js
TAP version 13
# comment test
# this is a comment
ok 1 (unnamed assert)

1..1
# tests 1
# pass  1

# ok


> echo $?
1
```

**Comment by davidtheclark** [comment]
I'm still having this problem. Addition of a single comment is causing exit code 1 despite all tests passing; remove the comment and everything's fine.

**Comment by grit96** [comment]
This is still a bug in v4.0.1

**Comment by soundyogi** [comment]
+1 
getting exit code 1
