### ISSUE TITLE
Equality for NaN

### ISSUE THREAD

**Issue by chrisveness** [substack/tape#96]
How do you assert a result is NaN? `assert.equal(NaN, NaN)` fails, as one would expect.

Thx.

**Comment by dy** [comment]
How about arrays?
```js
t.deepEqual(new Float32Array([NaN, NaN]), [NaN, NaN])
```

**Comment by dy** [comment]
@ljharb every assert this way creates a log line in console, in case if there is hundreds/thousands of elements...
I used
```js
t.ok(arr.every(isNaN))
```

**Comment by ljharb** [comment]
Sure, that works too.

**Comment by Raynos** [comment]
I've used a collapsed-assert class for that use case ( https://github.com/uber/tchannel-node/blob/master/test/lib/collapsed-assert.js ).

[Example: ](https://github.com/uber/tchannel-node/blob/5477673abf0908c07f39b2f2a77e7081a207ae82/test/relay-under-timeouts.js#L58-L69)

```
        var cassert = CollapsedAssert();

        for (var i = 0; i < data.errors.length; i++) {
            cassert.equal(data.errors[i].type, 'tchannel.request.timeout');
        }

        for (var j = 0; j < data.results.length; j++) {
            cassert.equal(data.results[j].responseOk, false);
            cassert.equal(data.results[j].error.type, 'tchannel.timeout');
        }

        cassert.report(assert, 'all response are errors');
```

If any asserts fail all asserts are printed ; if they all pass , a single assert is printed.
